version: 2
updates:
  # GitHub Actions päivitykset
  - package-ecosystem: "github-actions"
    # Etsi GitHub Actions riippuvuuksia kaikista relevanteista hakemistoista
    # Eli, etsitään .yml tiedostoja, joissa voisi olla päivitettäviä riippuvuuksia
    directories:
      - "/.github/actions/*"
      - "/.github/workflows"
    groups:
      # Ryhmittele eri tiedostoistä löytyneet riippuvuudet samaan PR:ään
      trivy-action:
        patterns:
          - "aquasecurity/trivy-action*"
      docker-login-action:
        patterns:
          - "docker/login-action*"
      sarif-upload-action:
        patterns:
          - "github/codeql-action/upload-sarif*"
      cache-action:
        patterns:
          - "actions/cache*"
      setup-java-action:
        patterns:
          - "actions/setup-java*"
      junit-report-action:
        patterns:
          - "mikepenz/action-junit-report*"

    schedule:
      interval: "weekly"

  # Dcoker image päivitykset
  - package-ecosystem: "docker"
    directory: "/aws/fargate/"
    # Check for updates once a week
    schedule:
      interval: "weekly"

  # tietokanta pom.xml maven plugin päivitykset
  - package-ecosystem: "maven"
    directory: /tietokanta
    schedule:
      interval: "weekly"
    groups:
      # Ryhmittele flyway päivitykset samaan PR:ään
      flyway:
        patterns:
          - "org.flywaydb*"
