version: 2
updates:
  # GitHub Actions päivitykset
  - package-ecosystem: "github-actions"
    # Etsi GitHub Actions riippuvuuksia kaikista relevanteista hakemistoista
    # Eli, etsitään .yml tiedostoja, joissa voisi olla päivitettäviä riippuvuuksia
    directories:
      - "/.github/actions/*"
      - "/.github/workflows"
    groups:
      # Ryhmittele eri tiedostoistä löytyneet riippuvuudet samaan PR:ään
      trivy-action:
        patterns:
          - "aquasecurity/trivy-action*"
      docker-login-action:
        patterns:
          - "docker/login-action*"
      codeql-action:
        patterns:
          - "github/codeql-action*"
      cache-action:
        patterns:
          - "actions/cache*"
      setup-java-action:
        patterns:
          - "actions/setup-java*"
      junit-report-action:
        patterns:
          - "mikepenz/action-junit-report*"
    ignore:
      # Älä päivitä näihin versioihin
      - dependency-name: "aquasecurity/trivy-action*"
        versions:
          - "0.27.0"
    schedule:
      interval: "weekly"
    # Mitigoi supply chain-hyökkäyksen riskiä cooldown-ajalla, joka viivyttää uuden päivityksen tarjoamista x päivää
    cooldown:
      default-days: 3

  # Dcoker image päivitykset
  - package-ecosystem: "docker"
    directory: "/aws/fargate/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Mitigoi supply chain-hyökkäyksen riskiä cooldown-ajalla, joka viivyttää uuden päivityksen tarjoamista x päivää
    # FIXME: Cooldown estää Docker-imageiden päivityksen
    #        Bug: https://github.com/dependabot/dependabot-core/issues/14044
#    cooldown:
#      default-days: 3

  # tietokanta pom.xml maven plugin päivitykset
  - package-ecosystem: "maven"
    directory: /tietokanta
    schedule:
      interval: "weekly"
    # Mitigoi supply chain-hyökkäyksen riskiä cooldown-ajalla, joka viivyttää uuden päivityksen tarjoamista x päivää
    cooldown:
      default-days: 3
    groups:
      # Ryhmittele flyway päivitykset samaan PR:ään
      flyway:
        patterns:
          - "org.flywaydb*"
