version: 2
updates:
  # GitHub Actions päivitykset
  - package-ecosystem: "github-actions"
    # Etsi GitHub Actions riippuvuuksia kaikista relevanteista hakemistoista
    # Eli, etsitään .yml tiedostoja, joissa voisi olla päivitettäviä riippuvuuksia
    directories:
      - "/.github/actions/*"
      - "/.github/workflows"
    groups:
      # Ryhmittele löytyneet GitHub Actions riippuvuudet loogisesti mielekkäisiin ryhmiin
      # Yhtä ryhmää kohden avataan aina yksi PR, joka sisältää kaikki kyseisen ryhmän päivitykset

      # Perustason CI-actionit, joita löytyy useista workflow-tiedostoista
      ci-infra:
        patterns:
          - "actions/checkout*"
          - "actions/cache*"
          - "actions/github-script*"
          - "actions/stale*"

      # Teknologiakohtaiset setup-actionit (Java, Node, Clojure, Python, jne.)
      ci-setup:
        patterns:
          - "actions/setup-*"
          - "DeLaGuardo/setup-clojure*"
          - "astral-sh/setup-uv*"

      # Artifaktien käsittelyyn ja hallintaan liittyvät actionit
      ci-artifacts:
        patterns:
          - "actions/upload-artifact*"
          - "actions/download-artifact*"

      # Docker build pipelinen actionit
      docker:
        patterns:
          - "docker/*"

      # AWS deployment- ja infra-actionit
      aws:
        patterns:
          - "aws-actions/*"

      # Tietoturva-analyysi
      trivy:
        patterns:
          - "aquasecurity/trivy-action*"

      # Koodianalyysi
      code-analysis:
        patterns:
          - "github/codeql-action*"

      # Testiraportit
      test-reports:
        patterns:
          - "mikepenz/action-junit-report*"

      # Notifikaatiot
      notifications:
        patterns:
          - "slackapi/slack-github-action*"
    ignore:
      # Älä päivitä näihin versioihin
      - dependency-name: "aquasecurity/trivy-action*"
        versions:
          - "0.27.0"
    schedule:
      interval: "weekly"
    # Mitigoi supply chain-hyökkäyksen riskiä cooldown-ajalla, joka viivyttää uuden päivityksen tarjoamista x päivää
    cooldown:
      default-days: 3

  # Dcoker image päivitykset
  - package-ecosystem: "docker"
    directory: "/aws/fargate/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Mitigoi supply chain-hyökkäyksen riskiä cooldown-ajalla, joka viivyttää uuden päivityksen tarjoamista x päivää
    # FIXME: Cooldown estää Docker-imageiden päivityksen
    #        Bug: https://github.com/dependabot/dependabot-core/issues/14044
  #    cooldown:
  #      default-days: 3

  # tietokanta pom.xml maven plugin päivitykset
  - package-ecosystem: "maven"
    directory: /tietokanta
    schedule:
      interval: "weekly"
    # Mitigoi supply chain-hyökkäyksen riskiä cooldown-ajalla, joka viivyttää uuden päivityksen tarjoamista x päivää
    cooldown:
      default-days: 3
    groups:
      # Ryhmittele tietokantaan liittyvät riippuvuudet (flyway, postgresql)
      # Huom: Renovatella päivitetään Postgresql-ajurin Clojure-riippuvuus
      database-deps:
        patterns:
          - "org.flywaydb*"
          - "org.postgresql*"
