# Tätä docker-compose-fileä käytetään githubin actionseissa esimerkiksi testitietokannan helpompaan käynnistämiseen
# Samalla varmistetaan, että tarvittavat ympäristömuuttujat on asetettu ja oikeat volumet on mountattu.
# Tämä tiedosto on tarkoitettu käytettäväksi vain Github Actionseissa

version: "3.8"

networks:
  harja_net:
    driver: bridge

services:
  harjadb:
    # Hae image GitHubin container registrystä
    image: ghcr.io/finnishtransportagency/harja_harjadb:latest
    container_name: harjadb
    networks:
      - harja_net
    environment:
      HARJA_TIETOKANTA_PORTTI: 5432
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ../tietokanta:/var/lib/postgresql/harja/tietokanta
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "harja", "-d", "harja"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 10s

# TODO: Disabloitu. Toteutetaan myöhemmin.
#  cypress:
#    image: ghcr.io/finnishtransportagency/harja_cypress:latest
#    container_name: cypress
#    networks:
#      - harja_net



