name: 'Start Harja Fargate tasks'
description: 'Käynnnistää uudelleen Harja servicen käynnissä olevat Fargate taskit (OIDC autentikaatio vaadittu)'

inputs:
  cluster:
    description: "Harja app Fargate cluster name"

runs:
  using: "composite"
  steps:
    - name: Start Fargate tasks
      env:
        SHA: ${{ inputs.commit-sha }}
        CLUSTER_NAME: ${{ inputs.cluster }}
        SERVICE_NAME: ${{ inputs.service }}
        DESIRED_COUNT: "1"
        WAIT_TIME_SEC: "10"

      # Komennon 'update-service' stdout ohjataan /dev/nulliin, koska se voi tulostaa sensitiivisiä tietoja
      run: |
        echo "Getting available service: ${SERVICE_NAME}"        
        AVAILABLE_SERVICE=$(aws ecs list-services --cluster "${CLUSTER_NAME}" --region eu-west-1 --query "serviceArns[?contains(@, \`${SERVICE_NAME}\`) == \`true\`] | [0]" --output text)
        
        echo "Starting tasks..."
        aws ecs update-service --cluster "${CLUSTER_NAME}" --service $AVAILABLE_SERVICE \
        --desired-count "${DESIRED_COUNT}" --region eu-west-1  1> /dev/null
        
        echo "Waiting for services to be stable..."
        aws ecs wait services-stable \
          --cluster "${CLUSTER_NAME}" --services "${AVAILABLE_SERVICE}" --region eu-west-1
        echo "Done."
      shell: bash


