name: 'Start Harja Fargate tasks'
description: 'Käynnnistää uudelleen Harja servicen käynnissä olevat Fargate taskit (OIDC autentikaatio vaadittu)'

inputs:
  cluster:
    description: "Harja app Fargate cluster name"

runs:
  using: "composite"
  steps:
    - name: Start Fargate tasks
      env:
        SHA: ${{ inputs.commit-sha }}
        CLUSTER_NAME: ${{ inputs.cluster }}
        DESIRED_COUNT: "1"
        WAIT_TIME_SEC: "10"

      # Komennon 'update-service' stdout ohjataan /dev/nulliin, koska se voi tulostaa sensitiivisiä tietoja
      run: |
        echo "Getting available service..."
        AVAILABLE_SERVICE=$(aws ecs list-services --cluster "${CLUSTER_NAME}" --region eu-west-1 | jq -r '.serviceArns[0]')
        
        echo "Starting tasks..."
        aws ecs update-service --cluster "${CLUSTER_NAME}" --service $AVAILABLE_SERVICE \
        --desired-count "${DESIRED_COUNT}" --region eu-west-1  1> /dev/null
        
         while true; do
            runningTasks=$(aws ecs list-tasks --cluster "${CLUSTER_NAME}" --service-name "$AVAILABLE_SERVICE" --region eu-west-1 | jq '.taskArns')
        
            if [ $(echo "$runningTasks" | jq length) -eq 0 ]; then
              echo "No running Fargate tasks found. Waiting ${WAIT_TIME_SEC} seconds..."
              sleep "${WAIT_TIME_SEC}"
            else
              echo "Fargate service restart successful."
              break
            fi
          done
        
        echo "Done."
      shell: bash


