# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  #config.vm.network "public_network"
  # forwardoidaan postgresql:n portti
  config.vm.network "forwarded_port", guest: 5432, host: 5432
  # nginx proxyn forwardointi
  config.vm.network "forwarded_port", guest: 8000, host: 8000
  # ActiveMQ web UI & JSM portit
  config.vm.network "forwarded_port", guest: 8161, host: 8161
  config.vm.network "forwarded_port", guest: 61616, host: 61616

  # config.vm.network "private_network", ip: "192.168.33.10"

  # config.vm.network "public_network"

  config.vm.synced_folder "../../harja-tietokanta", "/harja-tietokanta", :mount_options => ["dmode=777", "fmode=666"]

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "2048"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "db_provision.yml"
  end
end
