# TODO: Toteuta cypress-image, jota ajetaan taustalla. Ota mallia .github/docker imageista.
#
#       Tallenna cypress image .github/docker polkuun ja lähetä image Harjan repon Container Registryyn
#
#       Cypressillä on myös hyviä omia pohja-imageita, joita voi käyttää: https://github.com/cypress-io/cypress-docker-images
#
#       Muista käyttää yhteistä docker-composessa määriteltyä harja_net verkkoa
#          Katso: .github/docker-compose.yml

name: 'Start Cypress'
description: 'Käynnistää Cyperss kontin taustalle'

inputs:
  registry:
    description: 'Container registry, josta haetaan cypress kontin image'
    required: true
    default: 'ghcr.io'
  username:
    description: ''
    required: true
  password:
    description: ''
    required: true

runs:
  using: "composite"
  steps:
    - name: Log in to the Container registry
      uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Pull and start cypress image
      run: |
        cd .github
        echo "Pulling harja cypress image (Docker Compose version: $(docker-compose version --short))"
        docker compose pull cypress

        echo "Starting cypress and waiting for it to start (Docker Compose version: $(docker-compose version --short))"
        docker compose up -d --wait --wait-timeout 60 cypress
      shell: bash


