# TODO: Toteuta cypress-image, jota ajetaan taustalla. Ota mallia .github/docker imageista.
#
#       Tallenna cypress image .github/docker polkuun ja lähetä image Harjan repon Container Registryyn
#
#       Cypressillä on myös hyviä omia pohja-imageita, joita voi käyttää: https://github.com/cypress-io/cypress-docker-images
#
#       Muista käyttää yhteistä docker-composessa määriteltyä harja_net verkkoa
#          Katso: .github/docker-compose.yml

name: 'Start Cypress'
description: 'Käynnistää Cypress kontin ja ajaa komennon sen sisällä kerran'

inputs:
  registry:
    description: 'Container registry, josta haetaan cypress kontin image'
    required: true
    default: 'ghcr.io'
  username:
    description: ''
    required: true
  password:
    description: ''
    required: true
  image:
    description: 'Cypress kontin imagen nimi'
    required: false
    default: ghcr.io/finnishtransportagency/harja_cypress:latest
  GITHUB_WORKSPACE:
    description: 'Github jobin workspace path. Tämä mountataan cypress kontin sisälle.'
    required: true


runs:
  using: "composite"
  steps:
    - name: Log in to the Container registry
      uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Pull image
      env:
        IMAGE_NAME: ${{ inputs.image }}
      run: |
        echo "Pulling harja cypress image"
        docker pull "$IMAGE_NAME"
      shell: bash

    - name: Aja cypress-testit
      env:
        IMAGE_NAME: ${{ inputs.registry }}
        GITHUB_WORKSPACE: ${{ inputs.GITHUB_WORKSPACE }}
      run: |
        echo "Ajetaan cypress komento kontissa"
        
        docker run \
          --network host \
          -v $GITHUB_WORKSPACE:/harja \
          -w /harja \
          ghcr.io/finnishtransportagency/harja_cypress:latest \
          cypress run --browser chrome
      shell: bash

