name: 'Run migrations to RDS'
description: 'Ajaa migraatiot Aurora RDS kantaan kohdeympäristöön'

inputs:
  commit-sha:
    description: ''
    required: true

runs:
  using: "composite"
  steps:
    - name: Run migrations to RDS using lambda
      env:
        SHA: ${{ inputs.commit-sha }}

      run:  |
        echo "Run migrations to RDS using lambda"
        aws lambda invoke --function-name "HarjaMigrationRunner" --invocation-type "RequestResponse" --cli-read-timeout 0 \
        --cli-binary-format raw-in-base64-out --payload '{"payload":{"sha":"${SHA}"}}' result.json
        
        RESULT=$(cat result.json)
        
        if [[ "$RESULT" = "success" ]; then
          echo "Migration succesful"
        else
          echo "Migration failed!"
          echo "Result: $RESULT"
          
          exit 1
        fi

      shell: bash


