name: 'Run migrations to RDS'
description: 'Ajaa migraatiot Aurora RDS kantaan kohdeympäristöön'

inputs:
  commit-sha:
    description: ''
    required: true

# FIXME: aws lambda invoke harvakseltaan epäonnistuu siten, että se ei saa responsea ja ennenpitkää timeouttaa.
#        Vaikka kuitenkin, migraatio-lambda menee läpi onnistuneesti AWS:n puolella ja lähettää response payloadin.
#
#        AWS CLI v2 ohjeistus ohjaa säätämään esim. käyttöjärjestelmän "TCP keep alive" -asetuksia, mutta miten se onnistuu
#        Github actionseissa, en vielä tiedä.
#        https://github.com/aws/aws-cli/issues/5783
runs:
  using: "composite"
  steps:
    - name: Run migrations to RDS using lambda
      env:
        SHA: ${{ inputs.commit-sha }}
        TIMEOUT: "900"

      run:  |
        echo "Run migrations to RDS using lambda (Timeout ${TIMEOUT} sec)"
        
        readonly payload="{\"payload\":{\"sha\":\"${SHA}\"}}"
        
        aws lambda invoke --function-name "HarjaMigrationRunner" --invocation-type "RequestResponse" \
        --cli-read-timeout "${TIMEOUT}" \
        --cli-binary-format raw-in-base64-out --payload "$payload" result.json
        
        RESULT=$(cat result.json)
        
        if [[ "$RESULT" = "success" ]]; then
        echo "Migration succesful"
        else
          echo "Migration failed!"
          echo "Result: $RESULT"
        
          exit 1
        fi

      shell: bash


