name: 'Start test database'
description: 'Käynnistää testitietokannan taustalle ja ajaa siihen migraatiot ja testidataa'

inputs:
  registry:
    description: 'Container registry, josta haetaan testitietokannan image'
    required: true
    default: 'ghcr.io'
  username:
    description: ''
    required: true
  password:
    description: ''
    required: true
  # Katso saatavilla olevat versiot docker-compose.yml:stä (esim. harjadb-latest)
  # Versiot on lukittu docker-compose konfiguraatioksi ja konfiguraatiossa viitataan aina tiettyyn imagen
  # versioon.
  image-version:
    description: 'Testitietokannan imagen versio. Saatavilla olevat versiot on määritelty docker-compose.yml:ään'
    required: true

runs:
  using: "composite"
  steps:
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Pull and start test database
      env:
        IMAGE_VERSION: ${{ inputs.image-version }}
      run: |
        cd .github/docker
        echo "Pulling harja test database image (Docker Compose version: $(docker-compose version --short))"
        docker compose pull "${IMAGE_VERSION}"

        echo "Starting harja test database and waiting for it to start (Docker Compose version: $(docker-compose version --short))"
        docker compose up -d --wait --wait-timeout 60 "${IMAGE_VERSION}"
      shell: bash

    - name: Run migrations and test data into harja-postgres service
      run: |
        docker ps -a

        echo "Running migrations and test data into harja-postgres service"
        docker exec --user postgres harjadb /bin/bash -c "~/aja-migraatiot.sh"
        docker exec --user postgres harjadb /bin/bash -c "~/aja-testidata.sh"
      shell: bash
