name: 'Start test database'
description: 'Käynnistää testitietokannan taustalle ja ajaa siihen migraatiot ja testidataa'

inputs:
  registry:
    description: 'Container registry, josta haetaan testitietokannan image'
    required: true
    default: 'ghcr.io'
  username:
    description: ''
    required: true
  password:
    description: ''
    required: true
  # Katso saatavilla olevat harjadb servicet docker-compose.yml:stä (esim. harjadb-latest)
  # Servicen asetukset on lukittu docker-compose konfiguraatioksi ja konfiguraatiossa viitataan aina tiettyyn imagen
  # versioon.
  service-name:
    description: 'Testitietokannan compose servicen nimi. Saatavilla olevat servicet on määritelty docker-compose.yml:ään'
    required: true

runs:
  using: "composite"
  steps:
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Pull and start test database
      env:
        SERVICE_NAME: ${{ inputs.service-name }}
      run: |
        cd .github/docker
        echo "Docker Compose version: $(docker-compose version --short)"
        
        echo "Pulling harja test database docker image for service: ${SERVICE_NAME}"
        docker compose pull "${SERVICE_NAME}"

        echo "Starting test database service and waiting for it to start..."
        docker compose up -d --wait --wait-timeout 60 "${SERVICE_NAME}"
      shell: bash

    - name: Run migrations and test data into harja-postgres service
      run: |
        docker ps -a

        echo "Running migrations and test data into harja-postgres service..."
        docker exec --user postgres harjadb /bin/bash -c "~/aja-migraatiot.sh"
        docker exec --user postgres harjadb /bin/bash -c "~/aja-testidata.sh"
      shell: bash

    - name: Print DB version details
      run: |
        echo ""
        echo "-------------"
        echo ""
        
        echo "PostgreSQL version details:"
        
        docker exec --user postgres harjadb psql -c 'SELECT version();'
        docker exec --user postgres harjadb psql -U harja -c 'SELECT extname, extversion FROM pg_extension;'
      shell: bash
