name: 'Setup Clojure environment'
description: 'Asentaa Clojure-kehitysympäristön ja lataa riippuvuudet'

inputs:
  install-tools:
    description: 'Asennetaanko clj-työkalut?'

runs:
  using: "composite"
  steps:
    - name: Prepare java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Cache Clojure Dependencies
      id: cache-clojure-deps
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-leiningen-${{ hashFiles('**/project.clj') }}
        # https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#matching-a-cache-key
        # "restore-keys allows you to specify a list of alternate restore keys to use when there is a cache miss on key. "
        # Kommentoitu pois, jotta PR brancheissä ei haeta aina cachesta potentiaalisesti vääriä clojure depsuja
        #restore-keys: ${{ runner.os }}-leiningen-

    # https://github.com/DeLaGuardo/setup-clojure
    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@1c76ab0e154379260d7a6ea16b413679abe46785 # versio 11
      if: ${{ inputs.install-tools }} == 'true'
      with:
        clj-kondo: 2023.07.13
        #lein: 2.9.8

    - name: Download Clojure dependencies
      if: steps.cache-clojure-deps.outputs.cache-hit != 'true'
      run: lein deps
      shell: bash


