(ns harja.palvelin.integraatiot.api.tyokalut.xml-esimerkit)

(def +hae-tietolaji-request+ "xsd/tierekisteri/esimerkit/hae-tietolaji-request.xml")
(def +hae-tietue-request+ "xsd/tierekisteri/esimerkit/hae-tietue-request.xml")
(def +hae-tietueet-request+ "xsd/tierekisteri/esimerkit/hae-tietueet-request.xml")
(def +hae-urakantietueet-request+ "xsd/tierekisteri/esimerkit/hae-urakan-tietueet-request.xml")
(def +lisaa-tietue-request+ "xsd/tierekisteri/esimerkit/lisaa-tietue-request.xml")
(def +paivita-tietue-request+ "xsd/tierekisteri/esimerkit/paivita-tietue-request.xml")
(def +poista-tietue-request+ "xsd/tierekisteri/esimerkit/poista-tietue-request.xml")
(def +hae-tietue-response+ "xsd/tierekisteri/esimerkit/hae-tietue-response.xml")
(def +hae-tietueet-response+ "xsd/tierekisteri/esimerkit/hae-tietueet-response.xml")
(def +ok-vastaus-response+ "xsd/tierekisteri/esimerkit/ok-vastaus-response.xml")
(def +virhe-tietueen-lisays-epaonnistui-response+ "xsd/tierekisteri/esimerkit/virhe-tietueen-lisays-epaonnistui-response.xml")
(def +virhe-vastaus-tietolajia-ei-loydy-response+ "xsd/tierekisteri/esimerkit/virhe-vastaus-tietolajia-ei-loydy-response.xml")
(def +virhe-vastaus-tietuetta-ei-loydy-response+ "xsd/tierekisteri/esimerkit/virhe-vastaus-tietuetta-ei-loydy-response.xml")
(def +ilmoitus+ "xsd/tloik/esimerkit/ilmoitus.xml")
(def +ilmoitustoimenpide+ "xsd/tloik/esimerkit/ilmoitustoimenpide.xml")
(def +harja-kuittaus+ "xsd/tloik/esimerkit/harja-kuittaus.xml")
(def +vastaanottokuittus+ "xsd/tloik/esimerkit/tloik-kuittaus.xml")
(def +ilmoitusperuutus+ "xsd/tloik/esimerkit/ilmoitus-peruutus.xml")
