name: 'Start test activemq'
description: 'Käynnistää ActiveMQ:n taustalle'

inputs:
  registry:
    description: 'Container registry, josta haetaan activemq image'
    required: true
    default: 'ghcr.io'
  username:
    description: ''
    required: true
  password:
    description: ''
    required: true

runs:
  using: "composite"
  steps:
    - name: Log in to the Container registry
      uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Pull and start test activemq
      run: |
        cd .github
        echo "Pulling harja activemq image (Docker Compose version: $(docker-compose version --short))"
        docker compose pull activemq-itmf

        echo "Starting harja activemq and waiting for it to start (Docker Compose version: $(docker-compose version --short))"
        docker compose up -d --wait --wait-timeout 60 activemq-itmf
      shell: bash
