-- Lisätään Oulun MHU 2019-2024 urakalle eksoottisempi rahavaraus, että voidaan testata niiden huomioimista laskutusyhteenvedolla
INSERT INTO rahavaraus_urakka (urakka_id, rahavaraus_id, luotu, luoja)
VALUES ((select id from urakka where nimi = 'Oulun MHU 2019-2024'),
        (select id from rahavaraus where nimi = 'Varalaskupaikat'), current_timestamp,
        (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'));


-- tässä nyt luodaan testidatan kirjoittamishetkeen verrattuna tulevaisuuteen indeksikorjattuja rivejä, jotta voidaan varmistaa Muutosten laskentojen oikeellisuutta...
INSERT INTO kustannusarvioitu_tyo (vuosi, kuukausi, summa, tyyppi, tehtava, tehtavaryhma, toimenpideinstanssi, sopimus, luotu, luoja, summa_indeksikorjattu, indeksikorjaus_vahvistettu, vahvistaja, osio, rahavaraus_id)
VALUES
    (2025, 10, 10000, 'akillinen-hoitotyo', (SELECT ID FROM tehtava WHERE yksiloiva_tunniste = '1ed5d0bb-13c7-4f52-91ee-5051bb0fd974'), null, (SELECT id FROM toimenpideinstanssi WHERE nimi = 'Iin MHU 2021-2026 Liikenneympäristön hoito TP'), (SELECT id FROM sopimus WHERE nimi = 'MHU Ii sopimus'), NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 11100, NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 'tavoitehintaiset-rahavaraukset', (SELECT id FROM rahavaraus WHERE nimi = 'Äkilliset hoitotyöt')),
    (2025, 11, 10000, 'akillinen-hoitotyo', (SELECT ID FROM tehtava WHERE yksiloiva_tunniste = '1ed5d0bb-13c7-4f52-91ee-5051bb0fd974'), null, (SELECT id FROM toimenpideinstanssi WHERE nimi = 'Iin MHU 2021-2026 Liikenneympäristön hoito TP'), (SELECT id FROM sopimus WHERE nimi = 'MHU Ii sopimus'), NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 11100, NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 'tavoitehintaiset-rahavaraukset', (SELECT id FROM rahavaraus WHERE nimi = 'Äkilliset hoitotyöt')),
    (2025, 12, 10000, 'akillinen-hoitotyo', (SELECT ID FROM tehtava WHERE yksiloiva_tunniste = '1ed5d0bb-13c7-4f52-91ee-5051bb0fd974'), null, (SELECT id FROM toimenpideinstanssi WHERE nimi = 'Iin MHU 2021-2026 Liikenneympäristön hoito TP'), (SELECT id FROM sopimus WHERE nimi = 'MHU Ii sopimus'), NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 11100, NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 'tavoitehintaiset-rahavaraukset', (SELECT id FROM rahavaraus WHERE nimi = 'Äkilliset hoitotyöt')),
    (2026, 1, 10000, 'akillinen-hoitotyo', (SELECT ID FROM tehtava WHERE yksiloiva_tunniste = '1ed5d0bb-13c7-4f52-91ee-5051bb0fd974'), null, (SELECT id FROM toimenpideinstanssi WHERE nimi = 'Iin MHU 2021-2026 Liikenneympäristön hoito TP'), (SELECT id FROM sopimus WHERE nimi = 'MHU Ii sopimus'), NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 11100, NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 'tavoitehintaiset-rahavaraukset', (SELECT id FROM rahavaraus WHERE nimi = 'Äkilliset hoitotyöt')),
    (2026, 2, 10000, 'akillinen-hoitotyo', (SELECT ID FROM tehtava WHERE yksiloiva_tunniste = '1ed5d0bb-13c7-4f52-91ee-5051bb0fd974'), null, (SELECT id FROM toimenpideinstanssi WHERE nimi = 'Iin MHU 2021-2026 Liikenneympäristön hoito TP'), (SELECT id FROM sopimus WHERE nimi = 'MHU Ii sopimus'), NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 11100, NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 'tavoitehintaiset-rahavaraukset', (SELECT id FROM rahavaraus WHERE nimi = 'Äkilliset hoitotyöt')),
    (2026, 3, 10000, 'akillinen-hoitotyo', (SELECT ID FROM tehtava WHERE yksiloiva_tunniste = '1ed5d0bb-13c7-4f52-91ee-5051bb0fd974'), null, (SELECT id FROM toimenpideinstanssi WHERE nimi = 'Iin MHU 2021-2026 Liikenneympäristön hoito TP'), (SELECT id FROM sopimus WHERE nimi = 'MHU Ii sopimus'), NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 11100, NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 'tavoitehintaiset-rahavaraukset', (SELECT id FROM rahavaraus WHERE nimi = 'Äkilliset hoitotyöt')),
    (2026, 4, 10000, 'akillinen-hoitotyo', (SELECT ID FROM tehtava WHERE yksiloiva_tunniste = '1ed5d0bb-13c7-4f52-91ee-5051bb0fd974'), null, (SELECT id FROM toimenpideinstanssi WHERE nimi = 'Iin MHU 2021-2026 Liikenneympäristön hoito TP'), (SELECT id FROM sopimus WHERE nimi = 'MHU Ii sopimus'), NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 11100, NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 'tavoitehintaiset-rahavaraukset', (SELECT id FROM rahavaraus WHERE nimi = 'Äkilliset hoitotyöt')),
    (2026, 5, 10000, 'akillinen-hoitotyo', (SELECT ID FROM tehtava WHERE yksiloiva_tunniste = '1ed5d0bb-13c7-4f52-91ee-5051bb0fd974'), null, (SELECT id FROM toimenpideinstanssi WHERE nimi = 'Iin MHU 2021-2026 Liikenneympäristön hoito TP'), (SELECT id FROM sopimus WHERE nimi = 'MHU Ii sopimus'), NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 11100, NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 'tavoitehintaiset-rahavaraukset', (SELECT id FROM rahavaraus WHERE nimi = 'Äkilliset hoitotyöt')),
    (2026, 6, 10000, 'akillinen-hoitotyo', (SELECT ID FROM tehtava WHERE yksiloiva_tunniste = '1ed5d0bb-13c7-4f52-91ee-5051bb0fd974'), null, (SELECT id FROM toimenpideinstanssi WHERE nimi = 'Iin MHU 2021-2026 Liikenneympäristön hoito TP'), (SELECT id FROM sopimus WHERE nimi = 'MHU Ii sopimus'), NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 11100, NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 'tavoitehintaiset-rahavaraukset', (SELECT id FROM rahavaraus WHERE nimi = 'Äkilliset hoitotyöt')),
    (2026, 7, 10000, 'akillinen-hoitotyo', (SELECT ID FROM tehtava WHERE yksiloiva_tunniste = '1ed5d0bb-13c7-4f52-91ee-5051bb0fd974'), null, (SELECT id FROM toimenpideinstanssi WHERE nimi = 'Iin MHU 2021-2026 Liikenneympäristön hoito TP'), (SELECT id FROM sopimus WHERE nimi = 'MHU Ii sopimus'), NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 11100, NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 'tavoitehintaiset-rahavaraukset', (SELECT id FROM rahavaraus WHERE nimi = 'Äkilliset hoitotyöt')),
    (2026, 8, 10000, 'akillinen-hoitotyo', (SELECT ID FROM tehtava WHERE yksiloiva_tunniste = '1ed5d0bb-13c7-4f52-91ee-5051bb0fd974'), null, (SELECT id FROM toimenpideinstanssi WHERE nimi = 'Iin MHU 2021-2026 Liikenneympäristön hoito TP'), (SELECT id FROM sopimus WHERE nimi = 'MHU Ii sopimus'), NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 11100, NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 'tavoitehintaiset-rahavaraukset', (SELECT id FROM rahavaraus WHERE nimi = 'Äkilliset hoitotyöt')),
    (2026, 9, 10000, 'akillinen-hoitotyo', (SELECT ID FROM tehtava WHERE yksiloiva_tunniste = '1ed5d0bb-13c7-4f52-91ee-5051bb0fd974'), null, (SELECT id FROM toimenpideinstanssi WHERE nimi = 'Iin MHU 2021-2026 Liikenneympäristön hoito TP'), (SELECT id FROM sopimus WHERE nimi = 'MHU Ii sopimus'), NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 11100, NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 'tavoitehintaiset-rahavaraukset', (SELECT id FROM rahavaraus WHERE nimi = 'Äkilliset hoitotyöt')),

    (2025, 10, 200, 'vahinkojen-korjaukset', (SELECT ID FROM tehtava WHERE yksiloiva_tunniste = '63a2585b-5597-43ea-945c-1b25b16a06e2'), null, (SELECT id FROM toimenpideinstanssi WHERE nimi = 'Iin MHU 2021-2026 Liikenneympäristön hoito TP'), (SELECT id FROM sopimus WHERE nimi = 'MHU Ii sopimus'), NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 220, NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 'tavoitehintaiset-rahavaraukset', (SELECT id FROM rahavaraus WHERE nimi = 'Vahinkojen korjaukset')),
    (2025, 11, 200, 'vahinkojen-korjaukset', (SELECT ID FROM tehtava WHERE yksiloiva_tunniste = '63a2585b-5597-43ea-945c-1b25b16a06e2'), null, (SELECT id FROM toimenpideinstanssi WHERE nimi = 'Iin MHU 2021-2026 Liikenneympäristön hoito TP'), (SELECT id FROM sopimus WHERE nimi = 'MHU Ii sopimus'), NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 220, NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 'tavoitehintaiset-rahavaraukset', (SELECT id FROM rahavaraus WHERE nimi = 'Vahinkojen korjaukset')),
    (2025, 12, 200, 'vahinkojen-korjaukset', (SELECT ID FROM tehtava WHERE yksiloiva_tunniste = '63a2585b-5597-43ea-945c-1b25b16a06e2'), null, (SELECT id FROM toimenpideinstanssi WHERE nimi = 'Iin MHU 2021-2026 Liikenneympäristön hoito TP'), (SELECT id FROM sopimus WHERE nimi = 'MHU Ii sopimus'), NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 220, NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 'tavoitehintaiset-rahavaraukset', (SELECT id FROM rahavaraus WHERE nimi = 'Vahinkojen korjaukset')),
    (2026, 1, 200, 'vahinkojen-korjaukset', (SELECT ID FROM tehtava WHERE yksiloiva_tunniste = '63a2585b-5597-43ea-945c-1b25b16a06e2'), null, (SELECT id FROM toimenpideinstanssi WHERE nimi = 'Iin MHU 2021-2026 Liikenneympäristön hoito TP'), (SELECT id FROM sopimus WHERE nimi = 'MHU Ii sopimus'), NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 220, NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 'tavoitehintaiset-rahavaraukset', (SELECT id FROM rahavaraus WHERE nimi = 'Vahinkojen korjaukset')),
    (2026, 2, 200, 'vahinkojen-korjaukset', (SELECT ID FROM tehtava WHERE yksiloiva_tunniste = '63a2585b-5597-43ea-945c-1b25b16a06e2'), null, (SELECT id FROM toimenpideinstanssi WHERE nimi = 'Iin MHU 2021-2026 Liikenneympäristön hoito TP'), (SELECT id FROM sopimus WHERE nimi = 'MHU Ii sopimus'), NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 220, NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 'tavoitehintaiset-rahavaraukset', (SELECT id FROM rahavaraus WHERE nimi = 'Vahinkojen korjaukset')),
    (2026, 3, 200, 'vahinkojen-korjaukset', (SELECT ID FROM tehtava WHERE yksiloiva_tunniste = '63a2585b-5597-43ea-945c-1b25b16a06e2'), null, (SELECT id FROM toimenpideinstanssi WHERE nimi = 'Iin MHU 2021-2026 Liikenneympäristön hoito TP'), (SELECT id FROM sopimus WHERE nimi = 'MHU Ii sopimus'), NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 220, NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 'tavoitehintaiset-rahavaraukset', (SELECT id FROM rahavaraus WHERE nimi = 'Vahinkojen korjaukset')),
    (2026, 4, 200, 'vahinkojen-korjaukset', (SELECT ID FROM tehtava WHERE yksiloiva_tunniste = '63a2585b-5597-43ea-945c-1b25b16a06e2'), null, (SELECT id FROM toimenpideinstanssi WHERE nimi = 'Iin MHU 2021-2026 Liikenneympäristön hoito TP'), (SELECT id FROM sopimus WHERE nimi = 'MHU Ii sopimus'), NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 220, NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 'tavoitehintaiset-rahavaraukset', (SELECT id FROM rahavaraus WHERE nimi = 'Vahinkojen korjaukset')),
    (2026, 5, 200, 'vahinkojen-korjaukset', (SELECT ID FROM tehtava WHERE yksiloiva_tunniste = '63a2585b-5597-43ea-945c-1b25b16a06e2'), null, (SELECT id FROM toimenpideinstanssi WHERE nimi = 'Iin MHU 2021-2026 Liikenneympäristön hoito TP'), (SELECT id FROM sopimus WHERE nimi = 'MHU Ii sopimus'), NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 220, NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 'tavoitehintaiset-rahavaraukset', (SELECT id FROM rahavaraus WHERE nimi = 'Vahinkojen korjaukset')),
    (2026, 6, 200, 'vahinkojen-korjaukset', (SELECT ID FROM tehtava WHERE yksiloiva_tunniste = '63a2585b-5597-43ea-945c-1b25b16a06e2'), null, (SELECT id FROM toimenpideinstanssi WHERE nimi = 'Iin MHU 2021-2026 Liikenneympäristön hoito TP'), (SELECT id FROM sopimus WHERE nimi = 'MHU Ii sopimus'), NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 220, NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 'tavoitehintaiset-rahavaraukset', (SELECT id FROM rahavaraus WHERE nimi = 'Vahinkojen korjaukset')),
    (2026, 7, 200, 'vahinkojen-korjaukset', (SELECT ID FROM tehtava WHERE yksiloiva_tunniste = '63a2585b-5597-43ea-945c-1b25b16a06e2'), null, (SELECT id FROM toimenpideinstanssi WHERE nimi = 'Iin MHU 2021-2026 Liikenneympäristön hoito TP'), (SELECT id FROM sopimus WHERE nimi = 'MHU Ii sopimus'), NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 220, NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 'tavoitehintaiset-rahavaraukset', (SELECT id FROM rahavaraus WHERE nimi = 'Vahinkojen korjaukset')),
    (2026, 8, 200, 'vahinkojen-korjaukset', (SELECT ID FROM tehtava WHERE yksiloiva_tunniste = '63a2585b-5597-43ea-945c-1b25b16a06e2'), null, (SELECT id FROM toimenpideinstanssi WHERE nimi = 'Iin MHU 2021-2026 Liikenneympäristön hoito TP'), (SELECT id FROM sopimus WHERE nimi = 'MHU Ii sopimus'), NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 220, NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 'tavoitehintaiset-rahavaraukset', (SELECT id FROM rahavaraus WHERE nimi = 'Vahinkojen korjaukset')),
    (2026, 9, 200, 'vahinkojen-korjaukset', (SELECT ID FROM tehtava WHERE yksiloiva_tunniste = '63a2585b-5597-43ea-945c-1b25b16a06e2'), null, (SELECT id FROM toimenpideinstanssi WHERE nimi = 'Iin MHU 2021-2026 Liikenneympäristön hoito TP'), (SELECT id FROM sopimus WHERE nimi = 'MHU Ii sopimus'), NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 220, NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 'tavoitehintaiset-rahavaraukset', (SELECT id FROM rahavaraus WHERE nimi = 'Vahinkojen korjaukset')),
    
    (2025, 10, 3000, 'muut-rahavaraukset', (SELECT ID FROM tehtava WHERE yksiloiva_tunniste = '794c7fbf-86b0-4f3e-9371-fb350257eb30'), null, (SELECT id FROM toimenpideinstanssi WHERE nimi = 'Iin MHU 2021-2026 Liikenneympäristön hoito TP'), (SELECT id FROM sopimus WHERE nimi = 'MHU Ii sopimus'), NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 3300, NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 'tavoitehintaiset-rahavaraukset', (SELECT id FROM rahavaraus WHERE nimi = 'Tilaajan rahavaraus kannustinjärjestelmään')),
    (2025, 11, 3000, 'muut-rahavaraukset', (SELECT ID FROM tehtava WHERE yksiloiva_tunniste = '794c7fbf-86b0-4f3e-9371-fb350257eb30'), null, (SELECT id FROM toimenpideinstanssi WHERE nimi = 'Iin MHU 2021-2026 Liikenneympäristön hoito TP'), (SELECT id FROM sopimus WHERE nimi = 'MHU Ii sopimus'), NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 3300, NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 'tavoitehintaiset-rahavaraukset', (SELECT id FROM rahavaraus WHERE nimi = 'Tilaajan rahavaraus kannustinjärjestelmään')),
    (2025, 12, 3000, 'muut-rahavaraukset', (SELECT ID FROM tehtava WHERE yksiloiva_tunniste = '794c7fbf-86b0-4f3e-9371-fb350257eb30'), null, (SELECT id FROM toimenpideinstanssi WHERE nimi = 'Iin MHU 2021-2026 Liikenneympäristön hoito TP'), (SELECT id FROM sopimus WHERE nimi = 'MHU Ii sopimus'), NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 3300, NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 'tavoitehintaiset-rahavaraukset', (SELECT id FROM rahavaraus WHERE nimi = 'Tilaajan rahavaraus kannustinjärjestelmään')),
    (2026, 1, 3000, 'muut-rahavaraukset', (SELECT ID FROM tehtava WHERE yksiloiva_tunniste = '794c7fbf-86b0-4f3e-9371-fb350257eb30'), null, (SELECT id FROM toimenpideinstanssi WHERE nimi = 'Iin MHU 2021-2026 Liikenneympäristön hoito TP'), (SELECT id FROM sopimus WHERE nimi = 'MHU Ii sopimus'), NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 3300, NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 'tavoitehintaiset-rahavaraukset', (SELECT id FROM rahavaraus WHERE nimi = 'Tilaajan rahavaraus kannustinjärjestelmään')),
    (2026, 2, 3000, 'muut-rahavaraukset', (SELECT ID FROM tehtava WHERE yksiloiva_tunniste = '794c7fbf-86b0-4f3e-9371-fb350257eb30'), null, (SELECT id FROM toimenpideinstanssi WHERE nimi = 'Iin MHU 2021-2026 Liikenneympäristön hoito TP'), (SELECT id FROM sopimus WHERE nimi = 'MHU Ii sopimus'), NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 3300, NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 'tavoitehintaiset-rahavaraukset', (SELECT id FROM rahavaraus WHERE nimi = 'Tilaajan rahavaraus kannustinjärjestelmään')),
    (2026, 3, 3000, 'muut-rahavaraukset', (SELECT ID FROM tehtava WHERE yksiloiva_tunniste = '794c7fbf-86b0-4f3e-9371-fb350257eb30'), null, (SELECT id FROM toimenpideinstanssi WHERE nimi = 'Iin MHU 2021-2026 Liikenneympäristön hoito TP'), (SELECT id FROM sopimus WHERE nimi = 'MHU Ii sopimus'), NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 3300, NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 'tavoitehintaiset-rahavaraukset', (SELECT id FROM rahavaraus WHERE nimi = 'Tilaajan rahavaraus kannustinjärjestelmään')),
    (2026, 4, 3000, 'muut-rahavaraukset', (SELECT ID FROM tehtava WHERE yksiloiva_tunniste = '794c7fbf-86b0-4f3e-9371-fb350257eb30'), null, (SELECT id FROM toimenpideinstanssi WHERE nimi = 'Iin MHU 2021-2026 Liikenneympäristön hoito TP'), (SELECT id FROM sopimus WHERE nimi = 'MHU Ii sopimus'), NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 3300, NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 'tavoitehintaiset-rahavaraukset', (SELECT id FROM rahavaraus WHERE nimi = 'Tilaajan rahavaraus kannustinjärjestelmään')),
    (2026, 5, 3000, 'muut-rahavaraukset', (SELECT ID FROM tehtava WHERE yksiloiva_tunniste = '794c7fbf-86b0-4f3e-9371-fb350257eb30'), null, (SELECT id FROM toimenpideinstanssi WHERE nimi = 'Iin MHU 2021-2026 Liikenneympäristön hoito TP'), (SELECT id FROM sopimus WHERE nimi = 'MHU Ii sopimus'), NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 3300, NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 'tavoitehintaiset-rahavaraukset', (SELECT id FROM rahavaraus WHERE nimi = 'Tilaajan rahavaraus kannustinjärjestelmään')),
    (2026, 6, 3000, 'muut-rahavaraukset', (SELECT ID FROM tehtava WHERE yksiloiva_tunniste = '794c7fbf-86b0-4f3e-9371-fb350257eb30'), null, (SELECT id FROM toimenpideinstanssi WHERE nimi = 'Iin MHU 2021-2026 Liikenneympäristön hoito TP'), (SELECT id FROM sopimus WHERE nimi = 'MHU Ii sopimus'), NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 3300, NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 'tavoitehintaiset-rahavaraukset', (SELECT id FROM rahavaraus WHERE nimi = 'Tilaajan rahavaraus kannustinjärjestelmään')),
    (2026, 7, 3000, 'muut-rahavaraukset', (SELECT ID FROM tehtava WHERE yksiloiva_tunniste = '794c7fbf-86b0-4f3e-9371-fb350257eb30'), null, (SELECT id FROM toimenpideinstanssi WHERE nimi = 'Iin MHU 2021-2026 Liikenneympäristön hoito TP'), (SELECT id FROM sopimus WHERE nimi = 'MHU Ii sopimus'), NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 3300, NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 'tavoitehintaiset-rahavaraukset', (SELECT id FROM rahavaraus WHERE nimi = 'Tilaajan rahavaraus kannustinjärjestelmään')),
    (2026, 8, 3000, 'muut-rahavaraukset', (SELECT ID FROM tehtava WHERE yksiloiva_tunniste = '794c7fbf-86b0-4f3e-9371-fb350257eb30'), null, (SELECT id FROM toimenpideinstanssi WHERE nimi = 'Iin MHU 2021-2026 Liikenneympäristön hoito TP'), (SELECT id FROM sopimus WHERE nimi = 'MHU Ii sopimus'), NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 3300, NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 'tavoitehintaiset-rahavaraukset', (SELECT id FROM rahavaraus WHERE nimi = 'Tilaajan rahavaraus kannustinjärjestelmään')),
    (2026, 9, 3000, 'muut-rahavaraukset', (SELECT ID FROM tehtava WHERE yksiloiva_tunniste = '794c7fbf-86b0-4f3e-9371-fb350257eb30'), null, (SELECT id FROM toimenpideinstanssi WHERE nimi = 'Iin MHU 2021-2026 Liikenneympäristön hoito TP'), (SELECT id FROM sopimus WHERE nimi = 'MHU Ii sopimus'), NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 3300, NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), 'tavoitehintaiset-rahavaraukset', (SELECT id FROM rahavaraus WHERE nimi = 'Tilaajan rahavaraus kannustinjärjestelmään'));

-- rahavarauksia vasten toteutuneita kuluja
INSERT INTO kulu (kokonaissumma, erapaiva, urakka, luotu, luoja, muokattu, muokkaaja, poistettu, laskun_numero, lisatieto, koontilaskun_kuukausi)
VALUES  (200619.35, '2025-11-03', (SELECT id FROM urakka WHERE nimi = 'Iin MHU 2021-2026') , NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), null, null, false, '802', 'testidata Iin kulu 1', 'maaliskuu/3-hoitovuosi');
INSERT INTO kulu_kohdistus (rivi, kulu, summa, toimenpideinstanssi, tehtavaryhma, maksueratyyppi, luotu, luoja, rahavaraus_id, tyyppi, tavoitehintainen)
VALUES  (0, (SELECT id FROM kulu WHERE lisatieto = 'testidata Iin kulu 1'), 100000, (SELECT id FROM toimenpideinstanssi WHERE nimi = 'Iin MHU 2021-2026 Liikenneympäristön hoito TP'),
         (SELECT id FROM tehtavaryhma WHERE nimi = 'T1 - Äkilliset hoitotyöt, Liikenneympäristön hoito'), 'akillinen-hoitotyo', NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), (SELECT id FROM rahavaraus WHERE nimi = 'Äkilliset hoitotyöt'), 'rahavaraus', true),
        (1, (SELECT id FROM kulu WHERE lisatieto = 'testidata Iin kulu 1'), 1000, (SELECT id FROM toimenpideinstanssi WHERE nimi = 'Iin MHU 2021-2026 Liikenneympäristön hoito TP'),
         (SELECT id FROM tehtavaryhma WHERE nimi = 'T2 - Vahinkojen korjaukset, Liikenneympäristön hoito'), 'muu', NOW(), (SELECT id FROM kayttaja WHERE kayttajanimi = 'Integraatio'), (SELECT id FROM rahavaraus WHERE nimi = 'Vahinkojen korjaukset'), 'rahavaraus', true);
