INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, tehtava, urakka, sopimus) VALUES ('2005-10-01', '2005-12-31', 3, 'vrk', 525.50, (SELECT id FROM toimenpidekoodi WHERE taso=4 AND nimi='Opastustaulujen ja opastusviittojen uusiminen -porttaalissa olevan viitan/opastetaulun uusiminen'), (SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2005-2012'), (select id from sopimus where urakka = (SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2005-2012') AND paasopimus IS null));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, tehtava, urakka, sopimus) VALUES ('2006-01-01', '2006-09-30', 9, 'vrk', 525.50, (SELECT id FROM toimenpidekoodi WHERE taso=4 AND nimi='Opastustaulujen ja opastusviittojen uusiminen -porttaalissa olevan viitan/opastetaulun uusiminen'), (SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2005-2012'), (select id from sopimus where urakka = (SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2005-2012') AND paasopimus IS null));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, tehtava, urakka, sopimus) VALUES ('2005-10-01', '2005-12-31', 525.73, 'km', 525.50, (SELECT id FROM toimenpidekoodi WHERE taso=4 AND nimi='Pensaiden poisto'), (SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2005-2012'), (select id from sopimus where urakka = (SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2005-2012') AND paasopimus IS null));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, tehtava, urakka, sopimus) VALUES ('2006-01-01', '2006-09-30', 1525.321, 'km', 525.50, (SELECT id FROM toimenpidekoodi WHERE taso=4 AND nimi='Pensaiden poisto'), (SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2005-2012'), (select id from sopimus where urakka = (SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2005-2012') AND paasopimus IS null));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, tehtava, urakka, sopimus) VALUES ('2013-10-01', '2013-12-31', 525.73, 'km', 525.50, (SELECT id FROM toimenpidekoodi WHERE taso=4 AND nimi='Pensaiden poisto'), (SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2005-2012'), (select id from sopimus where urakka = (SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2005-2012') AND paasopimus IS null));

INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, tehtava, urakka, sopimus) VALUES ('2016-10-01', '2016-12-31', 3, 'vrk', 525.50, (SELECT id FROM toimenpidekoodi WHERE taso=4 AND nimi='Opastustaulujen ja opastusviittojen uusiminen -porttaalissa olevan viitan/opastetaulun uusiminen'), (SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2014-2019'), (select id from sopimus where urakka = (SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2014-2019') AND paasopimus IS null));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, tehtava, urakka, sopimus) VALUES ('2017-01-01', '2017-09-30', 9, 'vrk', 525.50, (SELECT id FROM toimenpidekoodi WHERE taso=4 AND nimi='Opastustaulujen ja opastusviittojen uusiminen -porttaalissa olevan viitan/opastetaulun uusiminen'), (SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2014-2019'), (select id from sopimus where urakka = (SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2014-2019') AND paasopimus IS null));

INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, tehtava, urakka, sopimus) VALUES ('2013-10-01', '2013-12-31', 3, 'vrk', 525.50, (SELECT id FROM toimenpidekoodi WHERE taso=4 AND nimi='Opastustaulujen ja opastusviittojen uusiminen -porttaalissa olevan viitan/opastetaulun uusiminen'), (SELECT id FROM urakka WHERE nimi='Pudasjärven alueurakka 2007-2012'), (select id from sopimus where urakka = (SELECT id FROM urakka WHERE nimi='Pudasjärven alueurakka 2007-2012') AND paasopimus IS null));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, tehtava, urakka, sopimus) VALUES ('2014-01-01', '2014-09-30', 9, 'vrk', 525.50, (SELECT id FROM toimenpidekoodi WHERE taso=4 AND nimi='Opastustaulujen ja opastusviittojen uusiminen -porttaalissa olevan viitan/opastetaulun uusiminen'), (SELECT id FROM urakka WHERE nimi='Pudasjärven alueurakka 2007-2012'), (select id from sopimus where urakka = (SELECT id FROM urakka WHERE nimi='Pudasjärven alueurakka 2007-2012') AND paasopimus IS null));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, tehtava, urakka, sopimus) VALUES ('2013-10-01', '2013-12-31', 866.0, 'km', 525.50, (SELECT id FROM toimenpidekoodi WHERE taso=4 AND nimi='Pensaiden poisto'), (SELECT id FROM urakka WHERE nimi='Pudasjärven alueurakka 2007-2012'), (select id from sopimus where urakka = (SELECT id FROM urakka WHERE nimi='Pudasjärven alueurakka 2007-2012') AND paasopimus IS null));

-- Tiemerkintöjen palvelusopimus KAS ELY 2013 - 2017
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2013-10-01', '2013-12-31', 20, 'm2', 1, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Pienmerkinnät massalla paksuus 7 mm: Pyörätien jatkeet ja suojatiet'), (SELECT id FROM urakka WHERE nimi = 'Tiemerkintöjen palvelusopimus KAS ELY 2013 - 2017'), (SELECT id FROM sopimus WHERE nimi = 'Tiemerkintöjen palvelusopimus KAS ELY 2013 - 2017'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2013-10-01', '2013-12-31', 40, 'kpl', 2, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Pienmerkinnät massalla paksuus 3 mm: Nopeusrajoitusmerkinnät'), (SELECT id FROM urakka WHERE nimi = 'Tiemerkintöjen palvelusopimus KAS ELY 2013 - 2017'), (SELECT id FROM sopimus WHERE nimi = 'Tiemerkintöjen palvelusopimus KAS ELY 2013 - 2017'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2013-10-01', '2013-12-31', 30, 'kpl', 5, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Pienmerkinnät massalla paksuus 3 mm: Väistämisviivan yksi kolmio hainhammas'), (SELECT id FROM urakka WHERE nimi = 'Tiemerkintöjen palvelusopimus KAS ELY 2013 - 2017'), (SELECT id FROM sopimus WHERE nimi = 'Tiemerkintöjen palvelusopimus KAS ELY 2013 - 2017'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2013-10-01', '2013-12-31', 60, 'm2', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Pienmerkinnät massalla paksuus 3 mm: Pysäytysviiva'), (SELECT id FROM urakka WHERE nimi = 'Tiemerkintöjen palvelusopimus KAS ELY 2013 - 2017'), (SELECT id FROM sopimus WHERE nimi = 'Tiemerkintöjen palvelusopimus KAS ELY 2013 - 2017'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2013-10-01', '2013-12-31', 40, 'm2', 4, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Pienmerkinnät massalla paksuus 3 mm: Sulkualueet'), (SELECT id FROM urakka WHERE nimi = 'Tiemerkintöjen palvelusopimus KAS ELY 2013 - 2017'), (SELECT id FROM sopimus WHERE nimi = 'Tiemerkintöjen palvelusopimus KAS ELY 2013 - 2017'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2013-10-01', '2013-12-31', 40, 'm2', 2, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Pienmerkinnät massalla paksuus 3 mm: Pyörätien jatkeet ja suojatiet'), (SELECT id FROM urakka WHERE nimi = 'Tiemerkintöjen palvelusopimus KAS ELY 2013 - 2017'), (SELECT id FROM sopimus WHERE nimi = 'Tiemerkintöjen palvelusopimus KAS ELY 2013 - 2017'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2013-10-01', '2013-12-31', 50, 'kpl', 2, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Pienmerkinnät massalla paksuus 3 mm: Nuoli, pitkä (1-, 2- ja 3-kärkiset sekä ajokaistan päättymisnuoli)'), (SELECT id FROM urakka WHERE nimi = 'Tiemerkintöjen palvelusopimus KAS ELY 2013 - 2017'), (SELECT id FROM sopimus WHERE nimi = 'Tiemerkintöjen palvelusopimus KAS ELY 2013 - 2017'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2013-10-01', '2013-12-31', 40, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Pienmerkinnät massalla paksuus 3 mm: Nuoli, lyhyt (1-, 2- ja 3-kärkiset sekä ajokaistan päättymisnuoli)'), (SELECT id FROM urakka WHERE nimi = 'Tiemerkintöjen palvelusopimus KAS ELY 2013 - 2017'), (SELECT id FROM sopimus WHERE nimi = 'Tiemerkintöjen palvelusopimus KAS ELY 2013 - 2017'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2013-10-01', '2013-12-31', 400, 'm2', 4, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Linjamerkinnät massalla paksuus 7 mm: Keskiviiva, ajokaistaviiva, ohjausviiva valkoinen'), (SELECT id FROM urakka WHERE nimi = 'Tiemerkintöjen palvelusopimus KAS ELY 2013 - 2017'), (SELECT id FROM sopimus WHERE nimi = 'Tiemerkintöjen palvelusopimus KAS ELY 2013 - 2017'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2013-10-01', '2013-12-31', 190, 'm2', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Linjamerkinnät massalla paksuus 7 mm: Reunaviiva ja reunaviivan jatke'), (SELECT id FROM urakka WHERE nimi = 'Tiemerkintöjen palvelusopimus KAS ELY 2013 - 2017'), (SELECT id FROM sopimus WHERE nimi = 'Tiemerkintöjen palvelusopimus KAS ELY 2013 - 2017'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2013-10-01', '2013-12-31', 40, 'm2', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Linjamerkinnät massalla, paksuus 3 mm: Sulkuviiva ja varoitusviiva keltainen'), (SELECT id FROM urakka WHERE nimi = 'Tiemerkintöjen palvelusopimus KAS ELY 2013 - 2017'), (SELECT id FROM sopimus WHERE nimi = 'Tiemerkintöjen palvelusopimus KAS ELY 2013 - 2017'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2013-10-01', '2013-12-31', 2000, 'm2', 4, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Linjamerkinnät massalla, paksuus 3 mm: Keskiviiva, ajokaistaviiva, ohjausviiva valkoinen'), (SELECT id FROM urakka WHERE nimi = 'Tiemerkintöjen palvelusopimus KAS ELY 2013 - 2017'), (SELECT id FROM sopimus WHERE nimi = 'Tiemerkintöjen palvelusopimus KAS ELY 2013 - 2017'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2013-10-01', '2013-12-31', 30, 'm2', 2, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Linjamerkinnät massalla, paksuus 3mm: Reunaviiva ja reunaviivan jatke'), (SELECT id FROM urakka WHERE nimi = 'Tiemerkintöjen palvelusopimus KAS ELY 2013 - 2017'), (SELECT id FROM sopimus WHERE nimi = 'Tiemerkintöjen palvelusopimus KAS ELY 2013 - 2017'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2013-10-01', '2013-12-31', 20, 'm2', 2, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Muut pienmerkinnät'), (SELECT id FROM urakka WHERE nimi = 'Tiemerkintöjen palvelusopimus KAS ELY 2013 - 2017'), (SELECT id FROM sopimus WHERE nimi = 'Tiemerkintöjen palvelusopimus KAS ELY 2013 - 2017'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2013-10-01', '2013-12-31', 30, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Nuolet ja nopeusrajoitusmerkinnät ja väistämisviivat'), (SELECT id FROM urakka WHERE nimi = 'Tiemerkintöjen palvelusopimus KAS ELY 2013 - 2017'), (SELECT id FROM sopimus WHERE nimi = 'Tiemerkintöjen palvelusopimus KAS ELY 2013 - 2017'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2013-10-01', '2013-12-31', 30, 'm2', 2, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Sulkualueet'), (SELECT id FROM urakka WHERE nimi = 'Tiemerkintöjen palvelusopimus KAS ELY 2013 - 2017'), (SELECT id FROM sopimus WHERE nimi = 'Tiemerkintöjen palvelusopimus KAS ELY 2013 - 2017'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2013-10-01', '2013-12-31', 200, 'm2', 1, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Linjamerkinnän upotusjyrsintä'), (SELECT id FROM urakka WHERE nimi = 'Tiemerkintöjen palvelusopimus KAS ELY 2013 - 2017'), (SELECT id FROM sopimus WHERE nimi = 'Tiemerkintöjen palvelusopimus KAS ELY 2013 - 2017'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2013-10-01', '2013-12-31', 60, 'jm', 4.5, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Täristävät merkinnät: sini-aallonmuotoinen jyrsintä, reunaviiva, 2 ajr tie: lev 30 cm, aallonpit 60 cm, syv 6 mm aallonharjalla, syv 13 mm aallon pohjalla'), (SELECT id FROM urakka WHERE nimi = 'Tiemerkintöjen palvelusopimus KAS ELY 2013 - 2017'), (SELECT id FROM sopimus WHERE nimi = 'Tiemerkintöjen palvelusopimus KAS ELY 2013 - 2017'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2013-10-01', '2013-12-31', 40, 'jm', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Täristävät merkinnät: sini-aallonmuotoinen jyrsintä, reunaviiva, 1 ajr tie: lev 30 cm, aallonpit 60 cm, syv 6 mm aallonharjalla, syv 13 mm aallon pohjalla'), (SELECT id FROM urakka WHERE nimi = 'Tiemerkintöjen palvelusopimus KAS ELY 2013 - 2017'), (SELECT id FROM sopimus WHERE nimi = 'Tiemerkintöjen palvelusopimus KAS ELY 2013 - 2017'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2013-10-01', '2013-12-31', 30, 'jm', 2, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Täristävät merkinnät: sylinterijyrsintä, reunaviiva, 2 ajr tie: lev 30 cm, pit 13-15 cm, merkintäväli 60 cm, syvyys 15 mm'), (SELECT id FROM urakka WHERE nimi = 'Tiemerkintöjen palvelusopimus KAS ELY 2013 - 2017'), (SELECT id FROM sopimus WHERE nimi = 'Tiemerkintöjen palvelusopimus KAS ELY 2013 - 2017'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2013-10-01', '2013-12-31', 30, 'jm', 2, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Täristävät merkinnät: sylinterijyrsintä, keskiviiva, 1 ajr tie: lev 30 cm, pit 13-15 cm, merkintäväli 60 cm, syvyys 15 mm'), (SELECT id FROM urakka WHERE nimi = 'Tiemerkintöjen palvelusopimus KAS ELY 2013 - 2017'), (SELECT id FROM sopimus WHERE nimi = 'Tiemerkintöjen palvelusopimus KAS ELY 2013 - 2017'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2013-10-01', '2013-12-31', 50, 'jm', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Täristävät merkinnät: sylinterijyrsintä, reunaviiva, 1 ajr tie: lev 30 cm, pit 13-15 cm, merkintäväli 60 cm, syvyys 15 mm'), (SELECT id FROM urakka WHERE nimi = 'Tiemerkintöjen palvelusopimus KAS ELY 2013 - 2017'), (SELECT id FROM sopimus WHERE nimi = 'Tiemerkintöjen palvelusopimus KAS ELY 2013 - 2017'));

-- Tievalaistuksen palvelusopimus 2015-2020: sopimuskausi 2015
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2015-01-01','2015-12-31', 286, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Lamppujen ryhmävaihto: SpNa 50 - 100 W'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2015-01-01','2015-12-31', 4455, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Lamppujen ryhmävaihto: SpNa 150 - 400 W'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2015-01-01','2015-12-31', 0, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Lamppujen ryhmävaihto: PpNa 35 - 180 W'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2015-01-01','2015-12-31', 0, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Lamppujen ryhmävaihto: Monimetalli 35 - 150 W'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2015-01-01','2015-12-31', 0, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Lamppujen ryhmävaihto: Monimetalli 250 - 400 W'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2015-01-01','2015-12-31', 0, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Lamppujen ryhmävaihto: Loistelamppu'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));

INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2015-01-01','2015-12-31', 0, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Lamppujen yksittäisvaihto: Hg 50 - 400 W'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2015-01-01','2015-12-31', 20, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Lamppujen yksittäisvaihto: SpNa 50 - 100 W'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2015-01-01','2015-12-31', 120, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Lamppujen yksittäisvaihto: SpNa 150 - 400 W'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2015-01-01','2015-12-31', 35, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Lamppujen yksittäisvaihto: Sytytin'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2015-01-01','2015-12-31', 0, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Lamppujen yksittäisvaihto: PpNa 35  - 180 W'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2015-01-01','2015-12-31', 5, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Lamppujen yksittäisvaihto: Monimetalli 35 - 400 W'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2015-01-01','2015-12-31', 2, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Lamppujen yksittäisvaihto: Loistelamppu'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2015-01-01','2015-12-31', 2, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Lamppujen yksittäisvaihto: LED-yksikkö VP 2221/2223 valaisimeen'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));

INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2015-01-01','2015-12-31', 7, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Valaistuslaitteiden vaihto: Jalustan vaihto SJ 4'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2015-01-01','2015-12-31', 7, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Valaistuslaitteiden vaihto: Teräskartiopylväs HE3 h=10m V=2,5m'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2015-01-01','2015-12-31', 20, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Valaistuslaitteiden vaihto: Myötäävä puupylväs h=10m'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2015-01-01','2015-12-31', 15, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Valaistuslaitteiden vaihto: Puupylväsvarsi V= 1.0 - 2,5m'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2015-01-01','2015-12-31', 5, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Valaistuslaitteiden vaihto: Valaisin SpNa 50 - 70 W, lamppuineen'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2015-01-01','2015-12-31', 50, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Valaistuslaitteiden vaihto: Valaisin SpNa 100 - 250 W, lamppuineen'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2015-01-01','2015-12-31', 20, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Valaistuslaitteiden vaihto: Valaisin SpNa 100 - 250 W, 2-tehokuristin ja tehonvaihtorele, lamppuineen'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2015-01-01','2015-12-31', 0, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Valaistuslaitteiden vaihto: Valaisin LED, h=6 m, K4'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2015-01-01','2015-12-31', 0, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Valaistuslaitteiden vaihto: Valaisin LED, h=10 m, AL4a'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2015-01-01','2015-12-31', 2, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Valaistuslaitteiden vaihto: Valaisin LED VP 2221/2223 M1 - M3'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2015-01-01','2015-12-31', 10, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Valaistuslaitteiden vaihto: Maajakokeskus'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2015-01-01','2015-12-31', 15, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Valaistuslaitteiden vaihto: Haruksen uusiminen'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));

INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2015-01-01','2015-12-31', 50, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Valaistuslaitteiden korjaus: Puupylvään oikaisu'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2015-01-01','2015-12-31', 80, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Valaistuslaitteiden korjaus: Metallipylvään oikaisu alle 13 m'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2015-01-01','2015-12-31', 5, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Valaistuslaitteiden korjaus: Metallipylvään oikaisu yli 13 m'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2015-01-01','2015-12-31', 100, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Valaistuslaitteiden korjaus: Valaisinvarsien suuntaus alle 13 m'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2015-01-01','2015-12-31', 5, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Valaistuslaitteiden korjaus: Valaisinvarsien suuntaus yli 13 m'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));

INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2015-01-01','2015-12-31', 1500, 'h', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Asentaja'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2015-01-01','2015-12-31', 150, 'h', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Tr- kaivuri'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2015-01-01','2015-12-31', 50, 'h', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Törmäysvaimennin'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2015-01-01','2015-12-31', 360, 'h', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Kuorma-auto nosturilla'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2015-01-01','2015-12-31', 360, 'h', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Nostolava alle 13 m'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2015-01-01','2015-12-31', 20, 'h', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Nostolava yli 13 m'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));

-- Tievalaistuksen palvelusopimus 2015-2020: sopimuskausi 2016
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2016-01-01','2016-12-31', 386, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Lamppujen ryhmävaihto: SpNa 50 - 100 W'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2016-01-01','2016-12-31', 6173, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Lamppujen ryhmävaihto: SpNa 150 - 400 W'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2016-01-01','2016-12-31', 0, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Lamppujen ryhmävaihto: PpNa 35 - 180 W'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2016-01-01','2016-12-31', 16, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Lamppujen ryhmävaihto: Monimetalli 35 - 150 W'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2016-01-01','2016-12-31', 0, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Lamppujen ryhmävaihto: Monimetalli 250 - 400 W'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2016-01-01','2016-12-31', 0, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Lamppujen ryhmävaihto: Loistelamppu'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));

INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2016-01-01','2016-12-31', 0, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Lamppujen yksittäisvaihto: Hg 50 - 400 W'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2016-01-01','2016-12-31', 25, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Lamppujen yksittäisvaihto: SpNa 50 - 100 W'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2016-01-01','2016-12-31', 140, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Lamppujen yksittäisvaihto: SpNa 150 - 400 W'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2016-01-01','2016-12-31', 45, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Lamppujen yksittäisvaihto: Sytytin'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2016-01-01','2016-12-31', 0, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Lamppujen yksittäisvaihto: PpNa 35  - 180 W'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2016-01-01','2016-12-31', 5, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Lamppujen yksittäisvaihto: Monimetalli 35 - 400 W'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2016-01-01','2016-12-31', 2, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Lamppujen yksittäisvaihto: Loistelamppu'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2016-01-01','2016-12-31', 2, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Lamppujen yksittäisvaihto: LED-yksikkö VP 2221/2223 valaisimeen'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));

INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2016-01-01','2016-12-31', 10, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Valaistuslaitteiden vaihto: Jalustan vaihto SJ 4'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2016-01-01','2016-12-31', 10, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Valaistuslaitteiden vaihto: Teräskartiopylväs HE3 h=10m V=2,5m'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2016-01-01','2016-12-31', 25, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Valaistuslaitteiden vaihto: Myötäävä puupylväs h=10m'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2016-01-01','2016-12-31', 20, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Valaistuslaitteiden vaihto: Puupylväsvarsi V= 1.0 - 2,5m'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2016-01-01','2016-12-31', 10, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Valaistuslaitteiden vaihto: Valaisin SpNa 50 - 70 W, lamppuineen'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2016-01-01','2016-12-31', 65, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Valaistuslaitteiden vaihto: Valaisin SpNa 100 - 250 W, lamppuineen'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2016-01-01','2016-12-31', 25, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Valaistuslaitteiden vaihto: Valaisin SpNa 100 - 250 W, 2-tehokuristin ja tehonvaihtorele, lamppuineen'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2016-01-01','2016-12-31', 0, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Valaistuslaitteiden vaihto: Valaisin LED, h=6 m, K4'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2016-01-01','2016-12-31', 56, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Valaistuslaitteiden vaihto: Valaisin LED, h=10 m, AL4a'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2016-01-01','2016-12-31', 2, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Valaistuslaitteiden vaihto: Valaisin LED VP 2221/2223 M1 - M3'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2016-01-01','2016-12-31', 10, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Valaistuslaitteiden vaihto: Maajakokeskus'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2016-01-01','2016-12-31', 20, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Valaistuslaitteiden vaihto: Haruksen uusiminen'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));

INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2016-01-01','2016-12-31', 60, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Valaistuslaitteiden korjaus: Puupylvään oikaisu'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2016-01-01','2016-12-31', 90, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Valaistuslaitteiden korjaus: Metallipylvään oikaisu alle 13 m'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2016-01-01','2016-12-31', 5, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Valaistuslaitteiden korjaus: Metallipylvään oikaisu yli 13 m'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2016-01-01','2016-12-31', 130, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Valaistuslaitteiden korjaus: Valaisinvarsien suuntaus alle 13 m'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2016-01-01','2016-12-31', 5, 'kpl', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Valaistuslaitteiden korjaus: Valaisinvarsien suuntaus yli 13 m'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));

INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2016-01-01','2016-12-31', 1800, 'h', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Asentaja'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2016-01-01','2016-12-31', 150, 'h', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Tr- kaivuri'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2016-01-01','2016-12-31', 50, 'h', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Törmäysvaimennin'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2016-01-01','2016-12-31', 450, 'h', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Kuorma-auto nosturilla'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2016-01-01','2016-12-31', 450, 'h', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Nostolava alle 13 m'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2016-01-01','2016-12-31', 20, 'h', 3, null, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Nostolava yli 13 m'), (SELECT id FROM urakka WHERE nimi = 'Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM sopimus WHERE nimi = 'Oulun valaistuksen palvelusopimuksen pääsopimus 2015-2020'));

-- talvihoidon laaja toimenpide Oulun ja Pudasjärven urakoille
-- talvihoidon  laaja toimenpide 23104
-- soratien hoidon laaja toimenpide 23124
-- hoitokausi 2005-2006
INSERT INTO toimenpideinstanssi (urakka, toimenpide, nimi, alkupvm, loppupvm, tuotepolku, sampoid, talousosasto_id, talousosastopolku) VALUES ((SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2005-2012'), (SELECT id FROM toimenpidekoodi WHERE koodi='23104'), 'Oulu Talvihoito TP', (SELECT alkupvm FROM urakka WHERE nimi='Oulun alueurakka 2005-2012'), (SELECT loppupvm FROM urakka WHERE nimi='Oulun alueurakka 2005-2012'), 'tuotepolku', 'sampoid', 'talousosastoid', 'talousosastopolku');
INSERT INTO toimenpideinstanssi (urakka, toimenpide, nimi, alkupvm, loppupvm, tuotepolku, sampoid, talousosasto_id, talousosastopolku) VALUES ((SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2005-2012'), (SELECT id FROM toimenpidekoodi WHERE koodi='23116'), 'Oulu Liikenneympäristön hoito TP', (SELECT alkupvm FROM urakka WHERE nimi='Oulun alueurakka 2005-2012'), (SELECT loppupvm FROM urakka WHERE nimi='Oulun alueurakka 2005-2012'), 'tuotepolku', 'sampoid', 'talousosastoid', 'talousosastopolku');
INSERT INTO toimenpideinstanssi (urakka, toimenpide, nimi, alkupvm, loppupvm, tuotepolku, sampoid, talousosasto_id, talousosastopolku) VALUES ((SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2005-2012'), (SELECT id FROM toimenpidekoodi WHERE koodi='23124'), 'Oulu Sorateiden hoito TP', (SELECT alkupvm FROM urakka WHERE nimi='Oulun alueurakka 2005-2012'), (SELECT loppupvm FROM urakka WHERE nimi='Oulun alueurakka 2005-2012'), 'tuotepolku', 'sampoid', 'talousosastoid', 'talousosastopolku');

INSERT INTO toimenpideinstanssi (urakka, toimenpide, nimi, alkupvm, loppupvm, tuotepolku, sampoid, talousosasto_id, talousosastopolku) VALUES ((SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2014-2019'), (SELECT id FROM toimenpidekoodi WHERE koodi='23104'), 'Oulu Talvihoito TP 2014-2019', (SELECT alkupvm FROM urakka WHERE nimi='Oulun alueurakka 2014-2019'), (SELECT loppupvm FROM urakka WHERE nimi='Oulun alueurakka 2014-2019'), 'tuotepolku', 'sampoid', 'talousosastoid', 'talousosastopolku');
INSERT INTO toimenpideinstanssi (urakka, toimenpide, nimi, alkupvm, loppupvm, tuotepolku, sampoid, talousosasto_id, talousosastopolku) VALUES ((SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2014-2019'), (SELECT id FROM toimenpidekoodi WHERE koodi='23116'), 'Oulu Liikenneympäristön hoito TP 2014-2019', (SELECT alkupvm FROM urakka WHERE nimi='Oulun alueurakka 2014-2019'), (SELECT loppupvm FROM urakka WHERE nimi='Oulun alueurakka 2014-2019'), 'tuotepolku', 'sampoid', 'talousosastoid', 'talousosastopolku');
INSERT INTO toimenpideinstanssi (urakka, toimenpide, nimi, alkupvm, loppupvm, tuotepolku, sampoid, talousosasto_id, talousosastopolku) VALUES ((SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2014-2019'), (SELECT id FROM toimenpidekoodi WHERE koodi='23124'), 'Oulu Sorateiden hoito TP 2014-2019', (SELECT alkupvm FROM urakka WHERE nimi='Oulun alueurakka 2014-2019'), (SELECT loppupvm FROM urakka WHERE nimi='Oulun alueurakka 2014-2019'), 'tuotepolku', 'sampoid', 'talousosastoid', 'talousosastopolku');

INSERT INTO toimenpideinstanssi (urakka, toimenpide, nimi, alkupvm, loppupvm, tuotepolku, sampoid, talousosasto_id, talousosastopolku) VALUES ((SELECT id FROM urakka WHERE nimi='Pudasjärven alueurakka 2007-2012'), (SELECT id FROM toimenpidekoodi WHERE koodi='23104'), 'Pudasjärvi Talvihoito TP', (SELECT alkupvm FROM urakka WHERE nimi='Pudasjärven alueurakka 2007-2012'), (SELECT loppupvm FROM urakka WHERE nimi='Pudasjärven alueurakka 2007-2012'), 'tuotepolku', 'sampoid', 'talousosastoid', 'talousosastopolku');
INSERT INTO toimenpideinstanssi (urakka, toimenpide, nimi, alkupvm, loppupvm, tuotepolku, sampoid, talousosasto_id, talousosastopolku) VALUES ((SELECT id FROM urakka WHERE nimi='Pudasjärven alueurakka 2007-2012'), (SELECT id FROM toimenpidekoodi WHERE koodi='23124'), 'Pudasjärvi Sorateiden hoito TP', (SELECT alkupvm FROM urakka WHERE nimi='Pudasjärven alueurakka 2007-2012'), (SELECT loppupvm FROM urakka WHERE nimi='Pudasjärven alueurakka 2007-2012'), 'tuotepolku', 'sampoid', 'talousosastoid', 'talousosastopolku');
INSERT INTO toimenpideinstanssi (urakka, toimenpide, nimi, alkupvm, loppupvm, tuotepolku, sampoid, talousosasto_id, talousosastopolku) VALUES ((SELECT id FROM urakka WHERE nimi='Pudasjärven alueurakka 2007-2012'), (SELECT id FROM toimenpidekoodi WHERE koodi='23116'), 'Pudasjärvi Liikenneympäristön hoito TP', (SELECT alkupvm FROM urakka WHERE nimi='Pudasjärven alueurakka 2007-2012'), (SELECT loppupvm FROM urakka WHERE nimi='Pudasjärven alueurakka 2007-2012'), 'tuotepolku', 'sampoid', 'talousosastoid', 'talousosastopolku');

INSERT INTO toimenpideinstanssi (urakka, toimenpide, nimi, alkupvm, loppupvm, tuotepolku, sampoid, talousosasto_id, talousosastopolku) VALUES ((SELECT id FROM urakka WHERE nimi='Porin alueurakka 2007-2012'), (SELECT id FROM toimenpidekoodi WHERE koodi='23104'), 'Pori Talvihoito TP', (SELECT alkupvm FROM urakka WHERE nimi='Porin alueurakka 2007-2012'), (SELECT loppupvm FROM urakka WHERE nimi='Porin alueurakka 2007-2012'), 'tuotepolku', 'sampoid', 'talousosastoid', 'talousosastopolku');
INSERT INTO toimenpideinstanssi (urakka, toimenpide, nimi, alkupvm, loppupvm, tuotepolku, sampoid, talousosasto_id, talousosastopolku) VALUES ((SELECT id FROM urakka WHERE nimi='Porin alueurakka 2007-2012'), (SELECT id FROM toimenpidekoodi WHERE koodi='23124'), 'Pori Sorateiden hoito TP', (SELECT alkupvm FROM urakka WHERE nimi='Porin alueurakka 2007-2012'), (SELECT loppupvm FROM urakka WHERE nimi='Porin alueurakka 2007-2012'), 'tuotepolku', 'sampoid', 'talousosastoid', 'talousosastopolku');
INSERT INTO toimenpideinstanssi (urakka, toimenpide, nimi, alkupvm, loppupvm, tuotepolku, sampoid, talousosasto_id, talousosastopolku) VALUES ((SELECT id FROM urakka WHERE nimi='Porin alueurakka 2007-2012'), (SELECT id FROM toimenpidekoodi WHERE koodi='23116'), 'Pori Liikenneympäristön hoito TP', (SELECT alkupvm FROM urakka WHERE nimi='Porin alueurakka 2007-2012'), (SELECT loppupvm FROM urakka WHERE nimi='Porin alueurakka 2007-2012'), 'tuotepolku', 'sampoid', 'talousosastoid', 'talousosastopolku');

INSERT INTO toimenpideinstanssi (urakka,toimenpide,nimi,alkupvm,loppupvm, tuotepolku, sampoid, talousosasto_id, talousosastopolku) VALUES ((SELECT id FROM urakka WHERE nimi='Oulun tiemerkinnän palvelusopimus 2013-2018'), (SELECT id FROM toimenpidekoodi WHERE taso=3 AND koodi='20123'), 'Tiemerkinnän TP', '2013-10-01','2018-12-31', 'tuotepolku', 'sampoid', 'talousosastoid', 'talousosastopolku');
INSERT INTO toimenpideinstanssi (urakka,toimenpide,nimi,alkupvm,loppupvm, tuotepolku, sampoid, talousosasto_id, talousosastopolku) VALUES ((SELECT id FROM urakka WHERE nimi='Pirkanmaan tiemerkinnän palvelusopimus 2013-2018'), (SELECT id FROM toimenpidekoodi WHERE taso=3 AND koodi='20123'), 'Pirkanmaan Tiemerkinnän TP', '2013-01-01','2018-12-31', 'tuotepolku', 'sampoid', 'talousosastoid', 'talousosastopolku');
INSERT INTO toimenpideinstanssi (urakka,toimenpide,nimi,alkupvm,loppupvm, tuotepolku, sampoid, talousosasto_id, talousosastopolku) VALUES ((SELECT id FROM urakka WHERE nimi='Muhoksen päällystysurakka'), (SELECT id FROM toimenpidekoodi WHERE taso=3 AND koodi='20101'), 'Muhos Ajoradan päällyste TP', '2007-01-01','2012-12-31', 'tuotepolku', 'sampoid', 'talousosastoid', 'talousosastopolku');
INSERT INTO toimenpideinstanssi (urakka,toimenpide,nimi,alkupvm,loppupvm, tuotepolku, sampoid, talousosasto_id, talousosastopolku) VALUES ((SELECT id FROM urakka WHERE nimi='Porintien päällystysurakka'), (SELECT id FROM toimenpidekoodi WHERE taso=3 AND koodi='20101'), 'Porintien Ajoradan päällyste TP', '2007-01-01','2012-12-31', 'tuotepolku', 'sampoid', 'talousosastoid', 'talousosastopolku');
INSERT INTO toimenpideinstanssi (urakka,toimenpide,nimi,alkupvm,loppupvm, tuotepolku, sampoid, talousosasto_id, talousosastopolku) VALUES ((SELECT id FROM urakka WHERE nimi='Oulun valaistuksen palvelusopimus 2013-2018'), (SELECT id FROM toimenpidekoodi WHERE taso=3 AND koodi='20172'), 'Oulu Valaistuksen korjaus TP', '2013-01-01','2018-12-31', 'tuotepolku', 'sampoid', 'talousosastoid', 'talousosastopolku');
INSERT INTO toimenpideinstanssi (urakka,toimenpide,nimi,alkupvm,loppupvm, tuotepolku, sampoid, talousosasto_id, talousosastopolku) VALUES ((SELECT id FROM urakka WHERE nimi='Kempeleen valaistusurakka'), (SELECT id FROM toimenpidekoodi WHERE taso=3 AND koodi='20172'), 'Kempele Valaistuksen korjaus TP', '2007-10-01','2012-09-30', 'tuotepolku', 'sampoid', 'talousosastoid', 'talousosastopolku');
INSERT INTO toimenpideinstanssi (urakka,toimenpide,nimi,alkupvm,loppupvm, tuotepolku, sampoid, talousosasto_id, talousosastopolku) VALUES ((SELECT id FROM urakka WHERE nimi='Tiemerkintöjen palvelusopimus KAS ELY 2013 - 2017'), (SELECT id FROM toimenpidekoodi WHERE taso=3 AND koodi='20123'), 'Valaistuksen korjaus TP', '2013-10-01','2015-09-30', 'tuotepolku', 'sampoid', 'talousosastoid', 'talousosastopolku');
INSERT INTO toimenpideinstanssi (urakka,toimenpide,nimi,alkupvm,loppupvm, tuotepolku, sampoid, talousosasto_id, talousosastopolku) VALUES ((SELECT id FROM urakka WHERE nimi='Tievalaistuksen palvelusopimus 2015-2020'), (SELECT id FROM toimenpidekoodi WHERE taso=3 AND koodi='20172'), 'Oulu Valaistuksen korjaus TP', '2015-01-01','2020-12-31', 'tuotepolku', 'sampoid', 'talousosastoid', 'talousosastopolku');
-- Luodaan Kajaanin, Vantaan ja Espoon urakalle tärkeimmät toimenpideinstanssit
INSERT INTO toimenpideinstanssi (urakka, toimenpide, nimi, alkupvm, loppupvm, tuotepolku, sampoid, talousosasto_id, talousosastopolku)
VALUES
  ((SELECT id FROM urakka WHERE nimi='Kajaanin alueurakka 2014-2019'), (SELECT id FROM toimenpidekoodi WHERE koodi='23104'), 'Kajaani Talvihoito TP 2014-2019', (SELECT alkupvm FROM urakka WHERE nimi='Kajaanin alueurakka 2014-2019'), (SELECT loppupvm FROM urakka WHERE nimi='Kajaanin alueurakka 2014-2019'), 'tuotepolku', 'sampoid', 'talousosastoid', 'talousosastopolku'),
  ((SELECT id FROM urakka WHERE nimi='Kajaanin alueurakka 2014-2019'), (SELECT id FROM toimenpidekoodi WHERE koodi='23116'), 'Kajaani Liikenneympäristön hoito TP 2014-2019', (SELECT alkupvm FROM urakka WHERE nimi='Kajaanin alueurakka 2014-2019'), (SELECT loppupvm FROM urakka WHERE nimi='Kajaanin alueurakka 2014-2019'), 'tuotepolku', 'sampoid', 'talousosastoid', 'talousosastopolku'),
  ((SELECT id FROM urakka WHERE nimi='Kajaanin alueurakka 2014-2019'), (SELECT id FROM toimenpidekoodi WHERE koodi='23124'), 'Kajaani Sorateiden hoito TP 2014-2019', (SELECT alkupvm FROM urakka WHERE nimi='Kajaanin alueurakka 2014-2019'), (SELECT loppupvm FROM urakka WHERE nimi='Kajaanin alueurakka 2014-2019'), 'tuotepolku', 'sampoid', 'talousosastoid', 'talousosastopolku'),
  ((SELECT id FROM urakka WHERE nimi='Vantaan alueurakka 2009-2019'), (SELECT id FROM toimenpidekoodi WHERE koodi='23104'), 'Vantaa Talvihoito TP 2014-2019', (SELECT alkupvm FROM urakka WHERE nimi='Vantaan alueurakka 2009-2019'), (SELECT loppupvm FROM urakka WHERE nimi='Vantaan alueurakka 2009-2019'), 'tuotepolku', 'sampoid', 'talousosastoid', 'talousosastopolku'),
  ((SELECT id FROM urakka WHERE nimi='Vantaan alueurakka 2009-2019'), (SELECT id FROM toimenpidekoodi WHERE koodi='23116'), 'Vantaa Liikenneympäristön hoito TP 2014-2019', (SELECT alkupvm FROM urakka WHERE nimi='Vantaan alueurakka 2009-2019'), (SELECT loppupvm FROM urakka WHERE nimi='Vantaan alueurakka 2009-2019'), 'tuotepolku', 'sampoid', 'talousosastoid', 'talousosastopolku'),
  ((SELECT id FROM urakka WHERE nimi='Vantaan alueurakka 2009-2019'), (SELECT id FROM toimenpidekoodi WHERE koodi='23124'), 'Vantaa Sorateiden hoito TP 2014-2019', (SELECT alkupvm FROM urakka WHERE nimi='Vantaan alueurakka 2009-2019'), (SELECT loppupvm FROM urakka WHERE nimi='Vantaan alueurakka 2009-2019'), 'tuotepolku', 'sampoid', 'talousosastoid', 'talousosastopolku'),
  ((SELECT id FROM urakka WHERE nimi='Espoon alueurakka 2014-2019'), (SELECT id FROM toimenpidekoodi WHERE koodi='23104'), 'Espoo Talvihoito TP 2014-2019', (SELECT alkupvm FROM urakka WHERE nimi='Espoon alueurakka 2014-2019'), (SELECT loppupvm FROM urakka WHERE nimi='Espoon alueurakka 2014-2019'), 'tuotepolku', 'sampoid', 'talousosastoid', 'talousosastopolku'),
  ((SELECT id FROM urakka WHERE nimi='Espoon alueurakka 2014-2019'), (SELECT id FROM toimenpidekoodi WHERE koodi='23116'), 'Espoo Liikenneympäristön hoito TP 2014-2019', (SELECT alkupvm FROM urakka WHERE nimi='Espoon alueurakka 2014-2019'), (SELECT loppupvm FROM urakka WHERE nimi='Espoon alueurakka 2014-2019'), 'tuotepolku', 'sampoid', 'talousosastoid', 'talousosastopolku'),
  ((SELECT id FROM urakka WHERE nimi='Espoon alueurakka 2014-2019'), (SELECT id FROM toimenpidekoodi WHERE koodi='23124'), 'Espoo Sorateiden hoito TP 2014-2019', (SELECT alkupvm FROM urakka WHERE nimi='Espoon alueurakka 2014-2019'), (SELECT loppupvm FROM urakka WHERE nimi='Espoon alueurakka 2014-2019'), 'tuotepolku', 'sampoid', 'talousosastoid', 'talousosastopolku');



INSERT INTO kokonaishintainen_tyo (vuosi,kuukausi,summa,maksupvm,toimenpideinstanssi,sopimus) VALUES (2005, 10, 3500, '2005-10-15', (SELECT id FROM toimenpideinstanssi WHERE nimi='Oulu Talvihoito TP'), (SELECT id FROM sopimus WHERE urakka = (SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2005-2012') AND paasopimus IS null));
INSERT INTO kokonaishintainen_tyo (vuosi,kuukausi,summa,maksupvm,toimenpideinstanssi,sopimus) VALUES (2005, 11, 3500, '2005-11-15', (SELECT id FROM toimenpideinstanssi WHERE nimi='Oulu Talvihoito TP'), (SELECT id FROM sopimus WHERE urakka = (SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2005-2012') AND paasopimus IS null));
INSERT INTO kokonaishintainen_tyo (vuosi,kuukausi,summa,maksupvm,toimenpideinstanssi,sopimus) VALUES (2005, 12, 3500, '2005-12-15', (SELECT id FROM toimenpideinstanssi WHERE nimi='Oulu Talvihoito TP'), (SELECT id FROM sopimus WHERE urakka = (SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2005-2012') AND paasopimus IS null));
INSERT INTO kokonaishintainen_tyo (vuosi,kuukausi,summa,maksupvm,toimenpideinstanssi,sopimus) VALUES (2006, 1, 3500, '2006-01-15', (SELECT id FROM toimenpideinstanssi WHERE nimi='Oulu Talvihoito TP'), (SELECT id FROM sopimus WHERE urakka = (SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2005-2012') AND paasopimus IS null));
INSERT INTO kokonaishintainen_tyo (vuosi,kuukausi,summa,maksupvm,toimenpideinstanssi,sopimus) VALUES (2006, 2, 3500, '2006-02-15', (SELECT id FROM toimenpideinstanssi WHERE nimi='Oulu Talvihoito TP'), (SELECT id FROM sopimus WHERE urakka = (SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2005-2012') AND paasopimus IS null));
INSERT INTO kokonaishintainen_tyo (vuosi,kuukausi,summa,maksupvm,toimenpideinstanssi,sopimus) VALUES (2006, 3, 3500, '2006-03-15', (SELECT id FROM toimenpideinstanssi WHERE nimi='Oulu Talvihoito TP'), (SELECT id FROM sopimus WHERE urakka = (SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2005-2012') AND paasopimus IS null));
INSERT INTO kokonaishintainen_tyo (vuosi,kuukausi,summa,maksupvm,toimenpideinstanssi,sopimus) VALUES (2006, 4, 3500, '2006-04-15', (SELECT id FROM toimenpideinstanssi WHERE nimi='Oulu Talvihoito TP'), (SELECT id FROM sopimus WHERE urakka = (SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2005-2012') AND paasopimus IS null));
INSERT INTO kokonaishintainen_tyo (vuosi,kuukausi,summa,maksupvm,toimenpideinstanssi,sopimus) VALUES (2006, 5, 3500, '2006-05-15', (SELECT id FROM toimenpideinstanssi WHERE nimi='Oulu Talvihoito TP'), (SELECT id FROM sopimus WHERE urakka = (SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2005-2012') AND paasopimus IS null));
INSERT INTO kokonaishintainen_tyo (vuosi,kuukausi,summa,maksupvm,toimenpideinstanssi,sopimus) VALUES (2006, 6, 3500, '2006-06-15', (SELECT id FROM toimenpideinstanssi WHERE nimi='Oulu Talvihoito TP'), (SELECT id FROM sopimus WHERE urakka = (SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2005-2012') AND paasopimus IS null));
INSERT INTO kokonaishintainen_tyo (vuosi,kuukausi,summa,maksupvm,toimenpideinstanssi,sopimus) VALUES (2006, 7, 3500, '2006-07-15', (SELECT id FROM toimenpideinstanssi WHERE nimi='Oulu Talvihoito TP'), (SELECT id FROM sopimus WHERE urakka = (SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2005-2012') AND paasopimus IS null));
INSERT INTO kokonaishintainen_tyo (vuosi,kuukausi,summa,maksupvm,toimenpideinstanssi,sopimus) VALUES (2006, 8, 3500, '2006-08-15', (SELECT id FROM toimenpideinstanssi WHERE nimi='Oulu Talvihoito TP'), (SELECT id FROM sopimus WHERE urakka = (SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2005-2012') AND paasopimus IS null));
INSERT INTO kokonaishintainen_tyo (vuosi,kuukausi,summa,maksupvm,toimenpideinstanssi,sopimus) VALUES (2006, 9, 3500, '2006-09-15', (SELECT id FROM toimenpideinstanssi WHERE nimi='Oulu Talvihoito TP'), (SELECT id FROM sopimus WHERE urakka = (SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2005-2012') AND paasopimus IS null));

-- hoitokausi 2006-2007
INSERT INTO kokonaishintainen_tyo (vuosi,kuukausi,summa,maksupvm,toimenpideinstanssi,sopimus) VALUES (2006, 10, 3500, '2006-10-15', (SELECT id FROM toimenpideinstanssi WHERE nimi='Oulu Talvihoito TP'), (SELECT id FROM sopimus WHERE urakka = (SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2005-2012') AND paasopimus IS null));
INSERT INTO kokonaishintainen_tyo (vuosi,kuukausi,summa,maksupvm,toimenpideinstanssi,sopimus) VALUES (2006, 11, 3500, '2006-11-15', (SELECT id FROM toimenpideinstanssi WHERE nimi='Oulu Talvihoito TP'), (SELECT id FROM sopimus WHERE urakka = (SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2005-2012') AND paasopimus IS null));
INSERT INTO kokonaishintainen_tyo (vuosi,kuukausi,summa,maksupvm,toimenpideinstanssi,sopimus) VALUES (2006, 12, 3500, '2006-12-15', (SELECT id FROM toimenpideinstanssi WHERE nimi='Oulu Talvihoito TP'), (SELECT id FROM sopimus WHERE urakka = (SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2005-2012') AND paasopimus IS null));
INSERT INTO kokonaishintainen_tyo (vuosi,kuukausi,summa,maksupvm,toimenpideinstanssi,sopimus) VALUES (2007, 1, 3500, '2007-01-15', (SELECT id FROM toimenpideinstanssi WHERE nimi='Oulu Talvihoito TP'), (SELECT id FROM sopimus WHERE urakka = (SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2005-2012') AND paasopimus IS null));
INSERT INTO kokonaishintainen_tyo (vuosi,kuukausi,summa,maksupvm,toimenpideinstanssi,sopimus) VALUES (2007, 2, 3500, '2007-02-15', (SELECT id FROM toimenpideinstanssi WHERE nimi='Oulu Talvihoito TP'), (SELECT id FROM sopimus WHERE urakka = (SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2005-2012') AND paasopimus IS null));
INSERT INTO kokonaishintainen_tyo (vuosi,kuukausi,summa,maksupvm,toimenpideinstanssi,sopimus) VALUES (2007, 3, 3500, '2007-03-15', (SELECT id FROM toimenpideinstanssi WHERE nimi='Oulu Talvihoito TP'), (SELECT id FROM sopimus WHERE urakka = (SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2005-2012') AND paasopimus IS null));
INSERT INTO kokonaishintainen_tyo (vuosi,kuukausi,summa,maksupvm,toimenpideinstanssi,sopimus) VALUES (2007, 4, 3500, '2007-04-15', (SELECT id FROM toimenpideinstanssi WHERE nimi='Oulu Talvihoito TP'), (SELECT id FROM sopimus WHERE urakka = (SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2005-2012') AND paasopimus IS null));
INSERT INTO kokonaishintainen_tyo (vuosi,kuukausi,summa,maksupvm,toimenpideinstanssi,sopimus) VALUES (2007, 5, 3500, '2007-05-15', (SELECT id FROM toimenpideinstanssi WHERE nimi='Oulu Talvihoito TP'), (SELECT id FROM sopimus WHERE urakka = (SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2005-2012') AND paasopimus IS null));
INSERT INTO kokonaishintainen_tyo (vuosi,kuukausi,summa,maksupvm,toimenpideinstanssi,sopimus) VALUES (2007, 6, 3500, '2007-06-15', (SELECT id FROM toimenpideinstanssi WHERE nimi='Oulu Talvihoito TP'), (SELECT id FROM sopimus WHERE urakka = (SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2005-2012') AND paasopimus IS null));
INSERT INTO kokonaishintainen_tyo (vuosi,kuukausi,summa,maksupvm,toimenpideinstanssi,sopimus) VALUES (2007, 7, 3500, '2007-07-15', (SELECT id FROM toimenpideinstanssi WHERE nimi='Oulu Talvihoito TP'), (SELECT id FROM sopimus WHERE urakka = (SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2005-2012') AND paasopimus IS null));
INSERT INTO kokonaishintainen_tyo (vuosi,kuukausi,summa,maksupvm,toimenpideinstanssi,sopimus) VALUES (2007, 8, 3500, '2007-08-15', (SELECT id FROM toimenpideinstanssi WHERE nimi='Oulu Talvihoito TP'), (SELECT id FROM sopimus WHERE urakka = (SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2005-2012') AND paasopimus IS null));
INSERT INTO kokonaishintainen_tyo (vuosi,kuukausi,summa,maksupvm,toimenpideinstanssi,sopimus) VALUES (2007, 9, 3500, '2007-09-15', (SELECT id FROM toimenpideinstanssi WHERE nimi='Oulu Talvihoito TP'), (SELECT id FROM sopimus WHERE urakka = (SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2005-2012') AND paasopimus IS null));

-- toisella sopimusnumerolla kiusaksi yksi työ
INSERT INTO kokonaishintainen_tyo (vuosi,kuukausi,summa,maksupvm,toimenpideinstanssi,sopimus) VALUES (2006, 9, 9999, '2006-09-15', (SELECT id FROM toimenpideinstanssi WHERE nimi='Oulu Talvihoito TP'), (SELECT id FROM sopimus WHERE urakka = (SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2005-2012') AND paasopimus IS NOT null));


INSERT INTO kokonaishintainen_tyo (vuosi,kuukausi,summa,maksupvm,toimenpideinstanssi,sopimus) VALUES (2005, 10, 1500, '2005-10-15', (SELECT id FROM toimenpideinstanssi WHERE nimi='Oulu Sorateiden hoito TP'), (SELECT id FROM sopimus WHERE urakka = (SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2005-2012') AND paasopimus IS null));
INSERT INTO kokonaishintainen_tyo (vuosi,kuukausi,summa,maksupvm,toimenpideinstanssi,sopimus) VALUES (2005, 11, 1500, '2005-11-15', (SELECT id FROM toimenpideinstanssi WHERE nimi='Oulu Sorateiden hoito TP'), (SELECT id FROM sopimus WHERE urakka = (SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2005-2012') AND paasopimus IS null));
INSERT INTO kokonaishintainen_tyo (vuosi,kuukausi,summa,maksupvm,toimenpideinstanssi,sopimus) VALUES (2005, 12, 1500, '2005-12-15', (SELECT id FROM toimenpideinstanssi WHERE nimi='Oulu Sorateiden hoito TP'), (SELECT id FROM sopimus WHERE urakka = (SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2005-2012') AND paasopimus IS null));
INSERT INTO kokonaishintainen_tyo (vuosi,kuukausi,summa,maksupvm,toimenpideinstanssi,sopimus) VALUES (2006, 1, 1500, '2006-01-15', (SELECT id FROM toimenpideinstanssi WHERE nimi='Oulu Sorateiden hoito TP'), (SELECT id FROM sopimus WHERE urakka = (SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2005-2012') AND paasopimus IS null));
INSERT INTO kokonaishintainen_tyo (vuosi,kuukausi,summa,maksupvm,toimenpideinstanssi,sopimus) VALUES (2006, 2, 1500, '2006-02-15', (SELECT id FROM toimenpideinstanssi WHERE nimi='Oulu Sorateiden hoito TP'), (SELECT id FROM sopimus WHERE urakka = (SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2005-2012') AND paasopimus IS null));
INSERT INTO kokonaishintainen_tyo (vuosi,kuukausi,summa,maksupvm,toimenpideinstanssi,sopimus) VALUES (2006, 3, 1500, '2006-03-15', (SELECT id FROM toimenpideinstanssi WHERE nimi='Oulu Sorateiden hoito TP'), (SELECT id FROM sopimus WHERE urakka = (SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2005-2012') AND paasopimus IS null));
INSERT INTO kokonaishintainen_tyo (vuosi,kuukausi,summa,maksupvm,toimenpideinstanssi,sopimus) VALUES (2006, 4, 1500, '2006-04-15', (SELECT id FROM toimenpideinstanssi WHERE nimi='Oulu Sorateiden hoito TP'), (SELECT id FROM sopimus WHERE urakka = (SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2005-2012') AND paasopimus IS null));
INSERT INTO kokonaishintainen_tyo (vuosi,kuukausi,summa,maksupvm,toimenpideinstanssi,sopimus) VALUES (2006, 5, 1500, '2006-05-15', (SELECT id FROM toimenpideinstanssi WHERE nimi='Oulu Sorateiden hoito TP'), (SELECT id FROM sopimus WHERE urakka = (SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2005-2012') AND paasopimus IS null));
INSERT INTO kokonaishintainen_tyo (vuosi,kuukausi,summa,maksupvm,toimenpideinstanssi,sopimus) VALUES (2006, 6, 1500, '2006-06-15', (SELECT id FROM toimenpideinstanssi WHERE nimi='Oulu Sorateiden hoito TP'), (SELECT id FROM sopimus WHERE urakka = (SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2005-2012') AND paasopimus IS null));
INSERT INTO kokonaishintainen_tyo (vuosi,kuukausi,summa,maksupvm,toimenpideinstanssi,sopimus) VALUES (2006, 7, 1500, '2006-07-15', (SELECT id FROM toimenpideinstanssi WHERE nimi='Oulu Sorateiden hoito TP'), (SELECT id FROM sopimus WHERE urakka = (SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2005-2012') AND paasopimus IS null));
INSERT INTO kokonaishintainen_tyo (vuosi,kuukausi,summa,maksupvm,toimenpideinstanssi,sopimus) VALUES (2006, 8, 1500, '2006-08-15', (SELECT id FROM toimenpideinstanssi WHERE nimi='Oulu Sorateiden hoito TP'), (SELECT id FROM sopimus WHERE urakka = (SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2005-2012') AND paasopimus IS null));
INSERT INTO kokonaishintainen_tyo (vuosi,kuukausi,summa,maksupvm,toimenpideinstanssi,sopimus) VALUES (2006, 9, 1500, '2006-09-15', (SELECT id FROM toimenpideinstanssi WHERE nimi='Oulu Sorateiden hoito TP'), (SELECT id FROM sopimus WHERE urakka = (SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2005-2012') AND paasopimus IS null));

-- Vesiväylien suunnitellut työt

INSERT INTO kokonaishintainen_tyo(vuosi, kuukausi, summa, maksupvm, toimenpideinstanssi, sopimus) VALUES (2016, 8, 0.3, '2016-08-01', (SELECT id FROM toimenpideinstanssi WHERE nimi = 'Väylänhoito, Itäinen Suomenlahti, sopimuksen kok.hintaiset työt, rann kmrk, TP'), 34);
INSERT INTO kokonaishintainen_tyo(vuosi, kuukausi, summa, maksupvm, toimenpideinstanssi, sopimus) VALUES (2017, 1, 1.8, '2017-01-01', (SELECT id FROM toimenpideinstanssi WHERE nimi = 'Väylänhoito, Itäinen Suomenlahti, sopimuksen kok.hintaiset työt, rann kmrk, TP'), 34);
INSERT INTO kokonaishintainen_tyo(vuosi, kuukausi, summa, maksupvm, toimenpideinstanssi, sopimus) VALUES (2016, 10, 0.9, '2016-10-01', (SELECT id FROM toimenpideinstanssi WHERE nimi = 'Väylänhoito, Itäinen Suomenlahti, sopimuksen kok.hintaiset työt, rann kmrk, TP'), 34);
INSERT INTO kokonaishintainen_tyo(vuosi, kuukausi, summa, maksupvm, toimenpideinstanssi, sopimus) VALUES (2017, 4, 2.7, '2017-04-01', (SELECT id FROM toimenpideinstanssi WHERE nimi = 'Väylänhoito, Itäinen Suomenlahti, sopimuksen kok.hintaiset työt, rann kmrk, TP'), 34);
INSERT INTO kokonaishintainen_tyo(vuosi, kuukausi, summa, maksupvm, toimenpideinstanssi, sopimus) VALUES (2017, 2, 2.1, '2017-02-01', (SELECT id FROM toimenpideinstanssi WHERE nimi = 'Väylänhoito, Itäinen Suomenlahti, sopimuksen kok.hintaiset työt, rann kmrk, TP'), 34);
INSERT INTO kokonaishintainen_tyo(vuosi, kuukausi, summa, maksupvm, toimenpideinstanssi, sopimus) VALUES (2016, 9, 0.6, '2016-09-01', (SELECT id FROM toimenpideinstanssi WHERE nimi = 'Väylänhoito, Itäinen Suomenlahti, sopimuksen kok.hintaiset työt, rann kmrk, TP'), 34);
INSERT INTO kokonaishintainen_tyo(vuosi, kuukausi, summa, maksupvm, toimenpideinstanssi, sopimus) VALUES (2017, 6, 6, '2017-06-01', (SELECT id FROM toimenpideinstanssi WHERE nimi = 'Väylänhoito, Itäinen Suomenlahti, sopimuksen kok.hintaiset työt, rann kmrk, TP'), 34);
INSERT INTO kokonaishintainen_tyo(vuosi, kuukausi, summa, maksupvm, toimenpideinstanssi, sopimus) VALUES (2017, 7, 1.5, '2017-07-01', (SELECT id FROM toimenpideinstanssi WHERE nimi = 'Väylänhoito, Itäinen Suomenlahti, sopimuksen kok.hintaiset työt, rann kmrk, TP'), 34);
INSERT INTO kokonaishintainen_tyo(vuosi, kuukausi, summa, maksupvm, toimenpideinstanssi, sopimus) VALUES (2016, 12, 1.5, '2016-12-01', (SELECT id FROM toimenpideinstanssi WHERE nimi = 'Väylänhoito, Itäinen Suomenlahti, sopimuksen kok.hintaiset työt, rann kmrk, TP'), 34);
INSERT INTO kokonaishintainen_tyo(vuosi, kuukausi, summa, maksupvm, toimenpideinstanssi, sopimus) VALUES (2016, 11, 1.2, '2016-11-01', (SELECT id FROM toimenpideinstanssi WHERE nimi = 'Väylänhoito, Itäinen Suomenlahti, sopimuksen kok.hintaiset työt, rann kmrk, TP'), 34);
INSERT INTO kokonaishintainen_tyo(vuosi, kuukausi, summa, maksupvm, toimenpideinstanssi, sopimus) VALUES (2017, 5, 9, '2017-05-01', (SELECT id FROM toimenpideinstanssi WHERE nimi = 'Väylänhoito, Itäinen Suomenlahti, sopimuksen kok.hintaiset työt, rann kmrk, TP'), 34);
INSERT INTO kokonaishintainen_tyo(vuosi, kuukausi, summa, maksupvm, toimenpideinstanssi, sopimus) VALUES (2017, 3, 2.4, '2017-03-01', (SELECT id FROM toimenpideinstanssi WHERE nimi = 'Väylänhoito, Itäinen Suomenlahti, sopimuksen kok.hintaiset työt, rann kmrk, TP'), 34);

INSERT INTO toimenpideinstanssi (urakka, toimenpide, nimi, alkupvm, loppupvm)
  SELECT id, (select id from toimenpidekoodi where koodi='VV111'), nimi, alkupvm, loppupvm
  FROM urakka
  WHERE tyyppi='vesivayla-hoito';