-- Pistokoe

INSERT INTO tarkastus (urakka, sopimus, aika, tr_numero, tr_alkuosa, tr_loppuosa, tr_loppuetaisyys, sijainti, tarkastaja, tyyppi, havainnot, luotu, luoja, tr_alkuetaisyys) VALUES ((SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2005-2010'), (SELECT id FROM sopimus WHERE nimi = 'Oulun alueurakka pääsopimus' AND urakka = 1), '2005-10-01 10:00.00', 1 ,2, 3, 4, point(430768.8350704433, 7203153.238678749)::GEOMETRY, 'Ismo', 'pistokoe'::tarkastustyyppi, 'jotain havaintoja siellä oli', NOW(), 1, 3);
INSERT INTO tarkastus (urakka, sopimus, aika, tr_numero, tr_alkuosa, tr_loppuosa, tr_loppuetaisyys, sijainti, tarkastaja, tyyppi, havainnot, luotu, luoja, tr_alkuetaisyys) VALUES ((SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2005-2010'), (SELECT id FROM sopimus WHERE nimi = 'Oulun alueurakka pääsopimus' AND urakka = 1), '2005-10-03 10:00.00', 1 ,2, 3, 4, point(430080.9018158768, 7204538.659816418)::GEOMETRY, 'Matti', 'pistokoe'::tarkastustyyppi, 'havaittiin kaikenlaista', NOW(), 1, 3);

-- Talvihoito

INSERT INTO tarkastus (urakka, sopimus, aika, tr_numero, tr_alkuosa, tr_alkuetaisyys, tr_loppuosa, tr_loppuetaisyys, sijainti, tarkastaja, tyyppi, havainnot, luotu, luoja) VALUES ((SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2014-2019'), (SELECT id FROM sopimus WHERE urakka = (SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2014-2019') AND paasopimus IS NULL), '2015-12-28 10:00:02', 4 ,364, 8012, null, null, point(429000, 7202314)::GEOMETRY, 'Matti', 'talvihoito'::tarkastustyyppi, 'järjestelmän raportoima testitarkastus 1', NOW(), (SELECT id from kayttaja WHERE kayttajanimi = 'fastroi'));
INSERT INTO tarkastus (urakka, sopimus, aika, tr_numero, tr_alkuosa, tr_alkuetaisyys, tr_loppuosa, tr_loppuetaisyys, sijainti, tarkastaja, tyyppi, havainnot, luotu, luoja) VALUES ((SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2014-2019'), (SELECT id FROM sopimus WHERE urakka = (SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2014-2019') AND paasopimus IS NULL), '2016-01-4 06:02:20', 4 ,364, 5, null, null, point(430750.5220656799, 7198888.689460491)::GEOMETRY, 'Matti', 'talvihoito'::tarkastustyyppi, 'järjestelmän raportoima testitarkastus 2', NOW(), (SELECT id from kayttaja WHERE kayttajanimi = 'fastroi'));
INSERT INTO tarkastus (urakka, sopimus, aika, tr_numero, tr_alkuosa, tr_alkuetaisyys, tr_loppuosa, tr_loppuetaisyys, sijainti, tarkastaja, tyyppi, havainnot, luotu, luoja) VALUES ((SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2014-2019'), (SELECT id FROM sopimus WHERE urakka = (SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2014-2019') AND paasopimus IS NULL), '2015-11-23 11:00:30', 4 ,364, 8012, null, null, point(430999.34049970115, 7202184.240103625)::GEOMETRY, 'Matti', 'talvihoito'::tarkastustyyppi, 'järjestelmän raportoima testitarkastus 3', NOW(), (SELECT id from kayttaja WHERE kayttajanimi = 'fastroi'));
INSERT INTO tarkastus (urakka, sopimus, aika, tr_numero, tr_alkuosa, tr_alkuetaisyys, tr_loppuosa, tr_loppuetaisyys, sijainti, tarkastaja, tyyppi, havainnot, luotu, luoja) VALUES ((SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2014-2019'), (SELECT id FROM sopimus WHERE urakka = (SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2014-2019') AND paasopimus IS NULL), '2015-10-23 10:00:02', 4 ,364, 8012, null, null, point(430999.3404997012, 7201565.577905941)::GEOMETRY, 'Matti', 'talvihoito'::tarkastustyyppi, 'järjestelmän raportoima testitarkastus 4', NOW(), (SELECT id from kayttaja WHERE kayttajanimi = 'fastroi'));
INSERT INTO tarkastus (urakka, sopimus, aika, tr_numero, tr_alkuosa, tr_alkuetaisyys, tr_loppuosa, tr_loppuetaisyys, sijainti, tarkastaja, tyyppi, havainnot, luotu, luoja) VALUES ((SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2014-2019'), (SELECT id FROM sopimus WHERE urakka = (SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2014-2019') AND paasopimus IS NULL), '2016-01-02 16:02:00', 4 ,364, 8012, null, null, point(430877.5189858716, 7200994.6888509365)::GEOMETRY, 'Matti', 'talvihoito'::tarkastustyyppi, 'Urakoitsija on kirjannut tämän tarkastuksen Harjaan käsin', NOW(), (SELECT id from kayttaja WHERE kayttajanimi = 'yit_uuvh'));

INSERT INTO talvihoitomittaus (tarkastus, talvihoitoluokka, lumimaara, tasaisuus, kitka, lampotila, ajosuunta) VALUES ((SELECT id FROM tarkastus WHERE havainnot = 'Urakoitsija on kirjannut tämän tarkastuksen Harjaan käsin'), 'A', 10, 5, 2, -16, 1);
INSERT INTO talvihoitomittaus (tarkastus, talvihoitoluokka, lumimaara, tasaisuus, kitka, lampotila, ajosuunta) VALUES ((SELECT id FROM tarkastus WHERE havainnot = 'järjestelmän raportoima testitarkastus 2'), 'B', 11, 6, 3, -15, 1);

INSERT INTO liite (nimi) VALUES ('kelitarkastus_2016.jpg');
INSERT INTO tarkastus_liite (tarkastus, liite) VALUES ((SELECT id FROM tarkastus WHERE havainnot ='järjestelmän raportoima testitarkastus 2'), (SELECT id FROM liite WHERE nimi ='kelitarkastus_2016.jpg'));

-- Tiestö

INSERT INTO tarkastus (urakka, sopimus, aika, tr_numero, tr_alkuosa, tr_alkuetaisyys, tr_loppuosa, tr_loppuetaisyys, sijainti, tarkastaja, tyyppi, havainnot, luotu, luoja) VALUES ((SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2014-2019'), (SELECT id FROM sopimus WHERE urakka = (SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2014-2019') AND paasopimus IS NULL), '2015-01-02 16:02:00', 4 ,364, 8012, null, null, point(430877.5189858716, 7200994.6888509365)::GEOMETRY, 'Tarmo Tarkastaja', 'tiesto'::tarkastustyyppi, 'Tiessä oli pieni kuoppa', NOW(), (SELECT id from kayttaja WHERE kayttajanimi = 'yit_uuvh'));
INSERT INTO tarkastus (urakka, sopimus, aika, tr_numero, tr_alkuosa, tr_alkuetaisyys, tr_loppuosa, tr_loppuetaisyys, sijainti, tarkastaja, tyyppi, havainnot, luotu, luoja) VALUES ((SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2014-2019'), (SELECT id FROM sopimus WHERE urakka = (SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2014-2019') AND paasopimus IS NULL), '2015-01-05 16:18:00', 4 ,364, 8012, null, null, point(430999.34049970115, 7202184.240103625)::GEOMETRY, 'Tarmo Tarkastaja', 'tiesto'::tarkastustyyppi, 'Tiessä oli muutamia pieniä kuoppia, ei kuitenkaan mitään vakavaa ongelmaa aiheuta', NOW(), (SELECT id from kayttaja WHERE kayttajanimi = 'yit_uuvh'));

INSERT INTO liite (nimi) VALUES ('tiestotarkastus_456.jpg');
INSERT INTO liite (nimi) VALUES ('tiesto5667858.jpg');
INSERT INTO tarkastus_liite (tarkastus, liite) VALUES ((SELECT id FROM tarkastus WHERE havainnot ='Tiessä oli pieni kuoppa'), (SELECT id FROM liite WHERE nimi ='tiestotarkastus_456.jpg'));
INSERT INTO tarkastus_liite (tarkastus, liite) VALUES ((SELECT id FROM tarkastus WHERE havainnot ='Tiessä oli pieni kuoppa'), (SELECT id FROM liite WHERE nimi ='tiesto5667858.jpg'));

-- Soratie

INSERT INTO tarkastus (urakka, sopimus, aika, tr_numero, tr_alkuosa, tr_alkuetaisyys, tr_loppuosa, tr_loppuetaisyys, sijainti, tarkastaja, tyyppi, havainnot, luotu, luoja) VALUES ((SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2014-2019'), (SELECT id FROM sopimus WHERE urakka = (SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2014-2019') AND paasopimus IS NULL), '2015-01-05 16:18:00', 4 ,364, 8012, null, null, point(430999.34049970115, 7202184.240103625)::GEOMETRY, 'Tarmo Tarkastaja', 'soratie'::tarkastustyyppi, 'Soratietarkastus 1', NOW(), (SELECT id from kayttaja WHERE kayttajanimi = 'yit_uuvh'));
INSERT INTO tarkastus (urakka, sopimus, aika, tr_numero, tr_alkuosa, tr_alkuetaisyys, tr_loppuosa, tr_loppuetaisyys, sijainti, tarkastaja, tyyppi, havainnot, luotu, luoja) VALUES ((SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2014-2019'), (SELECT id FROM sopimus WHERE urakka = (SELECT id FROM urakka WHERE nimi='Oulun alueurakka 2014-2019') AND paasopimus IS NULL), '2015-01-05 16:18:00', 5 ,364, 8012, null, null, point(430999.34049970115, 7202184.240103625)::GEOMETRY, 'Tarmo Tarkastaja', 'soratie'::tarkastustyyppi, 'Soratietarkastus 2', NOW(), (SELECT id from kayttaja WHERE kayttajanimi = 'yit_uuvh'));

INSERT INTO soratiemittaus (tarkastus, hoitoluokka, tasaisuus, kiinteys, polyavyys, sivukaltevuus) VALUES ((SELECT id FROM tarkastus WHERE havainnot = 'Soratietarkastus 1'), 1, 3, 4, 5, 1);
INSERT INTO soratiemittaus (tarkastus, hoitoluokka, tasaisuus, kiinteys, polyavyys, sivukaltevuus) VALUES ((SELECT id FROM tarkastus WHERE havainnot = 'Soratietarkastus 1'), 1, 2, 4, 2, 1);
INSERT INTO soratiemittaus (tarkastus, hoitoluokka, tasaisuus, kiinteys, polyavyys, sivukaltevuus) VALUES ((SELECT id FROM tarkastus WHERE havainnot = 'Soratietarkastus 2'), 2, 5, 4, 3, 1);
