INSERT INTO urakka_tehtavamaara (urakka, "hoitokauden-alkuvuosi", tehtava, maara) VALUES ((select id from urakka where nimi = 'Oulun MHU 2019-2024'), 2020, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Opastustaulujen ja liikennemerkkien rakentaminen tukirakenteineen (sis. liikennemerkkien poistamisia)' and poistettu = false), 200);
INSERT INTO urakka_tehtavamaara (urakka, "hoitokauden-alkuvuosi", tehtava, maara) VALUES ((select id from urakka where nimi = 'Oulun MHU 2019-2024'), 2020, (select id from toimenpidekoodi where nimi = 'Päällystettyjen teiden palteiden poisto'), 33.4);
INSERT INTO urakka_tehtavamaara (urakka, "hoitokauden-alkuvuosi", tehtava, maara) VALUES ((select id from urakka where nimi = 'Oulun MHU 2019-2024'), 2020, (select id from toimenpidekoodi where nimi = 'III'), 32.6);
INSERT INTO urakka_tehtavamaara (urakka, "hoitokauden-alkuvuosi", tehtava, maara) VALUES ((select id from urakka where nimi = 'Oulun MHU 2019-2024'), 2020, (select id from toimenpidekoodi where nimi = 'Katupölynsidonta'), 400);
INSERT INTO urakka_tehtavamaara (urakka, "hoitokauden-alkuvuosi", tehtava, maara) VALUES ((select id from urakka where nimi = 'Oulun MHU 2019-2024'), 2021, (select id from toimenpidekoodi where nimi = 'Katupölynsidonta'), 666);
INSERT INTO urakka_tehtavamaara (urakka, "hoitokauden-alkuvuosi", tehtava, maara) VALUES ((select id from urakka where nimi = 'Oulun MHU 2019-2024'), 2020, (select id from toimenpidekoodi where nimi = 'Ib rampit'), 500);
INSERT INTO urakka_tehtavamaara (urakka, "hoitokauden-alkuvuosi", tehtava, maara) VALUES ((select id from urakka where nimi = 'Oulun MHU 2019-2024'), 2020, (select id from toimenpidekoodi where nimi = 'K2'), 55.5);
INSERT INTO urakka_tehtavamaara (urakka, "hoitokauden-alkuvuosi", tehtava, maara) VALUES ((select id from urakka where nimi = 'Oulun MHU 2019-2024'), 2020, (select id from toimenpidekoodi where nimi = 'Sorateiden pölynsidonta'), 777.6);
INSERT INTO urakka_tehtavamaara (urakka, "hoitokauden-alkuvuosi", tehtava, maara) VALUES ((select id from urakka where nimi = 'Oulun MHU 2019-2024'), 2020, (select id from toimenpidekoodi where nimi = 'Is ohituskaistat'), 69.96);
INSERT INTO urakka_tehtavamaara (urakka, "hoitokauden-alkuvuosi", tehtava, maara) VALUES ((select id from urakka where nimi = 'Oulun MHU 2019-2024'), 2021, (select id from toimenpidekoodi where nimi = 'Sorateiden pölynsidonta'), 123.4);
INSERT INTO urakka_tehtavamaara (urakka, "hoitokauden-alkuvuosi", tehtava, maara) VALUES ((select id from urakka where nimi = 'Oulun MHU 2019-2024'), 2021, (select id from toimenpidekoodi where nimi = 'Is ohituskaistat'), 5556);

-- Valtakunnallinen määrätoteumaraportti
INSERT INTO urakka_tehtavamaara (urakka, "hoitokauden-alkuvuosi", tehtava, maara) VALUES ((select id from urakka where nimi = 'Ivalon MHU testiurakka (uusi)'), 2020, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Vesakonraivaus' and poistettu = false), 111.1);
INSERT INTO urakka_tehtavamaara (urakka, "hoitokauden-alkuvuosi", tehtava, maara) VALUES ((select id from urakka where nimi = 'Ivalon MHU testiurakka (uusi)'), 2020, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Puun poisto raivausjätteineen (taajamassa)' and poistettu = false), 222.1);
INSERT INTO urakka_tehtavamaara (urakka, "hoitokauden-alkuvuosi", tehtava, maara) VALUES ((select id from urakka where nimi = 'Ivalon MHU testiurakka (uusi)'), 2020, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Ic 1-ajorat' and poistettu = false), 333.1);
INSERT INTO urakka_tehtavamaara (urakka, "hoitokauden-alkuvuosi", tehtava, maara) VALUES ((select id from urakka where nimi = 'Ivalon MHU testiurakka (uusi)'), 2020, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Päällystettyjen teiden sr-pientareen täyttö' and poistettu = false), 433.1);
INSERT INTO urakka_tehtavamaara (urakka, "hoitokauden-alkuvuosi", tehtava, maara) VALUES ((select id from urakka where nimi = 'Ivalon MHU testiurakka (uusi)'), 2021, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Päällystettyjen teiden sr-pientareen täyttö' and poistettu = false), 544.1);
INSERT INTO urakka_tehtavamaara (urakka, "hoitokauden-alkuvuosi", tehtava, maara) VALUES ((select id from urakka where nimi = 'Ivalon MHU testiurakka (uusi)'), 2021, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Vesakonraivaus' and poistettu = false), 321.1);
INSERT INTO urakka_tehtavamaara (urakka, "hoitokauden-alkuvuosi", tehtava, maara) VALUES ((select id from urakka where nimi = 'Ivalon MHU testiurakka (uusi)'), 2021, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Puun poisto raivausjätteineen (taajamassa)' and poistettu = false), 654.1);
INSERT INTO urakka_tehtavamaara (urakka, "hoitokauden-alkuvuosi", tehtava, maara) VALUES ((select id from urakka where nimi = 'Ivalon MHU testiurakka (uusi)'), 2021, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Ic 1-ajorat' and poistettu = false), 321.1);

INSERT INTO urakka_tehtavamaara (urakka, "hoitokauden-alkuvuosi", tehtava, maara) VALUES ((select id from urakka where nimi = 'Oulun MHU 2019-2024'), 2020, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Pysäkkikatosten puhdistus' and poistettu = false), 6.12);
INSERT INTO urakka_tehtavamaara (urakka, "hoitokauden-alkuvuosi", tehtava, maara) VALUES ((select id from urakka where nimi = 'Oulun MHU 2019-2024'), 2021, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Pysäkkikatosten puhdistus' and poistettu = false), 7.12);
INSERT INTO urakka_tehtavamaara (urakka, "hoitokauden-alkuvuosi", tehtava, maara) VALUES ((select id from urakka where nimi = 'Oulun MHU 2019-2024'), 2020, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Ic 1-ajorat' and poistettu = false), 8.12);
INSERT INTO urakka_tehtavamaara (urakka, "hoitokauden-alkuvuosi", tehtava, maara) VALUES ((select id from urakka where nimi = 'Oulun MHU 2019-2024'), 2021, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Ic 1-ajorat' and poistettu = false), 9.12);
INSERT INTO urakka_tehtavamaara (urakka, "hoitokauden-alkuvuosi", tehtava, maara) VALUES ((select id from urakka where nimi = 'Oulun MHU 2019-2024'), 2020, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Graffitien poisto' and poistettu = false), 10.12);
INSERT INTO urakka_tehtavamaara (urakka, "hoitokauden-alkuvuosi", tehtava, maara) VALUES ((select id from urakka where nimi = 'Oulun MHU 2019-2024'), 2021, (SELECT id FROM toimenpidekoodi WHERE nimi = 'Graffitien poisto' and poistettu = false), 11.12);

INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2020-10-01', '2020-12-31', 52.2, 'jm', 4, null, (select id from toimenpidekoodi where nimi = 'Puun poisto raivausjätteineen (taajamassa)' and poistettu is not true), (SELECT id FROM urakka WHERE nimi = 'Aktiivinen Oulu Testi'), (SELECT id FROM sopimus WHERE urakka = (SELECT id FROM urakka WHERE nimi = 'Aktiivinen Oulu Testi')));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2020-10-01', '2020-12-31', 43.2, 'jm', 4, null, (select id from toimenpidekoodi where nimi = 'Päällystettyjen teiden sorapientareen kunnossapito' and poistettu is not true), (SELECT id FROM urakka WHERE nimi = 'Aktiivinen Oulu Testi'), (SELECT id FROM sopimus WHERE urakka = (SELECT id FROM urakka WHERE nimi = 'Aktiivinen Oulu Testi')));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2021-01-01', '2021-09-30', 34.2, 'jm', 4, null, (select id from toimenpidekoodi where nimi = 'Puun poisto raivausjätteineen (taajamassa)' and poistettu is not true), (SELECT id FROM urakka WHERE nimi = 'Aktiivinen Oulu Testi'), (SELECT id FROM sopimus WHERE urakka = (SELECT id FROM urakka WHERE nimi = 'Aktiivinen Oulu Testi')));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2021-01-01', '2021-09-30', 25.2, 'jm', 4, null, (select id from toimenpidekoodi where nimi = 'Päällystettyjen teiden sorapientareen kunnossapito' and poistettu is not true), (SELECT id FROM urakka WHERE nimi = 'Aktiivinen Oulu Testi'), (SELECT id FROM sopimus WHERE urakka = (SELECT id FROM urakka WHERE nimi = 'Aktiivinen Oulu Testi')));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2021-01-01', '2021-09-30', 16.2, 'jm', 4, null, (select id from toimenpidekoodi where nimi = 'Portaiden talvihoito' and poistettu is not true), (SELECT id FROM urakka WHERE nimi = 'Aktiivinen Oulu Testi'), (SELECT id FROM sopimus WHERE urakka = (SELECT id FROM urakka WHERE nimi = 'Aktiivinen Oulu Testi')));

INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2020-10-01', '2020-12-31', 22.7, 'jm', 4, null, (select id from toimenpidekoodi where nimi = 'Päällystettyjen teiden palteiden poisto' and poistettu is not true), (SELECT id FROM urakka WHERE nimi = 'Tampereen alueurakka 2017-2022'), (SELECT id FROM sopimus WHERE urakka = (SELECT id FROM urakka WHERE nimi = 'Tampereen alueurakka 2017-2022')));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2020-10-01', '2020-12-31', 33.7, 'jm', 4, null, (select id from toimenpidekoodi where nimi = 'Rumpujen korjaus ja uusiminen  600 - 1000 mm' and poistettu is not true), (SELECT id FROM urakka WHERE nimi = 'Tampereen alueurakka 2017-2022'), (SELECT id FROM sopimus WHERE urakka = (SELECT id FROM urakka WHERE nimi = 'Tampereen alueurakka 2017-2022')));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2021-01-01', '2021-09-30', 44.7, 'jm', 4, null, (select id from toimenpidekoodi where nimi = 'Päällystettyjen teiden palteiden poisto' and poistettu is not true), (SELECT id FROM urakka WHERE nimi = 'Tampereen alueurakka 2017-2022'), (SELECT id FROM sopimus WHERE urakka = (SELECT id FROM urakka WHERE nimi = 'Tampereen alueurakka 2017-2022')));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2021-01-01', '2021-09-30', 55.7, 'jm', 4, null, (select id from toimenpidekoodi where nimi = 'Rumpujen korjaus ja uusiminen  600 - 1000 mm' and poistettu is not true), (SELECT id FROM urakka WHERE nimi = 'Tampereen alueurakka 2017-2022'), (SELECT id FROM sopimus WHERE urakka = (SELECT id FROM urakka WHERE nimi = 'Tampereen alueurakka 2017-2022')));
INSERT INTO yksikkohintainen_tyo (alkupvm, loppupvm, maara, yksikko, yksikkohinta, kohde, tehtava, urakka, sopimus) VALUES ('2021-01-01', '2021-09-30', 66.7, 'jm', 4, null, (select id from toimenpidekoodi where nimi = 'Kaivojen ja putkistojen sulatus' and poistettu is not true), (SELECT id FROM urakka WHERE nimi = 'Tampereen alueurakka 2017-2022'), (SELECT id FROM sopimus WHERE urakka = (SELECT id FROM urakka WHERE nimi = 'Tampereen alueurakka 2017-2022')));