# Tätä docker-compose-fileä käytetään githubin actionseissa esimerkiksi testitietokannan helpompaan käynnistämiseen
# Samalla varmistetaan, että tarvittavat ympäristömuuttujat on asetettu ja oikeat volumet on mountattu.
# Tämä tiedosto on tarkoitettu käytettäväksi vain Github Actionseissa

networks:
  harja_net:
    driver: bridge
    # Estetään IPv6 käyttö, jotta testitietokannan migraatioiden ajossa ei tule yhteysongelmia
    enable_ipv6: false

services:
  # Uusin saatavilla oleva testietiekannan konfiguraatio
  harjadb-latest:
    # Hae latest image GitHubin container registrystä
    image: ghcr.io/finnishtransportagency/harja_harjadb:latest

    # Alla saatavilla olevia versioita
    # https://github.com/finnishtransportagency/harja/pkgs/container/harja_harjadb/versions
    #image: ghcr.io/finnishtransportagency/harja_harjadb:15.4-3.3.3 (uusin vakaa)
    #image: ghcr.io/finnishtransportagency/harja_harjadb:15.3-3.3.2
    #image: ghcr.io/finnishtransportagency/harja_harjadb:13.11-3.3.2

    container_name: harjadb
    networks:
      - harja_net
    environment:
      HARJA_TIETOKANTA_PORTTI: 5432
    ports:
      - "127.0.0.1:5432:5432"
    # Estetään IPv6 käyttö, jotta testitietokannan migraatioiden ajossa ei tule yhteysongelmia
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    # Huom: Mountissa viitataan Harja-repon juuressa olevaan tietokanta-hakemistoon, jossa migraatiotiedostot ovat.
    volumes:
      - ../../tietokanta:/var/lib/postgresql/harja/tietokanta
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "harja", "-d", "harja"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 10s

  # Vanhempia testattavia imagen versiota varten on tehty tähän omia compose konfiguraatioita, koska
  # 'latest' imagen versioissa healthcheck, volumet ym. asetukset voivat muuttua.

  harjadb-13.13-3.3.3:
    image: ghcr.io/finnishtransportagency/harja_harjadb:13.13-3.3.3

    container_name: harjadb
    networks:
      - harja_net
    environment:
      HARJA_TIETOKANTA_PORTTI: 5432
    ports:
      - "127.0.0.1:5432:5432"
    # Estetään IPv6 käyttö, jotta testitietokannan migraatioiden ajossa ei tule yhteysongelmia
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    # Huom: Mountissa viitataan Harja-repon juuressa olevaan tietokanta-hakemistoon, jossa migraatiotiedostot ovat.
    volumes:
      - ../../tietokanta:/var/lib/postgresql/harja/tietokanta
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "harja", "-d", "harja" ]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 10s

  # Huom. Uudempi flyway v10 ei toimi enää tässä imagessa
  harjadb-13-3.1:
    image: ghcr.io/finnishtransportagency/harja_harjadb:13-3.1

    container_name: harjadb
    networks:
      - harja_net
    environment:
      HARJA_TIETOKANTA_PORTTI: 5432
    ports:
      - "127.0.0.1:5432:5432"
    # Estetään IPv6 käyttö, jotta testitietokannan migraatioiden ajossa ei tule yhteysongelmia
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    # Huom: Mountissa viitataan Harja-repon juuressa olevaan tietokanta-hakemistoon, jossa migraatiotiedostot ovat.
    volumes:
      - ../../tietokanta:/var/lib/postgresql/harja/tietokanta
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "harja", "-d", "harja" ]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 10s

  activemq-itmf:
    image: ghcr.io/finnishtransportagency/harja_activemq:latest
    # FIXME: Versio 5.15.16 rikkoo integraatiotestit, selvitettävä mistä johtuu
    #image: ghcr.io/finnishtransportagency/harja_activemq:5.15.16
    container_name: activemq-itmf
    networks:
      - harja_net
    environment:
      TZ: "EET"
      TCP_PORT: 61616
      UI_PORT: 8161
    ports:
        - "127.0.0.1:61616:61616" # broker (admin:adminactivemq)(amq:amq)
        - "127.0.0.1:8161:8161"   # web    localhost:8161/admin/queues.jsp (admin:admin)
    # Estetään IPv6 käyttö, jotta testitietokannan migraatioiden ajossa ei tule yhteysongelmia
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    healthcheck:
     # https://stackoverflow.com/questions/52500782/how-to-check-if-activemq-is-working-properly
      test: /opt/activemq/bin/activemq query --objname type=Broker,brokerName=*,service=Health | grep Good
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 10s

  # Uusi ActiveMQ Artemis broker
  activemq-artemis-itmf:
    #image: ghcr.io/finnishtransportagency/harja_activemq_artemis:latest
    # FIXME: Testataan 2.32.0-alpine versiota.
    image: ghcr.io/finnishtransportagency/harja_activemq_artemis:2.32.0-alpine
    container_name: activemq-artemis-itmf
    networks:
      - harja_net
    environment:
      TZ: "EET"
      EXTRA_ARGS: "--http-host 0.0.0.0 --relax-jolokia --default-port 61616 --http-port 8161"
    ports:
      - "127.0.0.1:61616:61616" # broker
      - "127.0.0.1:8161:8161"   # web

    # Estetään IPv6 käyttö, jotta testitietokannan migraatioiden ajossa ei tule yhteysongelmia
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    healthcheck:
      test: /var/lib/artemis-instance/bin/artemis check node --up --user admin --password admin --url "tcp://127.0.0.1:61616" | grep "success"
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 10s
