---
- hosts: all
  roles:
    - role-epel
  sudo: yes
  vars:
    jdk_download_url: http://download.oracle.com/otn-pub/java/jdk/8u60-b27/jdk-8u60-linux-x64.tar.gz
    download_folder: /opt
    java_name: "{{download_folder}}/jdk1.8.0_60"
    java_archive: "{{download_folder}}/jdk-8u60-linux-x64.tar.gz"
  tasks:
    - name: disable selinux
      selinux: state=disabled
    - name: fix hostname
      hostname: name={{harja_hostname}}
    - name: fix hosts
      lineinfile: dest=/etc/hosts line="127.0.0.1 {{harja_hostname}}"
    - name: install nginx repo rpm
      yum:
        name: http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm
    - name: install Postgres repositories
      yum: name=http://yum.postgresql.org/9.5/redhat/rhel-7-x86_64/pgdg-centos95-9.5-2.noarch.rpm state=present
    - name: install wget
      yum: pkg=wget update_cache=yes state=latest
    - name: install git
      yum: pkg=git state=latest
    - name: install psycopg2
      yum: pkg=python-psycopg2.x86_64 state=latest
    - name: install nginx
      yum: pkg=nginx state=latest
    - name: remove old postgresql
      yum: pkg=postgresql94 state=absent
    - name: remove old postgresql server
      yum: pkg=postgresql94-server state=absent
    - name: remove old postgresql contrib
      yum: pkg=postgresql94-contrib state=absent
    - name: remove old postgis
      yum: pkg=postgis2_94.x86_64 state=absent
    - name: install Postgres 9.5
      yum: name=postgresql95
    - name: install postgresql-server 9.5
      yum: pkg=postgresql95-server state=latest
    - name: install postgresql-contrib 9.5
      yum: pkg=postgresql95-contrib state=latest
    - name: install postgis
      yum: pkg=postgis2_95 state=latest
    - name: update geos
      yum: pkg=geos state=latest
    - name: initialize postgres
      shell: /usr/pgsql-9.5/bin/postgresql95-setup initdb
      environment:
        PGSETUP_INITDB_OPTIONS: --encoding=UTF-8 --lc-collate=fi_FI.UTF-8 --lc-ctype=fi_FI.UTF-8
      ignore_errors: yes
    - name: install maven 3
      yum: pkg=maven.noarch state=latest   
    - name: download java 8
      command: "wget -q -O {{java_archive}} --no-cookies --no-check-certificate --header 'Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie' {{jdk_download_url}} creates={{java_archive}}"
    - name: unpack java 8
      command: "tar -xzf {{java_archive}} -C {{download_folder}} creates={{java_name}}"
    - name: fix ownership
      file: state=directory path={{java_name}} owner=root group=root recurse=yes
    - name: update javac alternatives
      alternatives: name=javac link=/usr/bin/javac path={{java_name}}/bin/javac
    - name: update java alternatives
      alternatives: name=java link=/usr/bin/java path={{java_name}}/bin/java
    - name: add Harja user
      user: name=harja
    - name: install Leiningen
      get_url: url=https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein dest=/usr/local/bin mode=0755
    - name: tuhoa temp harja-repo
      file: path=/opt/harja-repo state=absent
    - name: tuhoa temp harja-build
      file: path=/opt/harja-build state=absent
    - name: set up harja-repo directory
      file: state=directory path=/opt/harja-repo owner=harja group=harja
    - name: set up harja-build directory
      file: state=directory path=/opt/harja-build owner=harja group=harja
    - name: initialize git repo if not already initialized
      sudo: yes
      sudo_user: harja
      command: git init --bare
      ignore_errors: yes
      args:
        chdir: "/opt/harja-repo"
    - name: kloonaa repo valmiiksi
      sudo: yes
      sudo_user: harja
      command: git clone /opt/harja-repo
      args:
        chdir: "/opt/harja-build"
    - name: start postgres
      service: name=postgresql-9.5 state=restarted
    - name: set up harja database user
      sudo: yes
      sudo_user: postgres      
      postgresql_user: name=harja password=harja123 role_attr_flags=SUPERUSER
    - name: set up harja database
      sudo: yes
      sudo_user: postgres      
      postgresql_db: name=harja owner=harja encoding='UTF-8' lc_collate='fi_FI.UTF-8' lc_ctype='fi_FI.UTF-8'
    - name: set up postgis for harja database
      sudo: yes
      sudo_user: postgres      
      postgresql_ext: name=postgis db=harja
    - name: configure postgresql.conf
      template: src=templates/postgresql.conf.j2 dest=/var/lib/pgsql/9.5/data/postgresql.conf owner=postgres group=postgres mode=0600
      notify:
        - restart postgres
    - name: configure pg_hba.conf
      template: src=templates/pg_hba.conf.j2 dest=/var/lib/pgsql/9.5/data/pg_hba.conf owner=postgres group=postgres mode=0600
      notify:
        - restart postgres
    - name: upload server key
      copy: src=certs/server.key dest=/etc/nginx/server.key
    - name: upload server certificate
      copy: src=certs/server.crt dest=/etc/nginx/server.crt
    - name: upload certificate authority
      copy: src=certs/ca.crt dest=/etc/nginx/ca.crt
    - name: configure nginx
      template: src=templates/nginx.conf.j2 dest=/etc/nginx/nginx.conf owner=root group=root mode=0644
      notify:
        - restart nginx
    - name: Download ActiveMQ
      get_url: dest=/tmp/activemq.tar.gz url=http://www.apache.org/dyn/closer.cgi?filename=/activemq/5.14.3/apache-activemq-5.14.3-bin.tar.gz&action=download
      register: get_activemq
    - name: Create ActiveMQ directory
      file: state=directory path=/opt/activemq mode=0777
    - name: Extract ActiveMQ
      unarchive: dest=/opt/activemq src=/tmp/activemq.tar.gz copy=no
      when: get_activemq|changed
    - name: Start ActiveMQ
      async: 10
      poll: 0
      command: /opt/activemq/apache-activemq-5.14.3/bin/activemq restart
      args:
        chdir: "/opt/activemq/apache-activemq-5.14.3"
    - name: start nginx
      service: name=nginx state=started
    - name: add HTTPS to iptables IN_public_allow chain
      command: iptables -A IN_public_allow -i eth0 -p tcp --dport 443 -j ACCEPT
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
    - name: restart postgres
      service: name=postgresql-9.5 state=restarted
