-- Kytketään myös vanhat urakat elinvoimakeskukseen, että saadaan ne mukaan elinvoimakeskusten raportteihin
UPDATE urakka SET elinvoimakeskus_id = (select id from organisaatio where lyhenne = 'UUD' and tyyppi = 'elinvoimakeskus')  WHERE elinvoimakeskus_id IS NULL AND hallintayksikko = (select id from organisaatio where lyhenne = 'UUD' and tyyppi = 'hallintayksikko');
UPDATE urakka SET elinvoimakeskus_id = (select id from organisaatio where lyhenne = 'EPO' and tyyppi = 'elinvoimakeskus')  WHERE elinvoimakeskus_id IS NULL AND hallintayksikko = (select id from organisaatio where lyhenne = 'EPO' and tyyppi = 'hallintayksikko');
UPDATE urakka SET elinvoimakeskus_id = (select id from organisaatio where lyhenne = 'KAS' and tyyppi = 'elinvoimakeskus')  WHERE elinvoimakeskus_id IS NULL AND hallintayksikko = (select id from organisaatio where lyhenne = 'KAS' and tyyppi = 'hallintayksikko');
UPDATE urakka SET elinvoimakeskus_id = (select id from organisaatio where lyhenne = 'KES' and tyyppi = 'elinvoimakeskus')  WHERE elinvoimakeskus_id IS NULL AND hallintayksikko = (select id from organisaatio where lyhenne = 'KES' and tyyppi = 'hallintayksikko');
UPDATE urakka SET elinvoimakeskus_id = (select id from organisaatio where lyhenne = 'LAP' and tyyppi = 'elinvoimakeskus')  WHERE elinvoimakeskus_id IS NULL AND hallintayksikko = (select id from organisaatio where lyhenne = 'LAP' and tyyppi = 'hallintayksikko');
UPDATE urakka SET elinvoimakeskus_id = (select id from organisaatio where lyhenne = 'LOU' and tyyppi = 'elinvoimakeskus')  WHERE elinvoimakeskus_id IS NULL AND hallintayksikko = (select id from organisaatio where lyhenne = 'VAR' and tyyppi = 'hallintayksikko');
UPDATE urakka SET elinvoimakeskus_id = (select id from organisaatio where lyhenne = 'SIS' and tyyppi = 'elinvoimakeskus')  WHERE elinvoimakeskus_id IS NULL AND hallintayksikko = (select id from organisaatio where lyhenne = 'PIR' and tyyppi = 'hallintayksikko');
UPDATE urakka SET elinvoimakeskus_id = (select id from organisaatio where lyhenne = 'PSU' and tyyppi = 'elinvoimakeskus')  WHERE elinvoimakeskus_id IS NULL AND hallintayksikko = (select id from organisaatio where lyhenne = 'POP' and tyyppi = 'hallintayksikko');
UPDATE urakka SET elinvoimakeskus_id = (select id from organisaatio where lyhenne = 'ITA' and tyyppi = 'elinvoimakeskus')  WHERE elinvoimakeskus_id IS NULL AND hallintayksikko = (select id from organisaatio where lyhenne = 'POS' and tyyppi = 'hallintayksikko');

UPDATE urakka SET elinvoimakeskus_id = (select id from organisaatio where lyhenne = 'KAN' and tyyppi = 'elinvoimakeskus')  WHERE elinvoimakeskus_id IS NULL AND hallintayksikko = (select id from organisaatio where lyhenne = 'KAN' and tyyppi = 'hallintayksikko');
