-- Lisää Auran materiaalit kiinteäksi osaksi Harjaa
-- Jos materiaali on jo lisätty Harjaan, sitä ei lisätä

-- Testidatassa olleet
INSERT INTO materiaalikoodi (nimi, yksikko, urakkatyyppi, kohdistettava, materiaalityyppi) SELECT 'Talvisuolaliuos NaCl', 't', 'hoito'::urakkatyyppi, false, 'talvisuola'::materiaalityyppi WHERE NOT EXISTS (SELECT nimi FROM materiaalikoodi WHERE nimi = 'Talvisuolaliuos NaCl');
INSERT INTO materiaalikoodi (nimi, yksikko, urakkatyyppi, kohdistettava, materiaalityyppi) SELECT 'Talvisuolaliuos CaCl2', 't', 'hoito'::urakkatyyppi, false, 'talvisuola'::materiaalityyppi WHERE NOT EXISTS (SELECT nimi FROM materiaalikoodi WHERE nimi = 'Talvisuolaliuos CaCl2');
INSERT INTO materiaalikoodi (nimi, yksikko, urakkatyyppi, kohdistettava, materiaalityyppi) SELECT 'Erityisalueet NaCl', 't', 'hoito'::urakkatyyppi, true, 'talvisuola'::materiaalityyppi WHERE NOT EXISTS (SELECT nimi FROM materiaalikoodi WHERE nimi = 'Erityisalueet NaCl');
INSERT INTO materiaalikoodi (nimi, yksikko, urakkatyyppi, kohdistettava, materiaalityyppi) SELECT 'Erityisalueet NaCl-liuos', 't', 'hoito'::urakkatyyppi, true, 'talvisuola'::materiaalityyppi WHERE NOT EXISTS (SELECT nimi FROM materiaalikoodi WHERE nimi = 'Erityisalueet NaCl-liuos');
INSERT INTO materiaalikoodi (nimi, yksikko, urakkatyyppi, kohdistettava, materiaalityyppi) SELECT 'Hiekoitushiekka', 't', 'hoito'::urakkatyyppi, false, 'muu'::materiaalityyppi WHERE NOT EXISTS (SELECT nimi FROM materiaalikoodi WHERE nimi = 'Hiekoitushiekka');
INSERT INTO materiaalikoodi (nimi, yksikko, urakkatyyppi, kohdistettava, materiaalityyppi) SELECT 'Kaliumformiaatti', 't', 'hoito'::urakkatyyppi, false, 'talvisuola'::materiaalityyppi WHERE NOT EXISTS (SELECT nimi FROM materiaalikoodi WHERE nimi = 'Kaliumformiaatti');
-- Puuttuvat
INSERT INTO materiaalikoodi (nimi, yksikko, urakkatyyppi, kohdistettava, materiaalityyppi) SELECT 'Talvisuola', 't', 'hoito'::urakkatyyppi, false, 'talvisuola'::materiaalityyppi WHERE NOT EXISTS (SELECT nimi FROM materiaalikoodi WHERE nimi = 'Talvisuola');
INSERT INTO materiaalikoodi (nimi, yksikko, urakkatyyppi, kohdistettava, materiaalityyppi) SELECT 'Hiekoitushiekan suola', 't', 'hoito'::urakkatyyppi, false, 'talvisuola'::materiaalityyppi WHERE NOT EXISTS (SELECT nimi FROM materiaalikoodi WHERE nimi = 'Hiekoitushiekan suola');;
INSERT INTO materiaalikoodi (nimi, yksikko, urakkatyyppi, kohdistettava, materiaalityyppi) SELECT 'Rikkaruohojen torjunta-aineet', 'l', 'hoito'::urakkatyyppi, false, 'muu'::materiaalityyppi WHERE NOT EXISTS (SELECT nimi FROM materiaalikoodi WHERE nimi = 'Rikkaruohojen torjunta-aineet');
INSERT INTO materiaalikoodi (nimi, yksikko, urakkatyyppi, kohdistettava, materiaalityyppi) SELECT 'Kesäsuola (sorateiden kevätkunnostus)', 't', 'hoito'::urakkatyyppi, false, 'muu'::materiaalityyppi WHERE NOT EXISTS (SELECT nimi FROM materiaalikoodi WHERE nimi = 'Kesäsuola (sorateiden kevätkunnostus)');
INSERT INTO materiaalikoodi (nimi, yksikko, urakkatyyppi, kohdistettava, materiaalityyppi) SELECT 'Kesäsuola (pölynsidonta)', 't', 'hoito'::urakkatyyppi, false, 'muu'::materiaalityyppi WHERE NOT EXISTS (SELECT nimi FROM materiaalikoodi WHERE nimi = 'Kesäsuola (pölynsidonta)');
INSERT INTO materiaalikoodi (nimi, yksikko, urakkatyyppi, kohdistettava, materiaalityyppi) SELECT 'Murskeet', 't', 'hoito'::urakkatyyppi, false, 'muu'::materiaalityyppi WHERE NOT EXISTS (SELECT nimi FROM materiaalikoodi WHERE nimi = 'Murskeet');
INSERT INTO materiaalikoodi (nimi, yksikko, urakkatyyppi, kohdistettava, materiaalityyppi) SELECT 'Jätteet kaatopaikalle', 't', 'hoito'::urakkatyyppi, false, 'muu'::materiaalityyppi WHERE NOT EXISTS (SELECT nimi FROM materiaalikoodi WHERE nimi = 'Jätteet kaatopaikalle');