ALTER TYPE REIMARI_URAKOITSIJA RENAME ATTRIBUTE id TO "r-id";
ALTER TYPE REIMARI_URAKOITSIJA RENAME ATTRIBUTE nimi TO "r-nimi";
ALTER TYPE REIMARI_SOPIMUS RENAME ATTRIBUTE nro TO "r-nro";
ALTER TYPE REIMARI_SOPIMUS RENAME ATTRIBUTE tyyppi TO "r-tyyppi";
ALTER TYPE REIMARI_SOPIMUS RENAME ATTRIBUTE nimi TO "r-nimi";
ALTER TYPE REIMARI_TURVALAITE RENAME ATTRIBUTE nro TO "r-nro";
ALTER TYPE REIMARI_TURVALAITE RENAME ATTRIBUTE nimi TO "r-nimi";
ALTER TYPE REIMARI_TURVALAITE RENAME ATTRIBUTE ryhma TO "r-ryhma";
ALTER TYPE REIMARI_ALUS RENAME ATTRIBUTE tunnus TO "r-tunnus";
ALTER TYPE REIMARI_ALUS RENAME ATTRIBUTE nimi TO "r-nimi";
ALTER TYPE REIMARI_VAYLA RENAME ATTRIBUTE nro TO "r-nro";
ALTER TYPE REIMARI_VAYLA RENAME ATTRIBUTE nimi TO "r-nimi";
ALTER TYPE REIMARI_VAYLA RENAME ATTRIBUTE ryhma TO "r-ryhma";

ALTER TABLE vv_vikailmoitus DROP COLUMN "toteuma-id";
ALTER TABLE vv_vikailmoitus ADD COLUMN "toimenpide-id" INTEGER REFERENCES reimari_toimenpide(id);