CREATE TABLE kan_huoltokohde (
  id SERIAL PRIMARY KEY,
  nimi TEXT NOT NULL
);

INSERT INTO kan_huoltokohde (nimi) VALUES ('ALAKANAVA');
INSERT INTO kan_huoltokohde (nimi) VALUES ('ALAKANAVA');
INSERT INTO kan_huoltokohde (nimi) VALUES ('ALAPORTTI');
INSERT INTO kan_huoltokohde (nimi) VALUES ('ALASATAMA');
INSERT INTO kan_huoltokohde (nimi) VALUES ('ASENNONMITTAUSLAITTEET');
INSERT INTO kan_huoltokohde (nimi) VALUES ('ATK-VERKKO');
INSERT INTO kan_huoltokohde (nimi) VALUES ('HYDRAULIIKKA');
INSERT INTO kan_huoltokohde (nimi) VALUES ('JALKA- JA KAULALAAKERIT');
INSERT INTO kan_huoltokohde (nimi) VALUES ('KUULUTUSLAITTEET');
INSERT INTO kan_huoltokohde (nimi) VALUES ('LAITURI');
INSERT INTO kan_huoltokohde (nimi) VALUES ('LAPPO');
INSERT INTO kan_huoltokohde (nimi) VALUES ('LIIKKUVAT POLLARIT');
INSERT INTO kan_huoltokohde (nimi) VALUES ('LOGIIKKAJÄRJESTELMÄT');
INSERT INTO kan_huoltokohde (nimi) VALUES ('LUUKKUKONEISTOT');
INSERT INTO kan_huoltokohde (nimi) VALUES ('LÄMMITYKSET');
INSERT INTO kan_huoltokohde (nimi) VALUES ('MUSEOKANAVA KUIVATAIPALE');
INSERT INTO kan_huoltokohde (nimi) VALUES ('MUSEOKANAVA SAARIKOSKI');
INSERT INTO kan_huoltokohde (nimi) VALUES ('MUUNTOASEMAT');
INSERT INTO kan_huoltokohde (nimi) VALUES ('MUUT');
INSERT INTO kan_huoltokohde (nimi) VALUES ('NIPUN SIIRTOLAITTEET');
INSERT INTO kan_huoltokohde (nimi) VALUES ('OHJAUSLAITTEET');
INSERT INTO kan_huoltokohde (nimi) VALUES ('OHJAUSPÄÄTE');
INSERT INTO kan_huoltokohde (nimi) VALUES ('OHJAUSTIETOKONE');
INSERT INTO kan_huoltokohde (nimi) VALUES ('PAINEILMALAITTEET');
INSERT INTO kan_huoltokohde (nimi) VALUES ('PINNANMITTAUSLAITTEET');
INSERT INTO kan_huoltokohde (nimi) VALUES ('PORTTIKONEISTOT');
INSERT INTO kan_huoltokohde (nimi) VALUES ('PUHELINVERKKO');
INSERT INTO kan_huoltokohde (nimi) VALUES ('PUMPPAAMO');
INSERT INTO kan_huoltokohde (nimi) VALUES ('PUMPPAAMO MARTTILA');
INSERT INTO kan_huoltokohde (nimi) VALUES ('PUMPPAAMO PELKOLA');
INSERT INTO kan_huoltokohde (nimi) VALUES ('RAKENNUKSET');
INSERT INTO kan_huoltokohde (nimi) VALUES ('REUNAVALOT JA LOISTOT');
INSERT INTO kan_huoltokohde (nimi) VALUES ('SILTAKELLARI');
INSERT INTO kan_huoltokohde (nimi) VALUES ('SILTAKONEISTO');
INSERT INTO kan_huoltokohde (nimi) VALUES ('SILTALAITTEET');
INSERT INTO kan_huoltokohde (nimi) VALUES ('SILTARAKENTEET');
INSERT INTO kan_huoltokohde (nimi) VALUES ('SULKU- JA LAITURIRAKENTEET');
INSERT INTO kan_huoltokohde (nimi) VALUES ('SULKULAITTEET');
INSERT INTO kan_huoltokohde (nimi) VALUES ('SULKURAKENTEET');
INSERT INTO kan_huoltokohde (nimi) VALUES ('SUOJAPARRUT JA -LANKUT');
INSERT INTO kan_huoltokohde (nimi) VALUES ('SÄHKÖLAITTEET');
INSERT INTO kan_huoltokohde (nimi) VALUES ('SÄHKÖNJAKELU');
INSERT INTO kan_huoltokohde (nimi) VALUES ('SÄÄNNÖSTELYPATO JYRKILÄ');
INSERT INTO kan_huoltokohde (nimi) VALUES ('SÄÄNNÖSTELYPATO SUIKKI');
INSERT INTO kan_huoltokohde (nimi) VALUES ('KONETARKASTUSLISTAN MUKAISET');
INSERT INTO kan_huoltokohde (nimi) VALUES ('SÄHKÖTARKASTUSLISTAN MUKAISET');
INSERT INTO kan_huoltokohde (nimi) VALUES ('TELELAITTEET');
INSERT INTO kan_huoltokohde (nimi) VALUES ('TIEDONSIIRTOLAITTEET');
INSERT INTO kan_huoltokohde (nimi) VALUES ('TIELAITOS');
INSERT INTO kan_huoltokohde (nimi) VALUES ('TIELIIKENNEOPASTEET');
INSERT INTO kan_huoltokohde (nimi) VALUES ('TIELIIKENNEPUOMIT');
INSERT INTO kan_huoltokohde (nimi) VALUES ('TIET');
INSERT INTO kan_huoltokohde (nimi) VALUES ('TULVAPUOMI/VÄLPPÄ');
INSERT INTO kan_huoltokohde (nimi) VALUES ('TURVA-AIDAT');
INSERT INTO kan_huoltokohde (nimi) VALUES ('TURVAPATO LAURITSALA');
INSERT INTO kan_huoltokohde (nimi) VALUES ('TURVAPATO NUIJAMAA');
INSERT INTO kan_huoltokohde (nimi) VALUES ('TURVAPATO TORPANKAPEA');
INSERT INTO kan_huoltokohde (nimi) VALUES ('TURVAVAIJERIT JA -KISKOT');
INSERT INTO kan_huoltokohde (nimi) VALUES ('VALVONTAKAMERAT');
INSERT INTO kan_huoltokohde (nimi) VALUES ('VARAVOIMAKONE');
INSERT INTO kan_huoltokohde (nimi) VALUES ('VESILIIKENNEOPASTIMET');
INSERT INTO kan_huoltokohde (nimi) VALUES ('VHF');
INSERT INTO kan_huoltokohde (nimi) VALUES ('YLÄKANAVA');
INSERT INTO kan_huoltokohde (nimi) VALUES ('YLÄPORTTI');
INSERT INTO kan_huoltokohde (nimi) VALUES ('YMPÄRISTÖNHOITO');
