UPDATE tehtavaryhma SET nimi = 'Talvihoito (A)' WHERE nimi = 'TALVIHOITO (A)';
UPDATE tehtavaryhma SET nimi = 'Talvisuola (B1)' WHERE nimi = 'TALVISUOLA (B1)';
UPDATE tehtavaryhma SET nimi = 'KFo, NaFo (B2)' WHERE nimi = 'KFO,NAFO (B2)';
UPDATE tehtavaryhma SET nimi = 'Hiekoitus (B3)' WHERE nimi = 'HIEKOITUS (B3)';
UPDATE tehtavaryhma SET nimi = 'Liikennemerkit ja liikenteenohjauslaitteet (L)' WHERE nimi = 'LIIKENNEMERKIT JA LIIKENTEENOHJAUSLAITTEET (L)';
UPDATE tehtavaryhma SET nimi = 'Puhtaanapito (P)' WHERE nimi = 'PUHTAANAPITO (P)';
UPDATE tehtavaryhma SET nimi = 'Vesakonraivaukset ja puun poisto (V)' WHERE nimi = 'VESAKONRAIVAUKSET JA PUUN POISTO (V)';
UPDATE tehtavaryhma SET nimi = 'Nurmetukset ja muut vihertyöt (N)' WHERE nimi = 'NURMETUKSET JA MUUT VIHERTYÖT (N)';
UPDATE tehtavaryhma SET nimi = 'Kuivatusjärjestelmät (K)' WHERE nimi = 'KUIVATUSJÄRJESTELMÄT (K)';
UPDATE tehtavaryhma SET nimi = 'Rummut, päällystetiet (R)' WHERE nimi = 'RUMMUT, PÄÄLLYSTETIET (R)';
UPDATE tehtavaryhma SET nimi = 'Rummut, soratiet (S)' WHERE nimi = 'RUMMUT, SORATIET (S)';
UPDATE tehtavaryhma SET nimi = 'Kaiteet, aidat ja kiveykset (U)' WHERE nimi = 'KAITEET, AIDAT JA KIVEYKSET (U)';
UPDATE tehtavaryhma SET nimi = 'Kuumapäällyste (Y1)' WHERE nimi = 'KUUMAPÄÄLLYSTE (Y1)';
UPDATE tehtavaryhma SET nimi = 'Kylmäpäällyste (Y2)' WHERE nimi = 'KYLMÄPÄÄLLYSTE (Y2)';
UPDATE tehtavaryhma SET nimi = 'Puhallus-SIP (Y3)' WHERE nimi = 'PUHALLUS-SIP (Y3)';
UPDATE tehtavaryhma SET nimi = 'Saumojen juottaminen bitumilla (Y4)' WHERE nimi = 'SAUMOJEN JUOTTAMINEN BITUMILLA (Y4)';
UPDATE tehtavaryhma SET nimi = 'Massasaumaus (Y5)' WHERE nimi = 'MASSASAUMAUS (Y5)';
UPDATE tehtavaryhma SET nimi = 'KT-valu (Y6)' WHERE nimi = 'KT-VALU (Y6)';
UPDATE tehtavaryhma SET nimi = 'Valu (Y7)' WHERE nimi = 'VALU (Y7)';
UPDATE tehtavaryhma SET nimi = 'Siltapäällysteet (H)' WHERE nimi = 'SILTAPÄÄLLYSTEET (H)';
UPDATE tehtavaryhma SET nimi = 'Sorapientareet (O)' WHERE nimi = 'SORAPIENTAREET (O)';
UPDATE tehtavaryhma SET nimi = 'Sillat ja laiturit (I)' WHERE nimi = 'SILLAT JA LAITURIT (I)';
UPDATE tehtavaryhma SET nimi = 'Sorateiden hoito (C)' WHERE nimi = 'SORATEIDEN HOITO (C)';
UPDATE tehtavaryhma SET nimi = 'Kesäsuola, materiaali (D)' WHERE nimi = 'KESÄSUOLA, MATERIAALI (D)';
UPDATE tehtavaryhma SET nimi = 'Sorastus (M)' WHERE nimi = 'SORASTUS (M)';
UPDATE tehtavaryhma SET nimi = 'Äkilliset hoitotyöt, Talvihoito (T1)' WHERE nimi = 'ÄKILLISET HOITOTYÖT, TALVIHOITO (T1)';
UPDATE tehtavaryhma SET nimi = 'Äkilliset hoitotyöt, Liikenneympäristön hoito (T1)' WHERE nimi = 'ÄKILLISET HOITOTYÖT, LIIKENNEYMPÄRISTÖN HOITO (T1)';
UPDATE tehtavaryhma SET nimi = 'Äkilliset hoitotyöt, Soratiet (T1)' WHERE nimi = 'ÄKILLISET HOITOTYÖT, SORATIET (T1)';
UPDATE tehtavaryhma SET nimi = 'Vahinkojen korjaukset, Talvihoito (T2)' WHERE nimi = 'VAHINKOJEN KORJAUKSET, TALVIHOITO (T2)';
UPDATE tehtavaryhma SET nimi = 'Vahinkojen korjaukset, Liikenneympäristön hoito (T2)' WHERE nimi = 'VAHINKOJEN KORJAUKSET, LIIKENNEYMPÄRISTÖN HOITO (T2)';
UPDATE tehtavaryhma SET nimi = 'Vahinkojen korjaukset, Soratiet (T2)' WHERE nimi = 'VAHINKOJEN KORJAUKSET, SORATIET (T2)';
UPDATE tehtavaryhma SET nimi = 'Tilaajan rahavaraus (T3)' WHERE nimi = 'TILAAJAN RAHAVARAUS (T3)';
UPDATE tehtavaryhma SET nimi = 'Avo-ojitus, päällystetyt tiet (X)' WHERE nimi = 'AVO-OJITUS, PÄÄLLYSTETYT TIET (X)';
UPDATE tehtavaryhma SET nimi = 'Avo-ojitus, soratiet (Z)' WHERE nimi = 'AVO-OJITUS, SORATIET (Z)';
UPDATE tehtavaryhma SET nimi = 'RKR-korjaus (Q)' WHERE nimi = 'RKR-KORJAUS (Q)';
UPDATE tehtavaryhma SET nimi = 'Muut (F)' WHERE nimi = 'MUUT (F)';
UPDATE tehtavaryhma SET nimi = 'ELY-rahoitteiset (E)' WHERE nimi = 'ELY-RAHOITTEISET (E)';
UPDATE tehtavaryhma SET nimi = 'Johto- ja hallintokorvaus (J)' WHERE nimi = 'JOHTO- JA HALLINTOKORVAUS (J)';
UPDATE tehtavaryhma SET nimi = 'Hoidonjohtopalkkio (G)' WHERE nimi = 'HOIDONJOHTOPALKKIO (G)';
UPDATE tehtavaryhma SET nimi = 'Erillishankinnat (W' WHERE nimi = 'ERILLISHANKINNAT (W)';

