-- Korjaa Saimaan kanavan sulkujen oletuspalvelumuodoksi KAUKO
UPDATE kan_kohteenosa set oletuspalvelumuoto = 				'itse'	where nimi = 		'Herraskosken kanavan vanha silta';
UPDATE kan_kohteenosa set oletuspalvelumuoto = 				'muu' where nimi = 		'Hietalahden kääntösilta';
UPDATE kan_kohteenosa set oletuspalvelumuoto = 				'kauko' where nimi = 		'Itikan silta';
UPDATE kan_kohteenosa set oletuspalvelumuoto = 				'kauko' where nimi = 		'Joensuun kanavasilta';
UPDATE kan_kohteenosa set oletuspalvelumuoto = 				'kauko' where nimi = 		'Juustilan läppäsilta';
UPDATE kan_kohteenosa set oletuspalvelumuoto = 				'muu' where nimi = 		'Jännevirran silta';
UPDATE kan_kohteenosa set oletuspalvelumuoto = 				'kauko' where nimi = 		'Kaltimonkosken silta';
UPDATE kan_kohteenosa set oletuspalvelumuoto = 				'kauko' where nimi = 		'Kansolan läppäsilta';
UPDATE kan_kohteenosa set oletuspalvelumuoto = 				'kauko' where nimi = 		'Kellosalmen silta';
UPDATE kan_kohteenosa set oletuspalvelumuoto = 				'itse' where nimi = 		'Kerman kanavan kääntösilta';
UPDATE kan_kohteenosa set oletuspalvelumuoto = 				'muu' where nimi = 		'Killingholman silta';
UPDATE kan_kohteenosa set oletuspalvelumuoto = 				'kauko' where nimi = 		'Kuurnan kanavan läppäsilta';
UPDATE kan_kohteenosa set oletuspalvelumuoto = 				'paikallis' where nimi = 		'Kyrönsalmen eteläinen silta';
UPDATE kan_kohteenosa set oletuspalvelumuoto = 				'paikallis' where nimi = 		'Kyrönsalmen pohjoinen silta';
UPDATE kan_kohteenosa set oletuspalvelumuoto = 				'paikallis' where nimi = 		'Kyrönsalmen ratasilta';
UPDATE kan_kohteenosa set oletuspalvelumuoto = 				'paikallis' where nimi = 		'Kyrönsalmen silta';
UPDATE kan_kohteenosa set oletuspalvelumuoto = 				'muu' where nimi = 		'Lapinsalmen ratasilta';
UPDATE kan_kohteenosa set oletuspalvelumuoto = 				'muu' where nimi = 		'Lieksanjoen ratasilta';
UPDATE kan_kohteenosa set oletuspalvelumuoto = 				'kauko' where nimi = 		'Lillholmenin silta';
UPDATE kan_kohteenosa set oletuspalvelumuoto = 				'paikallis' where nimi = 		'Muroleen kanavan kääntösilta';
UPDATE kan_kohteenosa set oletuspalvelumuoto = 				'kauko' where nimi = 		'Mustolan silta';
UPDATE kan_kohteenosa set oletuspalvelumuoto = 				'itse' where nimi = 		'Nerkoon kanavan silta';
UPDATE kan_kohteenosa set oletuspalvelumuoto = 				'kauko' where nimi = 		'Pirtinvirran ratasilta (Varkauden kääntösilta)';
UPDATE kan_kohteenosa set oletuspalvelumuoto = 				'paikallis' where nimi = 		'Pohjan ratasilta, läntinen salmi';
UPDATE kan_kohteenosa set oletuspalvelumuoto = 				'muu' where nimi = 		'Päivärannan läppäsilta';
UPDATE kan_kohteenosa set oletuspalvelumuoto = 				'muu' where nimi = 		'Päivärannan läppäsilta';
UPDATE kan_kohteenosa set oletuspalvelumuoto = 				'muu' where nimi = 		'Päivärannan läppäsilta';
UPDATE kan_kohteenosa set oletuspalvelumuoto = 				'kauko' where nimi = 		'Pällin läppäsilta';
UPDATE kan_kohteenosa set oletuspalvelumuoto = 				'paikallis' where nimi = 		'Reposaaren silta';
UPDATE kan_kohteenosa set oletuspalvelumuoto = 				'kauko' where nimi = 		'Rättijärven läppäsilta';
UPDATE kan_kohteenosa set oletuspalvelumuoto = 				'kauko' where nimi = 		'Soskuan läppäsilta';
UPDATE kan_kohteenosa set oletuspalvelumuoto = 				'muu' where nimi = 		'Strömman kääntösilta';
UPDATE kan_kohteenosa set oletuspalvelumuoto = 				'kauko' where nimi = 		'Strömman läppäsilta';
UPDATE kan_kohteenosa set oletuspalvelumuoto = 				'muu' where nimi = 		'Suvantolan ponttoonisilta';
UPDATE kan_kohteenosa set oletuspalvelumuoto = 				'kauko' where nimi = 		'Särkijärven läppäsilta';
UPDATE kan_kohteenosa set oletuspalvelumuoto = 				'paikallis' where nimi = 		'Tahkoluodon ratasilta';
UPDATE kan_kohteenosa set oletuspalvelumuoto = 				'paikallis' where nimi = 		'Taipaleen kanavan läppäsilta I';
UPDATE kan_kohteenosa set oletuspalvelumuoto = 				'paikallis' where nimi = 		'Taipaleen kanavan ratasilta';
UPDATE kan_kohteenosa set oletuspalvelumuoto = 				'itse' where nimi = 		'Taivallahden kanavan kääntösilta';
UPDATE kan_kohteenosa set oletuspalvelumuoto = 				'muu' where nimi = 		'Tarvonsalmen ponttonisilta';
UPDATE kan_kohteenosa set oletuspalvelumuoto = 				'kauko' where nimi = 		'Tikkalansaaren nostosilta';
UPDATE kan_kohteenosa set oletuspalvelumuoto = 				'muu' where nimi = 		'Tornionjoen ratasilta';
UPDATE kan_kohteenosa set oletuspalvelumuoto = 				'kauko' where nimi = 		'Uimasalmen ratasilta';
UPDATE kan_kohteenosa set oletuspalvelumuoto = 				'kauko' where nimi = 		'Uimasalmen silta';
UPDATE kan_kohteenosa set oletuspalvelumuoto = 				'paikallis' where nimi = 		'Varistaipaleen kanavan kääntösilta';
UPDATE kan_kohteenosa set oletuspalvelumuoto = 				'kauko' where nimi = 		'Vihtakannan silta';
UPDATE kan_kohteenosa set oletuspalvelumuoto = 				'kauko' where nimi = 		'Virtasalmen silta';
UPDATE kan_kohteenosa set oletuspalvelumuoto = 				'kauko' where nimi = 		'Visuveden silta';
UPDATE kan_kohteenosa set oletuspalvelumuoto = 				'paikallis' where nimi = 		'Vääksyn kanavan silta';

