INSERT INTO koodisto_konversio (id, nimi, kuvaus)
VALUES ('v/vtlmln', 'velho/liikennemerkki-lakinumero', 'Varustetoteumien liikennemerkkien lisätietojen konversio, lakinumero');

INSERT INTO koodisto_konversio_koodit (koodisto_konversio_id, lahde, tulos)
VALUES ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro1', 'Mutka oikealle'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro2', 'Mutka vasemmalle'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro3', 'Mutkia, joista ensimmäinen oikealle'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro4', 'Mutkia, joista ensimmäinen vasemmalle'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro5', 'Jyrkkä ylämäki'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro6', 'Jyrkkä alamäki'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro7', 'Kapeneva tie'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro8', 'Kaksisuuntainen liikenne'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro9', 'Avattava silta'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro10', 'Lautta, laituri tai ranta'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro11', 'Liikenneruuhka'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro12', 'Epätasainen tie'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro13', 'Töyssyjä'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro14', 'Tietyö'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro15', 'Irtokiviä'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro16', 'Liukas ajorata'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro17', 'Vaarallinen tien reuna'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro18', 'Suojatien ennakkovaroitus'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro19', 'Jalankulkijoita'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro20', 'Lapsia'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro21', 'Pyöräilijöitä'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro22', 'Hiihtolatu'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro23', 'Hirvi'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro24', 'Poro'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro25', 'Kauriseläin'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro26', 'Tienristeys'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro27', 'Sivutien risteys molemmin puolin'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro28', 'Sivutien risteys porrastetusti ensimmäinen vasemmalle'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro29', 'Sivutien risteys porrastetusti ensimmäinen oikealle'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro30', 'Sivutien risteys vasemmalle'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro31', 'Sivutien risteys oikealle'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro32', 'Sivutien risteys oikealle alaviistoon'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro33', 'Sivutien risteys vasemmalle alaviistoon'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro34', 'Sivutien risteys oikealle yläviistoon'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro35', 'Sivutien risteys vasemmalle yläviistoon'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro36', 'Liikennevalot'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro37', 'Liikenneympyrä'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro38', 'Raitiovaunu'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro39', 'Rautatien tasoristeys ilman puomeja'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro40', 'Rautatien tasoristeys, jossa on puomit'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro41', 'Rautatien tasoristeyksen lähestymismerkki, vasen 3 raitaa'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro42', 'Rautatien tasoristeyksen lähestymismerkki, oikea 3 raitaa'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro43', 'Rautatien tasoristeyksen lähestymismerkki, vasen 2 raitaa'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro44', 'Rautatien tasoristeyksen lähestymismerkki, oikea 2 raitaa'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro45', 'Rautatien tasoristeyksen lähestymismerkki, vasen 1 raita'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro46', 'Rautatien tasoristeyksen lähestymismerkki, oikea 1 raita'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro47', 'Yksiraiteisen rautatien tasoristeys'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro48', 'Kaksi tai useampiraiteisen rautatien tasoristeys'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro49', 'Putoavia kiviä'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro50', 'Matalalla lentäviä lentokoneita'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro51', 'Sivutuuli'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro52', 'Muu vaara'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro53', 'Etuajo-oikeutettu tie'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro54', 'Etuajo-oikeuden päättyminen'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro55', 'Etuajo-oikeus kohdattaessa'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro56', 'Väistämisvelvollisuus kohdattaessa'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro57', 'Väistämisvelvollisuus risteyksessä'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro58', 'Pakollinen pysäyttäminen'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro59', 'Väistämisvelvollisuus pyöräilijän tienylityspaikassa'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro60', 'Ajoneuvolla ajo kielletty'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro61', 'Moottorikäyttöisellä ajoneuvolla ajo kielletty'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro62', 'Kuorma- ja pakettiautolla ajo kielletty'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro63', 'Ajoneuvoyhdistelmällä ajo kielletty'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro64', 'Traktorilla ajo kielletty'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro65', 'Moottoripyörällä ajo kielletty'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro66', 'Moottorikelkalla ajo kielletty'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro67', 'Vaarallisten aineiden kuljetus kielletty'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro68', 'Linja-autolla ajo kielletty'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro69', 'Mopolla ajo kielletty'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro70', 'Polkupyörällä ajo kielletty'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro71', 'Polkupyörällä ja mopolla ajo kielletty'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro72', 'Jalankulku kielletty'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro73', 'Jalankulku ja polkupyörällä ajo kielletty'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro74', 'Jalankulku ja polkupyörällä ja mopolla ajo kielletty'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro75', 'Ratsastus kielletty'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro76', 'Kielletty ajosuunta'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro77', 'Vasemmalle kääntyminen kielletty'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro78', 'Oikealle kääntyminen kielletty'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro79', 'U-käännös kielletty'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro80', 'Ajoneuvon suurin sallittu leveys'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro81', 'Ajoneuvon suurin sallittu korkeus'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro82', 'Ajoneuvon tai ajoneuvoyhdistelmän suurin sallittu pituus'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro83', 'Ajoneuvon suurin sallittu massa'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro84', 'Ajoneuvoyhdistelmän suurin sallittu massa'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro85', 'Ajoneuvon suurin sallittu akselille kohdistuva massa'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro86', 'Ajoneuvon suurin sallittu telille kohdistuva massa'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro87', 'Ohituskielto'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro88', 'Ohituskielto päättyy'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro89', 'Ohituskielto kuorma-autolla'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro90', 'Ohituskielto kuorma-autolla päättyy'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro91', 'Nopeusrajoitus'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro92', 'Nopeusrajoitus päättyy'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro93', 'Nopeusrajoitusalue'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro94', 'Nopeusrajoitusalue päättyy'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro95', 'Ajokaistakohtainen kielto, rajoitus tai määräys'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro96', 'Pysäyttäminen kielletty'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro97', 'Pysäköinti kielletty'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro98', 'Pysäköintikieltoalue'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro99', 'Pysäköintikieltoalue päättyy'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro100', 'Taksiasema-alue'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro101', 'Taksin pysäyttämispaikka'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro102', 'Kuormauspaikka'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro103', 'Vuoropysäköinti (kielletty parittomina päivinä)'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro104', 'Vuoropysäköinti (kielletty parillisina päivinä)'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro105', 'Pakollinen pysäyttäminen tullitarkastusta varten Suomi-Venäjä'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro106', 'Pakollinen pysäyttäminen tullitarkastusta varten Suomi-Ruotsi'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro107', 'Pakollinen pysäyttäminen tullitarkastusta varten Suomi-Norja'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro108', 'Pakollinen pysäyttäminen tarkastusta varten - Poliisi'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro109', 'Pakollinen pysäyttäminen tarkastusta varten - Rajatarkastus'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro110', 'Pakollinen pysäyttäminen tarkastusta varten - Rajatarkastus Ruotsi'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro111', 'Pakollinen pysäyttäminen tarkastusta varten - Rajatarkastus Norja'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro112', 'Pakollinen pysäyttäminen tarkastusta varten - Rajatarkastus Venäjä'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro113', 'Moottorikäyttöisten ajoneuvojen vähimmäisetäisyys'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro114', 'Nastarenkailla varustetulla moottorikäyttöisellä ajoneuvolla ajo kielletty'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro115', 'Pakollinen ajosuunta oikealle'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro116', 'Pakollinen ajosuunta vasemmalle'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro117', 'Pakollinen ajosuunta suoraan'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro118', 'Pakollinen ajosuunta kääntyminen oikealle'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro119', 'Pakollinen ajosuunta kääntyminen oikealle yläviistoon'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro120', 'Pakollinen ajosuunta kääntyminen oikealle alaviistoon'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro121', 'Pakollinen ajosuunta kääntyminen vasemmalle'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro122', 'Pakollinen ajosuunta kääntyminen vasemmalle yläviistoon'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro123', 'Pakollinen ajosuunta kääntyminen vasemmalle alaviistoon'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro124', 'Pakollinen ajosuunta suoraan tai kääntyminen oikealle'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro125', 'Pakollinen ajosuunta suoraan tai kääntyminen oikealle yläviistoon'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro126', 'Pakollinen ajosuunta suoraan tai kääntyminen oikealle alaviistoon'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro127', 'Pakollinen ajosuunta suoraan tai kääntyminen vasemmalle'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro128', 'Pakollinen ajosuunta suoraan tai kääntyminen vasemmalle yläviistoon'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro129', 'Pakollinen ajosuunta suoraan tai kääntyminen vasemmalle alaviistoon'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro130', 'Pakollinen ajosuunta kääntyminen oikealle tai vasemmalle'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro131', 'Pakollinen ajosuunta suoraan tai kääntyminen oikealle tai vasemmalle'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro132', 'Pakollinen kiertosuunta'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro133', 'Liikenteenjakaja oikea'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro134', 'Liikenteenjakaja vasen'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro135', 'Liikenteenjakaja molemmin puolin'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro136', 'Jalkakäytävä'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro137', 'Pyörätie'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro138', 'Yhdistetty pyörätie ja jalkakäytävä'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro139', 'Pyörätie ja jalkakäytävä rinnakkain, pyörätie vasemmalla'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro140', 'Pyörätie ja jalkakäytävä rinnakkain, pyörätie oikealla'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro141', 'Moottorikelkkailureitti'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro142', 'Ratsastustie'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro143', 'Vähimmäisnopeus'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro144', 'Vähimmäisnopeus päättyy'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro145', 'Suojatie'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro146', 'Pysäköintipaikka'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro147', 'Liityntäpysäköintipaikka juna'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro148', 'Liityntäpysäköintipaikka bussi'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro149', 'Liityntäpysäköintipaikka metro'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro150', 'Liityntäpysäköintipaikka useita joukkoliikennevälineitä'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro151', 'Ajoneuvojen sijoitus pysäköintipaikalla suoraan'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro152', 'Ajoneuvojen sijoitus pysäköintipaikalla vastakkain'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro153', 'Ajoneuvojen sijoitus pysäköintipaikalla vinoon'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro154', 'Kohtaamispaikka'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro155', 'Linja-autopysäkki'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro156', 'Raitiovaunupysäkki'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro157', 'Taksiasema'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro158', 'Linja-autokaista'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro159', 'Linja-auto ja taksikaista'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro160', 'Linja-autokaista päättyy'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro161', 'Linja-auto ja taksikaista päättyy'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro162', 'Raitiovaunukaista'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro163', 'Raitiovaunu- ja taksikaista'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro164', 'Raitiovaunukaista päättyy'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro165', 'Raitiovaunu- ja taksikaista päättyy'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro166', 'Pyöräkaista oikealla'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro167', 'Pyöräkaista keskellä'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro168', 'Yksisuuntainen tie suoraan'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro169', 'Yksisuuntainen tie oikealle/vasemmalle'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro170', 'Moottoritie'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro171', 'Moottoritie päättyy'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro172', 'Moottoriliikennetie'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro173', 'Moottoriliikennetie päättyy'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro174', 'Tunneli'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro175', 'Tunneli päättyy'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro176', 'Hätäpysäyttämispaikka'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro177', 'Taajama'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro178', 'Taajama päättyy'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro179', 'Pihakatu'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro180', 'Pihakatu päättyy'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro181', 'Kävelykatu'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro182', 'Kävelykatu päättyy'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro183', 'Pyöräkatu'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro184', 'Pyöräkatu päättyy'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro185', 'Ajokaistojen yhdistymien'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro186', 'Suunnistustaulu'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro187', 'Suunnistustaulu'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro188', 'Suunnistustaulu'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro189', 'Suunnistustaulu'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro190', 'Suunnistustaulu'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro191', 'Suunnistustaulu'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro192', 'Ajokaistakohtainen suunnistustaulu'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro193', 'Kiertotien suunnistustaulu (sininen pohja)'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro194', 'Kiertotien suunnistustaulu (keltainen pohja)'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro195', 'Kiertotieopastus'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro196', 'Ajoreittiopastus'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro197', 'Ajokaistaopastus'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro198', 'Ajokaistaopastus'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro199', 'Ajokaistaopastus'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro200', 'Ajokaistaopastus'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro201', 'Ajokaistaopastus'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro202', 'Ajokaistaopastus'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro203', 'Ajokaistan päättyminen'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro204', 'Ajokaistan päättyminen'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro205', 'Viitoituksen koontimerkki'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro206', 'Ajokaistan yläpuolinen viitta'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro207', 'Ajokaistan yläpuolinen viitta'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro208', 'Ajokaistan yläpuolinen erkanemisviitta'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro209', 'Tienviitta'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro210', 'Erkanemisviitta'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro211', 'Kiertotien viitta'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro212', 'Osoiteviitta'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro213', 'Osoiteviitan ennakkomerkki'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro214', 'Liityntäpysäköintiviitta juna'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro215', 'Liityntäpysäköintiviitta bussi'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro216', 'Liityntäpysäköintiviitta raitiovaunu'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro217', 'Liityntäpysäköintiviitta metro'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro218', 'Liityntäpysäköintiviitta useita joukkoliikennevälineitä'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro219', 'Jalankulun viitta'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro220', 'Pyöräilyn viitta ilman etäisyyksiä'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro221', 'Pyöräilyn viitta etäisyyslukemilla'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro222', 'Pyöräilyn suunnistustaulu etäisyyslukemilla'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro223', 'Pyöräilyn suunnistustaulu ilman etäisyyksiä'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro224', 'Pyöräilyn etäisyystaulu'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro225', 'Pyöräilyn paikannimi'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro226', 'Umpitie edessä'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro227', 'Umpitie oikealla/vasemmalla'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro228', 'Umpitie'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro229', 'Enimmäisnopeussuositus'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro230', 'Etäisyystaulu'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro231', 'Paikannimi'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro232', 'Vesistön nimi'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro233', 'Kansainvälisen pääliikenneväylän numero'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro234', 'Valtatien numero'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro235', 'Kantatien numero'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro236', 'Seututien numero'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro237', 'Muun maantien numero'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro238', 'Kehätien numero'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro239', 'Eritasoliittymän numero'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro240', 'Opastus numeron tarkoittamalle tielle'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro241', 'Varareitti'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro242', 'Moottoritien tunnus'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro243', 'Moottoriliikennetien tunnus'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro244', 'Lentoasema'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro245', 'Autolautta'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro246', 'Matkustajasatama'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro247', 'Tavarasatama'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro248', 'Tavaraterminaali'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro249', 'Teollisuusalue tai yritysalue'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro250', 'Vähittäiskaupan suuryksikkö'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro251', 'Pysäköinti'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro252', 'Katettu pysäköinti'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro253', 'Rautatieasema'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro254', 'Linja-autoasema'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro255', 'Keskusta'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro257', 'Kuorma-autolle tarkoitettu reitti'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro258', 'Henkilöautolle tarkoitettu reitti'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro259', 'Linja-autolle tarkoitettu reitti'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro260', 'Pakettiautolle tarkoitettu reitti'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro261', 'Matkailuautolle tarkoitettu reitti'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro262', 'Moottoripyörälle tarkoitettu reitti'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro263', 'Mopolle tarkoitettu reitti'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro264', 'Polkupyörälle tarkoitettu reitti'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro265', 'Moottorikelkalle tarkoitettu reitti'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro266', 'Traktorille tarkoitettu reitti'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro267', 'Vaarallisten aineiden kuljetukselle tarkoitettu reitti'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro268', 'Jalankulkijalle tarkoitettu reitti'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro269', 'Esteetön reitti'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro270', 'Reitti, jolla on portaat alas'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro271', 'Reitti, jolla on portaat ylös'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro272', 'Reitti ilman portaita alas'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro273', 'Reitti ilman portaita ylös'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro274', 'Pyörätuoliramppi alas'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro275', 'Pyörätuoliramppi ylös'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro276', 'Hätäuloskäynti vasemmalla'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro277', 'Hätäuloskäynti oikealla'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro278', 'Poistumisreitti (yksi)'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro279', 'Poistumisreitti (useita)'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro280', 'Palvelukohteen opastustaulu'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro281', 'Palvelukohteen opastustaulu nuolella'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro282', 'Palvelukohteen erkanemisviitta'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro283', 'Palvelukohteen osoiteviitta'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro284', 'Palvelukohteen osoiteviitan ennakkomerkki'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro285', 'Radioaseman taajuus'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro286', 'Opastuspiste'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro287', 'Opastustoimisto'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro288', 'Ensiapu'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro289', 'Autokorjaamo'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro290', 'Polttoaineen jakelu bensiini tai etanoli'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro291', 'Polttoaineen jakelu paineistettu maakaasu'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro292', 'Polttoaineen jakelu sähkö'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro293', 'Polttoaineen jakelu vety'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro294', 'Hotelli tai motelli'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro295', 'Ruokailupaikka'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro296', 'Kahvila tai pikaruokapaikka'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro297', 'Käymälä'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro298', 'Retkeilymaja'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro299', 'Leirintäalue'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro300', 'Matkailuajoneuvoalue'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro301', 'Levähdysalue'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro302', 'Ulkoilualue'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro303', 'Hätäpuhelin'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro304', 'Sammutin'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro305', 'Museo tai historiallinen rakennus'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro306', 'Maailmanperintökohde'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro307', 'Luontokohde'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro308', 'Näköalapaikka'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro309', 'Eläintarha tai -puisto'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro310', 'Muu nähtävyys'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro311', 'Uintipaikka'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro312', 'Kalastuspaikka'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro313', 'Hiihtohissi'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro314', 'Maastohiihtokeskus'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro315', 'Golfkenttä'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro316', 'Huvi- ja teemapuisto'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro317', 'Mökkimajoitus'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro318', 'Aamiaismajoitus'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro319', 'Suoramyyntipaikka'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro320', 'Käsityöpaja'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro321', 'Kotieläinpiha'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro322', 'Ratsastuspaikka'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro323', 'Matkailutie (pelkkä teksti)'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro324', 'Matkailutie (kuva ja teksti)'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro325', 'Tilapäinen opastusmerkki'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro326', 'Kohde risteävässä suunnassa'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro327', 'Kohde risteävässä suunnassa oikealla'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro328', 'Kohde risteävässä suunnassa vasemmalla'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro329', 'Kohde risteävässä suunnassa alaoikealla'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro330', 'Kohde risteävässä suunnassa yläoikealla'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro331', 'Kohde risteävässä suunnassa ylävasemmalla'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro332', 'Kohde risteävässä suunnassa alavasemmalla'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro333', 'Kohde risteävässä suunnassa, kiertoliittymässä oikealla'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro334', 'Kohde risteävässä suunnassa, kiertoliittymässä vasemmalla'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro335', 'Kohde risteävässä suunnassa, kiertoliittymässä alaoikealla'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro336', 'Kohde risteävässä suunnassa, kiertoliittymässä yläoikealla'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro337', 'Kohde risteävässä suunnassa, kiertoliittymässä ylävasemmalla'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro338', 'Kohde risteävässä suunnassa, kiertoliittymässä alavasemmalla'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro339', 'Kohde nuolen suunnassa'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro340', 'Kohde nuolen suunnassa ja etäisyys'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro341', 'Kohde edessä ja etäisyys'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro342', 'Kohde nuolen suunnassa, kiertoliittymä'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro343', 'Vaikutusalueen pituus'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro344', 'Etäisyys kohteeseen'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro345', 'Etäisyys pakolliseen pysäyttämiseen'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro346', 'Vapaa leveys'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro347', 'Vapaa korkeus'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro348', 'Sähköjohdon korkeus'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro349', 'Vaikutusalue molempiin suuntiin oikealle ja vasemmalle'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro350', 'Vaikutusalue molempiin suuntiin eteen- ja taaksepäin'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro351', 'Vaikutusalue nuolen suuntaan'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro352', 'Vaikutusalue päättyy'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro353', 'Henkilöauto'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro354', 'Linja-auto'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro355', 'Kuormaauto'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro356', 'Pakettiauto'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro357', 'Matkailuperävaunu'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro358', 'Matkailuauto'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro359', 'Invalidin ajoneuvo'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro360', 'Moottoripyörä'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro361', 'Mopo'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro362', 'Polkupyörä'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro363', 'Moottorikelkka'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro364', 'Traktori'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro365', 'Vähäpäästöinen ajoneuvo'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro366', 'Pysäköintitapa reunakiven päälle'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro367', 'Pysäköintitapa reunakiven laitaan'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro368', 'Kielto ryhmän A vaarallisten aineiden kuljetukselle'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro369', 'Kielto ryhmän B vaarallisten aineiden kuljetukselle'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro370', 'Tunneliluokka'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro371', 'Voimassaoloaika arkisin ma-pe'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro372', 'Voimassaoloaika arkilauantaisin'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro373', 'Voimassaoloaika sunnuntaisin ja pyhinä'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro374', 'Aikarajoitus'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro375', 'Aikarajoitus ja voimassaoloaika'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro376', 'Pysäköintiajan alkamisen osoittamisvelvollisuus (keltainen pohja)'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro377', 'Pysäköintiajan alkamisen osoittamisvelvollisuus ja voimassaoloaika'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro378', 'Pysäköintiajan alkamisen osoittamisvelvollisuus (sininen pohja)'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro379', 'Maksullinen pysäköinti'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro380', 'Latauspaikka'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro381', 'Etuajooikeutetun liikenteen suunta'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro382', 'Etuajooikeutetun liikenteen suunta kääntyville'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro383', 'Kaksisuuntainen pyörätie (keltainen pohja)'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro384', 'Kaksisuuntainen pyörätie (sininen pohja)'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro385', 'Tekstillinen lisäkilpi'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro386', 'Huoltoajo sallittu'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro387', 'Hätäpuhelin ja sammutin'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro388', 'Sulkupuomi'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro389', 'Sulkuaita'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro390', 'Sulkuaita nuolilla'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro391', 'Sulkupylväs vasemmalla'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro392', 'Sulkupylväs oikealla'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro393', 'Sulkupylväs'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro394', 'Sulkukartio'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro395', 'Taustamerkki'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro396', 'Kaarteen suuntamerkki'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro397', 'Reunamerkki vasemmalla'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro398', 'Reunamerkki oikealla'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro399', 'Korkeusmerkki'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro400', 'Alikulun korkeusmitta'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro401', 'Liikennemerkkipylvään tehostamismerkki (sinivalkoinen)'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro402', 'Liikennemerkkipylvään tehostamismerkki (keltamusta)'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro403', 'Erkanemismerkki'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro404', 'Reunapaalu vasemmalla'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro405', 'Reunapaalu oikealla'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro406', 'Siirtokehotus'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro407', 'Paikannusmerkki'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro408', 'Automaattinen liikennevalvonta'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro409', 'Tekninen valvonta'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro410', 'Poronhoitoalue tekstillinen'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro411', 'Poronhoitoalue ilman tekstiä'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro412', 'Yleinen nopeusrajoitus rajalla'),
       ('v/vtlmln', 'liikennemerkki-lakinumero/liilnro413', 'Valtion raja');