-- Lisätään varustehaun integraation tyyppi integraatio tauluun
INSERT INTO integraatio (jarjestelma, nimi)
VALUES ('velho', 'varustetoteumien-haku');

CREATE TYPE kuntoluokka_tyyppi
AS ENUM ('Puuttuu', 'Erittäin huono', 'Huono', 'Tyydyttävä', 'Hyvä', 'Erittäin hyvä', 'Ei voitu tarkastaa');

CREATE TYPE kohdeluokka_tyyppi
AS ENUM (
    'varusteet/kaiteet', -- tl501 'Kaiteet'
    'varusteet/tienvarsikalusteet', -- tl503 tl504 tl505 tl507 tl508 tl516 *
    'varusteet/liikennemerkit', -- tl506 'Liikennemerkki'
    'varusteet/rumpuputket', -- tl509 'Rummut'
    'varusteet/kaivot', -- tl512 'Viemärit'
    'varusteet/reunapaalut', -- tl513 'Reunapaalut'
    'tiealueen-poikkileikkaus/luiskat', -- tl514 'Melurakenteet', tl518 'Kivetyt alueet'
    'varusteet/aidat', -- tl515 'Aidat'
    'varusteet/portaat', -- tl517 'Portaat'
    'tiealueen-poikkileikkaus/erotusalueet', -- tl518 'Kivetyt alueet'
    'varusteet/puomit-sulkulaitteet-pollarit', -- tl520 'Puomit'
    'varusteet/reunatuet', -- tl522 'Reunakivet'
    'ymparisto/viherkuviot' -- tl524 'Viherkuviot'
    );


-- Nimi: varustetoteuma_ulkoiset - taulun lisääminen
-- Kuvaus: Tierekisterin poistuessa Harja alkoi käyttää Velhoa (ja muitakin järjestelmiä)
-- varustetoteumien lähteenä.
--
-- Tämä taulu koostaa Ulkoisista järjestelmistä
-- haettujen toteumien ja varusteiden tiedot.

CREATE TABLE varustetoteuma_ulkoiset
(
    id               serial PRIMARY KEY    NOT NULL,
    ulkoinen_oid     varchar(128)          NOT NULL,
    urakka_id        integer               NOT NULL,
    tr_numero        integer               NOT NULL,
    tr_alkuosa       integer               NOT NULL,
    tr_alkuetaisyys  integer               NOT NULL,
    tr_loppuosa      integer,
    tr_loppuetaisyys integer,
    sijainti         geometry              NOT NULL,
    tietolaji        varchar(128)          NOT NULL, -- tl506,tl501 jne.
    lisatieto        varchar(128),
    toteuma          varustetoteuma_tyyppi NOT NULL,
    kuntoluokka      kuntoluokka_tyyppi    NOT NULL,
    alkupvm          date                  NOT NULL,
    loppupvm         date,
    muokkaaja        text                  NOT NULL,
    muokattu         timestamp             NOT NULL
);

CREATE UNIQUE INDEX varustetoteuma_ulkoiset_unique_versio ON varustetoteuma_ulkoiset (ulkoinen_oid, alkupvm);

CREATE TABLE varustetoteuma_ulkoiset_kohdevirhe
(
    id           serial PRIMARY KEY NOT NULL,
    ulkoinen_oid varchar(128)       NOT NULL,
    alkupvm      timestamp          NOT NULL,
    virhekuvaus  text -- Vastaava teksti, kuin minkä Harja kirjoitti lokiin virheestä
);

CREATE TABLE varustetoteuma_ulkoiset_viimeisin_hakuaika_kohdeluokalle
(
    kohdeluokka        kohdeluokka_tyyppi PRIMARY KEY NOT NULL,
    viimeisin_hakuaika timestamp                      NOT NULL
);

INSERT INTO koodisto_konversio (id, nimi, kuvaus)
VALUES ('v/vtlm', 'velho/liikennemerkki-asetusnumero', 'Varustetoteumien liikennemerkkien lisätietojen konversio');

INSERT INTO koodisto_konversio_koodit (koodisto_konversio_id, lahde, tulos)
VALUES ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro260', 'Traktorille tarkoitettu reitti'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro5', 'Jyrkkä alamäki'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro173', 'Palvelukohteen opastustaulu'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro115', 'Raitiovaunun pysäkki'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro184', 'Hotelli tai motelli'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro308', 'Paikallis- ja kaukoliikenteen linja-auton pysäkki'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro49', 'Kuorma- ja pakettiautolla ajo kielletty'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro312', 'Yksityisen tien viitta'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro140', 'Ajokaistan yläpuolinen viitta'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro130', 'Kävelykatu päättyy'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro186', 'Kahvila tai pikaruokapaikka'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro61', 'Kielletty ajosuunta'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro122', 'Tunneli'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro44', 'Väistämisvelvollisuus kohdattaessa'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro306', 'Maakunnanraja'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro269', 'Näköalapaikka'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro93', 'Pakollinen ajosuunta'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro156', 'Moottoritien tunnus'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro279', 'Suoramyyntipaikka'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro293', 'Euroopan unionin merkki rajalla'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro55', 'Linja-autolla ajo kielletty'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro145', 'Kevyen liikenteen viitta'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro54', 'Vaarallisten aineiden kuljetus kielletty'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro302', 'Tiekirkko'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro9', 'Avattava silta'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro183', 'Huoltoasema'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro198', 'Vaikutusalueen pituus'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro142', 'Ajokaistan yläpuolinen erkanemisviitta'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro315', 'Kiertotien viitta'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro181', 'Nähtävyys (sininen pohja)'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro39', 'Sivutuuli'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro251', 'Seututien numero'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro125', 'Taajama'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro120', 'Moottoriliikennetie'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro285', 'Etuajo-oikeutetun liikenteen suunta'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro162', 'Pysäköinti'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro214', 'Mopo'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro18', 'Lapsia'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro261', 'Matkailuajoneuvolle tarkoitettu reitti'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro310', 'Tienviitta'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro271', 'Muu nähtävyys'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro274', 'Hiihtohissi'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro52', 'Moottoripyörällä ajo kielletty'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro150', 'Etäisyystaulu'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro222', 'Voimassaoloaika sunn. ja pyhinä'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro80', 'Ajokaistakohtainen kielto tai rajoitus'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro105', 'Moottorikelkkailureitti'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro188', 'Retkeilymaja'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro63', 'Oikealle kääntyminen kielletty'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro147', 'Umpitie'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro177', 'Radioaseman taajuus'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro262', 'Polkupyörälle tarkoitettu reitti'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro213', 'Moottoripyörä'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro2', 'Mutka vasemmalle'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro298', 'Ajovalojen käyttö'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro13', 'Tietyö'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro289', 'Euroopan unionin merkki rajalla'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro20', 'Hiihtolatu'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro178', 'Opastuspiste'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro76', 'Nopeusrajoitus'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro256', 'Linja-autolle tarkoitettu reitti'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro85', 'Taksiasemaalue'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro249', 'Ajokaistaopastus keskikaiteellisella tiellä'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro230', 'Kaarteen suuntamerkki'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro38', 'Matalalla lentäviä lentokoneita'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro96', 'Pakollinen ajosuunta'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro228', 'Hätäpuhelin ja sammutin'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro62', 'Vasemmalle kääntyminen kielletty'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro317', 'Vaikutusalue nuolen suuntaan'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro48', 'Moottorikäyttöisellä ajoveuvolla ajo kielletty'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro109', 'Liityntäpysäköintipaikka'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro316', 'Kiertotien suuntanuoli'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro166', 'Jalankulkijoille tarkoitettu reitti'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro273', 'Kalastuspaikka'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro137', 'Ajokaistaopastus'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro314', 'Kiertotien viitta'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro16', 'Vaarallinen tien reuna'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro292', 'Euroopan unionin merkki rajalla'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro59', 'Jalankulku sekä polkupyörällä ja mopolla ajo kiell'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro133', 'Kiertotien suunnistustaulu'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro95', 'Pakollinen ajosuunta'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro229', 'Erkanemismerkki'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro267', 'Luontokohde'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro47', 'Ajoneuvolla ajo kielletty'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro305', 'Kunnanraja'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro90', 'Pakollinen pysäyttäminen tarkastusta varten'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro81', 'Pysäyttäminen kielletty'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro250', 'Osoiteviitan ennakkomerkki'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro236', '1612'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro176', 'Palvelukohteen osoiteviitta'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro172', 'Poistumisreitti'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro171', 'Hätäuloskäynti'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro187', 'Käymälä'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro207', 'Henkilöauto'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro100', 'Jalkakäytävä'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro155', 'Opastus numeron tarkoittamalle tielle'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro84', 'Pysäköintikieltoalue päättyy'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro4', 'Mutkia joista ensimmäinen vasemmalle'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro51', 'Traktorilla ajo kielletty'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro255', 'Henkilöautolle tarkoitettu reitti'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro246', 'Raitiovaunukaista päättyy'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro204', 'Vaikutusalue molempiin suuntiin'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro161', 'Teollisuusalue'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro225', 'Kaksisuuntainen pyörätie'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro208', 'Linja-auto'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro307', 'Paikannimi'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro128', 'Pihakatu päättyy'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro192', 'Ulkoilualue'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro35', 'Yksiraiteisen rautatien tasoristeys'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro320', 'Maksullinen pysäköinti'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro28', 'Liikenneympyrä'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro152', 'Valtatien numero'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro68', 'Ajoneuvon suurin sallittu massa'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro104', 'Pyörätie ja jalkakäytävä rinnakkain'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro92', 'Pakollinen ajosuunta'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro211', 'Matkailuajoneuvo'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro119', 'Moottoritie päättyy'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro287', 'Ajovalojen käyttö'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro159', 'Autolautta'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro301', 'Kameravalvonta'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro71', 'Ajoneuvon suurin sallittu telille kohdistuva massa'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro295', 'Poronhoitoalueen merkitseminen'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro175', 'Palvelukohteen erkanemisviitta'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro240', 'Linja-autokaista'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro58', 'Jalankulku kielletty'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro102', 'Yhdistetty pyörätie ja jalkakäytävä'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro185', 'Ruokailupaikka'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro41', 'Etuajooikeutettu tie'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro231', 'Reunamerkki'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro37', 'Putoavia kiviä'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro220', 'Voimassaoloaika arkisin ma-pe'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro97', 'Pakollinen kiertosuunta'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro6', 'Jyrkkä ylämäki'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro79', 'Nopeusrajoitusalue päättyy'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro45', 'Väistämisvelvollisuus risteyksessä'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro210', 'Pakettiauto'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro157', 'Moottoriliikennetien tunnus'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro200', 'Etäisyys pakolliseen pysäyttämiseen'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro288', 'Yleiset nopeusrajoitukset'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro233', 'Korkeusmerkki'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro31', 'Rautatien tasoristeys jossa on puomit'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro322', 'Etuajo-oikeutetun liikenteen suunta'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro121', 'Moottoriliikennetie päättyy'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro46', 'Pakollinen pysäyttäminen'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro226', 'Tekstillinen lisäkilpi'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro191', 'Levähdysalue'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro11', 'Liikenneruuhka'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro60', 'Ratsastus kielletty'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro103', 'Pyörätie ja jalkakäytävä rinnakkain'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro223', 'Aikarajoitus'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro143', 'Erkanemisviitta'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro283', 'Pysäköintikiekon käyttövelvollisuus (kieltomerkin'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro89', 'Pakollinen pysäyttäminen tullitarkastusta varten'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro237', 'Ajoneuvojen sijoitus pysäköintipaikalla'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro218', 'Kielto ryhmän A vaarallisten aineiden kuljetuksell'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro101', 'Pyörätie'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro199', 'Etäisyys kohteeseen'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro33', 'Rautatien tasoristeyksen lähestymismerkki'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro165', 'Tietyille ajoneuvoille tai ajoneuvoyhdistelmille t'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro82', 'Pysäköinti kielletty'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro25', 'Sivutien risteys'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro266', 'Museo tai historiallinen rakennus'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro215', 'Polkupyörä'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro169', 'Reitti jolla on portaat'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro15', 'Liukas ajorata'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro259', 'Mopolle tarkoitettu reitti'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro189', 'Leirintäalue'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro14', 'Irtokiviä'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro257', 'Pakettiautolle tarkoitettu reitti'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro309', 'Kaukoliikenteen linja-auton pysäkki'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro117', 'Yksisuuntainen tie'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro254', 'Kuorma-autolle tarkoitettu reitti'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro135', 'Kiertotieopastus'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro7', 'Kapeneva tie'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro88', 'Vuoropysäköinti'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro113', 'Pysäköintipaikka'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro164', 'Linja-autoasema'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro258', 'Moottoripyörälle tarkoitettu reitti'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro153', 'Kantatien numero'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro146', 'Liityntäpysäköintiviitta'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro124', 'Hätäpysäyttämispaikka'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro151', 'Kansainvälisen pääliikenneväylän numero'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro297', 'Maantie päättyy'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro239', 'Ajoneuvojen sijoitus pysäköintipaikalla'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro243', 'Linja-autokaista päättyy'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro17', 'Suojatien ennakkovaroitus'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro268', 'Maailmanperintökohde'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro253', 'Katettu pysäköinti'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro23', 'Tienristeys'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro57', 'Polkupyörällä ja mopolla ajo kielletty'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro163', 'Rautatieasema'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro141', 'Ajokaistan yläpuolinen viitta'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro212', 'Invalidin ajoneuvo'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro196', 'Kohde nuolen suunnassa'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro131', 'Suunnistustaulu'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro43', 'Etuajo-oikeus kohdattaessa'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro134', 'Kiertotien suunnistustaulu'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro290', 'Euroopan unionin merkki rajalla'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro241', 'Linja-autokaista'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro75', 'Ohituskielto kuorma-autolla päättyy'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro281', 'Kotieläinpiha'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro12', 'Epätasainen tie'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro73', 'Ohituskielto päättyy'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro136', 'Ajoreittiopastus'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro272', 'Uintipaikka'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro65', 'Ajoneuvon suurin sallittu leveys'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro160', 'Tavarasatama'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro24', 'Sivutien risteys'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro286', 'Taustamerkki varalaskupaikalla'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro311', 'Moottori- ja moottoriliikennetien viitta'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro56', 'Mopolla ajo kielletty'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro116', 'Taksiasema'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro197', 'Kohde nuolen suunnassa'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro106', 'Ratsastustie'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro8', 'Kaksisuuntainen liikenne'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro126', 'Taajama päättyy'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro182', 'Autokorjaamo'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro127', 'Pihakatu'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro313', 'Paikalliskohteen viitta'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro10', 'Lautta laituri tai ranta'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro205', 'Vaikutusalue molempiin suuntiin'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro303', 'Muu merkki (mm. ei numeroa)'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro284', 'Pysäköintikiekon käyttövelvollisuus (pysäköintipai'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro280', 'Käsityöpaja'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro32', 'Rautatien tasoristeyksen lähestymismerkki'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro319', 'Maksullinen pysäköinti'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro77', 'Nopeusrajoitus päättyy'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro264', 'Matkailutie'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro118', 'Moottoritie'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro78', 'Nopeusrajoitusalue'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro94', 'Pakollinen ajosuunta'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro98', 'Liikenteenjakaja'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro64', 'U-käännös kielletty'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro299', 'Ajovalojen käyttö'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro190', 'Matkailuajoneuvoalue'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro227', 'Tekstillinen lisäkilpi'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro247', 'Raitiovaunukaista päättyy'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro139', 'Ajokaistan päättyminen'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro209', 'Kuorma-auto'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro234', 'Alikulun korkeusmitta'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro238', 'Ajoneuvojen sijoitus pysäköintipaikalla'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro321', 'Etuajo-oikeutetun liikenteen suunta'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro252', 'Eritasoliittymän numero'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro36', 'Kaksi tai useampiraiteisen rautatien tasoristeys'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro232', 'Liikennemerkkipylvään tehostamismerkki'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro221', 'Voimassaoloaika lauantaisin'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro40', 'Muu vaara'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro277', 'Mökkimajoitus'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro107', 'Suojatie'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro291', 'Euroopan unionin merkki rajalla'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro86', 'Taksin pysäyttämispaikka'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro129', 'Kävelykatu'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro217', 'Pysäköintitapa'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro123', 'Tunneli päättyy'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro276', 'Huvi- tai teemapuisto'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro114', 'Kohtaamispaikka'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro50', 'Ajoneuvoyhdistelmällä ajo kielletty'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro27', 'Liikennevalot'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro42', 'Etuajo-oikeuden päättyminen'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro53', 'Moottorikelkalla ajo kielletty'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro70', 'Ajoneuvon suurin sallittu akselille kohdistuva mas'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro304', 'Tyhjä varsi (ei merkkiä)'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro30', 'Rautatien tasoristeys ilman puomeja'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro83', 'Pysäköintikieltoalue'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro278', 'Aamiaismajoitus'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro318', 'Vaikutusalue alkaa'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro26', 'Sivutien risteys'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro149', 'Enimmäisnopeussuositus'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro72', 'Ohituskielto'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro148', 'Umpitie'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro193', 'Hätäpuhelin'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro235', 'Töyssy'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro67', 'Ajoneuvon tai ajoneuvoyhdistelmän suurin sallittu'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro87', 'Vuoropysäköinti'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro168', 'Vaarallisten aineiden kuljetuksille tarkoitettu re'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro99', 'Liikenteenjakaja'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro22', 'Poroja'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro296', 'Ajovalojen käyttö'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro328', 'Taustamerkki'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro244', 'Raitiovaunukaista'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro216', 'Pysäköintitapa'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro248', 'Kiertosuositustaulu'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro167', 'Vammaisille tarkoitettu reitti'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro74', 'Ohituskielto kuorma-autolla'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro69', 'Ajoneuvoyhdistelmän suurin sallittu massa'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro194', 'Sammutin'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro170', 'Reitti ilman portaita'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro242', 'Linja-autokaista päättyy'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro201', 'Vapaa leveys'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro263', 'Palvelukohteen osoiteviitan ennakkomerkki'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro180', 'Ensiapu'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro144', 'Osoiteviitta'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro1', 'Mutka oikealle'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro91', 'Moottorikäyttöisten ajoneuvojen vähimmäisetäisyys'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro154', 'Muun maantien numero'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro21', 'Hirvieläimiä'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro275', 'Golfkenttä'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro245', 'Raitiovaunukaista'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro202', 'Vapaa korkeus'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro300', 'Väistämisvelvollisuus muuttunut'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro66', 'Ajoneuvon suurin sallittu korkeus'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro219', 'Läpiajokielto ryhmän B vaarallisten aineiden kulje'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro224', 'Tukkitie'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro19', 'Pyöräilijöitä'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro34', 'Rautatien tasoristeyksen lähestymismerkki'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro282', 'Ratsastuspaikka'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro174', 'Palvelukohteen opastustaulu'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro294', 'Poronhoitoalueen merkitseminen'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro158', 'Lentoasema'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro132', 'Suunnistustaulu'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro3', 'Mutkia joista ensimmäinen oikealle'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro265', 'Matkailutie'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro203', 'Sähköjohdon korkeus'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro138', 'Ajokaistaopastus'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro195', 'Kohde risteävällä tiellä'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro179', 'Opastustoimisto'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro270', 'Eläintarha tai -puisto'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro29', 'Raitiotie'),
       ('v/vtlm', 'liikennemerkki-asetusnumero/liiasnro206', 'Vaikutusalue päättyy');