-- name: vie-kanavatauluun<!
-- vie entryn kanava-tauluun
INSERT INTO kanava
(
  kanavanro,
  aluenro,
  nimi,
  kanavatyyppi,
  aluetyyppi,
  kiinnitys,
  porttityyppi,
  kayttotapa,
  sulku_leveys,
  sulku_pituus,
  alus_leveys,
  alus_pituus,
  alus_syvyys,
  alus_korkeus,
  sulkumaara,
  putouskorkeus_1,
  putouskorkeus_2,
  ALA_VER_1,
  ALA_VER_2,
  YLA_VER_1,
  YLA_VER_2,
  kynnys_1,
  kynnys_2,
  vesisto,
  kanavakokonaisuus,
  kanava_pituus,
  kanava_leveys,
  lahtopaikka,
  kohdepaikka,
  omistaja,
  geometria,
  luotu,
  luoja
)
VALUES
  (
    :kanavanro,
    :aluenro,
    :nimi,
    :kanavatyyppi,
    :aluetyyppi,
    :kiinnitys,
    :porttityyppi,
    :kayttotapa,
    :sulku_leveys,
    :sulku_pituus,
    :alus_leveys,
    :alus_pituus,
    :alus_syvyys,
    :alus_korkeus,
    :sulkumaara,
    :putouskorkeus_1,
    :putouskorkeus_2,
    :ALA_VER_1,
    :ALA_VER_2,
    :YLA_VER_1,
    :YLA_VER_2,
    :kynnys_1,
    :kynnys_2,
    :vesisto,
    :kanavakokonaisuus,
    :kanava_pituus,
    :kanava_leveys,
    :lahtopaikka,
    :kohdepaikka,
    :omistaja,
    ST_GeomFromText(:geometria) :: GEOMETRY,
    current_timestamp,
    :luoja
  )
ON CONFLICT (kanavanro)
  DO UPDATE
    SET
      kanavanro         = :kanavanro,
      aluenro           = :aluenro,
      nimi              = :nimi,
      kanavatyyppi      = :kanavatyyppi,
      aluetyyppi        = :aluetyyppi,
      kiinnitys         = :kiinnitys,
      porttityyppi      = :porttityyppi,
      kayttotapa        = :kayttotapa,
      sulku_leveys      = :sulku_leveys,
      sulku_pituus      = :sulku_pituus,
      alus_leveys       = :alus_leveys,
      alus_pituus       = :alus_pituus,
      alus_syvyys       = :alus_syvyys,
      alus_korkeus      = :alus_korkeus,
      sulkumaara        = :sulkumaara,
      putouskorkeus_1   = :putouskorkeus_1,
      putouskorkeus_2   = :putouskorkeus_2,
      ALA_VER_1         = :ALA_VER_1,
      ALA_VER_2         = :ALA_VER_2,
      YLA_VER_1         = :YLA_VER_1,
      YLA_VER_2         = :YLA_VER_2,
      kynnys_1          = :kynnys_1,
      kynnys_2          = :kynnys_2,
      vesisto           = :vesisto,
      kanavakokonaisuus = :kanavakokonaisuus,
      kanava_pituus     = :kanava_pituus,
      kanava_leveys     = :kanava_leveys,
      lahtopaikka       = :lahtopaikka,
      kohdepaikka       = :kohdepaikka,
      omistaja          = :omistaja,
      geometria         = :geometria :: GEOMETRY,
      muokattu          = current_timestamp,
      muokkaaja         = :muokkaaja;