-- name: luo-kanavasilta<!
INSERT INTO kan_silta
  (siltanro,
  nimi,
  tunnus,
  --kayttotarkoitus,
  tila,
  pituus,
  rakennetiedot,
  tieosoitteet,
  sijainti_lev,
  sijainti_pit,
  --geometria,
  --avattu,
  --trex_muutettu,
  trex_oid,
  trex_sivu,
  luoja,
  luotu)
VALUES (
  :siltanro,
  :nimi,
  :tunnus,
  --:kayttotarkoitus,
  :tila,
  :pituus,
  :rakennetiedot :: VARCHAR [],
  :tieosoitteet :: VARCHAR [][],
  :sijainti_lev,
  :sijainti_pit,
  --st_makepoint(:sijainti_lev, :sijainti_pit),
  --:avattu,
  --:trex_muutettu,
  :trex_oid,
  :trex_sivu,
  :luoja,
  CURRENT_TIMESTAMP)
ON CONFLICT (siltanro)
  DO UPDATE
    SET
  siltanro = :siltanro,
  nimi = :nimi,
  --tunnus = :tunnus,
  --kayttotarkoitus = :kayttotarkoitus,
  --tila = :tila,
  --pituus = :pituus,
   rakennetiedot = :rakennetiedot :: VARCHAR [],
   tieosoitteet = :tieosoitteet :: VARCHAR [][],
  --sijainti_lev = :sijainti_lev,
  --sijainti_pit = :sijainti_pit,
  -- geometria = st_makepoint(:sijainti_lev, :sijainti_pit),
  --avattu = :avattu,
  --trex_muutettu = :trex_muutettu,
  --trex_oid = :trex_oid,
  --trex_sivu = :trex_sivu,
  --muokkaaja = :muokkaaja,
  muokattu = CURRENT_TIMESTAMP;
