DO $$
DECLARE
  urakka_id_saimaan_kanava INTEGER := (SELECT id FROM urakka WHERE nimi = 'Saimaan kanava');
  sopimus_id_saimaan_paahuolto INTEGER := (SELECT id FROM sopimus WHERE nimi = 'Saimaan huollon pääsopimus');
  sopimus_id_saimaan_lisahuolto INTEGER := (SELECT id FROM sopimus WHERE nimi = 'Saimaan huollon lisäsopimus');
  kohde_id_tikkalansaaren_silta INTEGER := (SELECT id FROM kan_kohde WHERE nimi = 'Tikkalansaaren avattava ratasilta');
  huoltokohde_id_asennonmittauslaitteet INTEGER := (SELECT id FROM kan_huoltokohde WHERE nimi = 'ASENNONMITTAUSLAITTEET');
  kayttaja_id_jvh INTEGER := (SELECT id FROM kayttaja WHERE kayttajanimi = 'jvh');
  toimenpidekoodi_id_vv_laaja_yksiloimaton INTEGER := (SELECT id FROM toimenpidekoodi WHERE emo = (SELECT id FROM toimenpidekoodi WHERE koodi = '24104') AND nimi = 'Ei yksilöity');
  tpk_id_saimaan_kok_hint_tp INTEGER := (SELECT id FROM toimenpideinstanssi WHERE nimi = 'Saimaan kanava, sopimukseen kuuluvat työt, TP');
BEGIN
INSERT INTO kan_toimenpide
(tyyppi,
 urakka,
 sopimus,
 pvm,
 kohde,
 huoltokohde,
 toimenpidekoodi,
 lisatieto,
 suorittaja,
 kuittaaja,
 luotu,
 luoja,
 muokattu,
 muokkaaja,
 poistettu,
 poistaja,
 toimenpideinstanssi)
VALUES ('kokonaishintainen' :: KAN_TOIMENPIDETYYPPI,
  urakka_id_saimaan_kanava,
  sopimus_id_saimaan_paahuolto,
  '2017-10-10',
  kohde_id_tikkalansaaren_silta,
  huoltokohde_id_asennonmittauslaitteet,
  toimenpidekoodi_id_vv_laaja_yksiloimaton,
  'Testitoimenpide',
  kayttaja_id_jvh,
  kayttaja_id_jvh,
  '2017-10-10',
  kayttaja_id_jvh,
  '2017-10-10',
  kayttaja_id_jvh,
  FALSE,
  NULL,
  tpk_id_saimaan_kok_hint_tp);

INSERT INTO kan_toimenpide
(tyyppi,
 urakka,
 sopimus,
 pvm,
 kohde,
 huoltokohde,
 toimenpidekoodi,
 lisatieto,
 suorittaja,
 kuittaaja,
 luotu,
 luoja,
 muokattu,
 muokkaaja,
 poistettu,
 poistaja,
 toimenpideinstanssi)
VALUES ('kokonaishintainen' :: KAN_TOIMENPIDETYYPPI,
  urakka_id_saimaan_kanava,
  sopimus_id_saimaan_paahuolto,
  '2016-11-07',
  (SELECT id
   FROM kan_kohde
   WHERE nimi = 'Taipaleen sulku'),
  huoltokohde_id_asennonmittauslaitteet,
  toimenpidekoodi_id_vv_laaja_yksiloimaton,
  'Testitoimenpide',
  kayttaja_id_jvh,
  kayttaja_id_jvh,
  '2016-11-07',
  kayttaja_id_jvh,
  '2016-11-07',
  kayttaja_id_jvh,
  FALSE,
  NULL,
  tpk_id_saimaan_kok_hint_tp);

INSERT INTO kan_toimenpide
(tyyppi,
 urakka,
 sopimus,
 pvm,
 kohde,
 huoltokohde,
 toimenpidekoodi,
 lisatieto,
 suorittaja,
 kuittaaja,
 luotu,
 luoja,
 muokattu,
 muokkaaja,
 poistettu,
 poistaja,
 toimenpideinstanssi)
VALUES ('kokonaishintainen' :: KAN_TOIMENPIDETYYPPI,
  urakka_id_saimaan_kanava,
  sopimus_id_saimaan_lisahuolto,
  '2017-01-07',
  kohde_id_tikkalansaaren_silta,
  huoltokohde_id_asennonmittauslaitteet,
  toimenpidekoodi_id_vv_laaja_yksiloimaton,
  'Testitoimenpide',
  kayttaja_id_jvh,
  kayttaja_id_jvh,
  '2017-01-07',
  kayttaja_id_jvh,
  '2017-01-07',
  kayttaja_id_jvh,
  FALSE,
  NULL,
  tpk_id_saimaan_kok_hint_tp);

INSERT INTO kan_toimenpide
(tyyppi,
 urakka,
 sopimus,
 pvm,
 kohde,
 huoltokohde,
 toimenpidekoodi,
 lisatieto,
 suorittaja,
 kuittaaja,
 luotu,
 luoja,
 muokattu,
 muokkaaja,
 poistettu,
 poistaja,
 toimenpideinstanssi)
VALUES ('muutos-lisatyo' :: KAN_TOIMENPIDETYYPPI,
  urakka_id_saimaan_kanava,
  sopimus_id_saimaan_lisahuolto,
  '2017-01-07',
  kohde_id_tikkalansaaren_silta,
  huoltokohde_id_asennonmittauslaitteet,
  toimenpidekoodi_id_vv_laaja_yksiloimaton,
  'Testitoimenpide',
  kayttaja_id_jvh,
  kayttaja_id_jvh,
  '2017-01-07',
   kayttaja_id_jvh,
   '2017-01-07',
   kayttaja_id_jvh,
   FALSE,
   NULL,
   tpk_id_saimaan_kok_hint_tp);

INSERT INTO kan_toimenpide
(tyyppi,
 urakka,
 sopimus,
 pvm,
 kohde,
 huoltokohde,
 toimenpidekoodi,
 lisatieto,
 suorittaja,
 kuittaaja,
 luotu,
 luoja,
 muokattu,
 muokkaaja,
 poistettu,
 poistaja,
 toimenpideinstanssi)
VALUES ('muutos-lisatyo' :: KAN_TOIMENPIDETYYPPI,
  urakka_id_saimaan_kanava,
  sopimus_id_saimaan_paahuolto,
  '2017-01-11',
  kohde_id_tikkalansaaren_silta,
  huoltokohde_id_asennonmittauslaitteet,
  toimenpidekoodi_id_vv_laaja_yksiloimaton,
  'Testitoimenpide',
  kayttaja_id_jvh,
  kayttaja_id_jvh,
  '2017-01-07',
  kayttaja_id_jvh,
  '2017-01-07',
  kayttaja_id_jvh,
  FALSE,
  NULL,
  tpk_id_saimaan_kok_hint_tp);

INSERT INTO kan_toimenpide
(tyyppi,
 urakka,
 sopimus,
 pvm,
 kohde,
 huoltokohde,
 toimenpidekoodi,
 lisatieto,
 suorittaja,
 kuittaaja,
 luotu,
 luoja,
 muokattu,
 muokkaaja,
 poistettu,
 poistaja,
 toimenpideinstanssi)
VALUES ('muutos-lisatyo' :: KAN_TOIMENPIDETYYPPI,
  urakka_id_saimaan_kanava,
  sopimus_id_saimaan_paahuolto,
  '2017-01-12',
  kohde_id_tikkalansaaren_silta,
  huoltokohde_id_asennonmittauslaitteet,
  toimenpidekoodi_id_vv_laaja_yksiloimaton,
  'Testitoimenpide',
  kayttaja_id_jvh,
  kayttaja_id_jvh,
  '2017-01-07',
  kayttaja_id_jvh,
  '2017-01-07',
  kayttaja_id_jvh,
  FALSE,
  NULL,
  tpk_id_saimaan_kok_hint_tp);
  INSERT INTO kan_tyo ("toimenpidekoodi-id", maara, luoja) VALUES (toimenpidekoodi_id_vv_laaja_yksiloimaton, 4, kayttaja_id_jvh);
END $$;
