# Security hardening for GitHub Actions
# https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions

name: "[Chore] Clear unused caches (PR)"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:
    inputs:
      pr-number:
        description: "PR number"
        type: string
        required: true

# Aseta least-privilege default permissionit workflowille
# Job-kohtaiset oikeudet määritellään jobeissa erikseen
permissions: {}

jobs:
  cleanup:
    name: "Clear unused caches"
    runs-on: ubuntu-latest
    permissions:
      actions: write # Tarvitaan cachejen poistamiseen
      contents: read # Tarvitaan checkout actionissa
    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          # Estä turha kredentiaalien tallennus levylle (tietoturva)
          persist-credentials: false

      - name: Cleanup using GitHub Script
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        env:
          PR_NUMBER: ${{ github.event.pull_request.number || inputs.pr-number }}
        with:
          script: |
            const ref = `refs/pull/${process.env.PR_NUMBER}/merge`
            const { data } = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref,
            })
            
            console.log(`Found ${data.actions_caches.length} caches for ${ref}`)
            
            for (const cache of data.actions_caches) {
              console.log(`Deleting cache ${cache.key} for ${cache.ref}`)
            
              const result = await github.rest.actions.deleteActionsCacheById({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  cache_id: cache.id,
              });
            
              if (result.status !== 204) {
                console.warn(`Failed to delete cache ${cache.key} for ${cache.ref}`)
              }
            }
