# Security hardening for GitHub Actions
# https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions

name: '[Scheduled] Harja: Deploy to production'
run-name: '[Scheduled] Harja: Deploy latest successful build to production'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  # Anna edellisen deploymentin mennä rauhassa loppuun, koska mahdollisesti käynnissä olevaa AWS migration lambdaa ei pysty canceloimaan
  # Jos edellinen deployment on ehtinyt migraatioiden ajon vaiheeseen, canceloiminen voi aiheuttaa ongelmia.
  cancel-in-progress: false

on:
  # Manuaalisen käynnistyksen asetukset
  workflow_dispatch:
  # Ajastettu käynnistys (Ajetaan deployment joka arkipäivä klo 7 (Huom, GitHub actions on UTC-aikavyöhykkeessä))
  #schedule:
  #  - cron: '0 4 * * 1-5'

# TODO:
#  - Hae viimeisin onnistunut build ja sen tiedot (run_id ja liittyvä commit SHA)
#  - Muokkaa reusable_deploy-harja-image-to-ecs.yml tiedostoa niin, että se ottaa parametrina viimeisimmän onnistuneen buildin tiedot
#    - Muokkaa jobia niin, että se hakee viimeisimmän build artifactin run_id:n perusteella
#    - Muokkaa jobia niin, että se ajaa migraatiot jobille annetun commit SHA:n perusteella
#    - Lisää reusable_deploy-harja-image-to-ecs.yml omaksi jobin ajoksi tähän workflowhun
#  - Hae get-last-successful-build jobin outputista viimeisin onnistunut buildin run_id ja commit SHA

jobs:

  get-latest-succesful-build:
    runs-on: ubuntu-latest
    env:
      # Scriptin käyttämät ympäristömuuttujat
      WORKFLOW_ID: 'harja_build_and_deploy.yml'
      BRANCH_NAME: 'develop'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get latest succesful build
        uses: actions/github-script@v7
        id: latest-successful-build
        # Palauta result jobin outputtiin
        with:
          retries: 3
          result-encoding: json
          script: |
            const script = require('./.github/scripts/get-latest-successful-run.js')
            const result = await script({github, context, core})
            console.log(result)
            
            core.setOutput("commit-sha", result.commit_sha);
            core.setOutput("run-id", result.run_id);

      # https://github.com/github/vscode-github-actions/issues/188
      - name: Get results
        run: |
          echo "${{ steps.latest-successful-build.outputs.latest-commit-sha }}"
          echo "${{ steps.latest-successful-build.outputs.run-id }}"

      - name: Run deployment
        run: |
          echo "Latest successful commit SHA: ${{ steps.latest-successful-build.outputs.latest-commit-sha }}"
          echo "Latest succesfull run ID: ${{ steps.latest-successful-build.outputs.run-id }}"
          echo "TODO..."

            


