# Security hardening for GitHub Actions
# https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions

name: 'Harja: Test Pull Request'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

on:
  # Manuaalisen käynnistyksen asetukset
  workflow_dispatch:
  # Workflow ajetaan automaattisesti jokaiselle PR:lle, jonka base branch on develop
  pull_request:
    branches: [ develop ]

jobs:
  tests:
    uses: ./.github/workflows/reusable_run_app_tests.yml
    # Permissions
    # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
    # https://docs.github.com/en/actions/using-workflows/reusing-workflows#access-and-permissions
    permissions:
      # Contents read lupaa tarvitaan checkout actionissa
      contents: read
      # Packages read lupaa tarvitaan Harjan testaukseen tarkoitettujen Docker imageiden pullaamiseen
      packages: read
      # Actions write oikeudella voidaan esim. listata ja poistaa artifacteja
      actions: write
      # Tarvitaan test-reportin julkaisuun PR:ssä
      checks: write
    strategy:
      # Halutaan, että kaikki testit käydään läpi.
      # Yksittäinen flaky testi ei saa kaataa koko testimatriisia.
      fail-fast: false
      max-parallel: 2
      matrix:
        # Katso saatavilla olevat harjadb servicet docker-compose.yml:stä
        configs: [
          { testDBService: "harjadb-latest", e2eBrowsers: ['chrome'], artifactPrefix: 'harjadb-latest_' },
          { testDBService: "harjadb-12-3.1", e2eBrowsers: ['chrome', 'edge'], artifactPrefix: 'harjadb-12-3.1_' },
        ]

    with:
      test-db-service: ${{ matrix.configs.testDBService }}
      e2e-browsers: ${{ toJSON(matrix.configs.e2eBrowsers) }}
      artifact-prefix: ${{ matrix.configs.artifactPrefix }}
      lint-clj: 'false'
