name: 'Harja: Scan AWS ECS Fargate image (manual)'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

on:
  workflow_dispatch:

# Aseta least-privilege default permissionit workflowille
# Job-kohtaiset oikeudet määritellään jobeissa erikseen
permissions: {}

jobs:
  build-and-scan:
    name: "Build and scan Fargate image"
    runs-on: ubuntu-latest
    # README: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
    permissions:
      contents: read # Tarvitaan checkout actionissa
      packages: read # Tarvitaan Docker imageiden pullamiseen GH Container Registrystä

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          # Estä turha kredentiaalien tallennus levylle (tietoturva)
          persist-credentials: false

      - name: Log in to the Container registry
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Testitietokantaa tarvitaan buildin yhteydessä
      - name: Start test database
        uses: ./.github/actions/start-test-db
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          # Katso saatavilla olevat harjadb servicet docker-compose.yml:stä (esim. harjadb-latest)
          # Käytetään uusinta saatavilla olevaa testidb:tä AWS buildeissa.
          service-name: harjadb-latest


      # Huom: Build-action tarvitsee testitietokannan taustalle ennen buildin ajoa
      - name: Build Harja Uberjar
        uses: ./.github/actions/build-harja-app
        with:
          build-laadunseuranta: 'false'

      - name: Docker build
        env:
          COMMIT_SHA: ${{ github.sha }}
        run: docker build -t harja-app:${COMMIT_SHA} --file aws/fargate/Dockerfile .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          image-ref: 'harja-app:${{ github.sha }}'
          # Sallitaan ainoastaan table-formaatin tulostus, koska manuaalisen ajon SARIF upload aiheuttaisi ristiriitoja
          #   develop-branchin SARIF-tulosten kanssa.
          format: 'table'
          # ignore-unfixed: true
          scanners: vuln,secret,misconfig
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'
