# Security hardening for GitHub Actions
# https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions

name: "Harja-infra: Start Fargate Tasks"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Valitse deploy-ympäristö"
        required: true
        type: choice
        options:
          - dev
          - stg
          - prod

# Aseta least-privilege default permissionit workflowille
# Job-kohtaiset oikeudet määritellään jobeissa erikseen
permissions: {}

jobs:
  start-fargate-tasks:
    name: "Start Fargate tasks"
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      # Käytä ympäristökohtaisia salaisuuksia, mutta estä GitHub deployment-objektin luonti, jotta ei synny turhaa kohinaa.
      deployment: false

    # README: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
    permissions:
      id-token: write # OIDC tokenia tarvitaan AWS roolin omaksumiseen
      contents: read # Tarvitaan checkout actionissa

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          # Estä turha kredentiaalien tallennus levylle (tietoturva)
          persist-credentials: false

      - name: List used environment variables
        env:
          ENVIRONMENT: ${{ inputs.environment }}
          ECR_REPOSITORY_NAME: ${{ vars.ECR_REPOSITORY_NAME }}
          ECS_TASK_DEFINITION_NAME: ${{ vars.ECS_TASK_DEFINITION_NAME }}
          ECS_CONTAINER_NAME: ${{ vars.ECS_CONTAINER_NAME }}
          ECS_CLUSTER_NAME: ${{ vars.ECS_CLUSTER_NAME }}
          ECS_SERVICE_NAME: ${{ vars.ECS_SERVICE_NAME }}
        run: |
          echo "Target environment: ${ENVIRONMENT}"
          echo "Environment variables:"
          echo "  ECR_REPOSITORY_NAME: ${ECR_REPOSITORY_NAME}"
          echo "  ECS_TASK_DEFINITION_NAME: ${ECS_TASK_DEFINITION_NAME}"
          echo "  ECS_CONTAINER_NAME: ${ECS_CONTAINER_NAME}"
          echo "  ECS_CLUSTER_NAME: ${ECS_CLUSTER_NAME}"
          echo "  ECS_SERVICE_NAME: ${ECS_SERVICE_NAME}"
        shell: bash

      - name: Assume role with OIDC
        uses: aws-actions/configure-aws-credentials@d979d5b3a71173a29b74b5b88418bfda9437d885 # v6.1.1
        with:
          aws-region: "eu-west-1"
          role-to-assume: "arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/cicd-github-harja-app-admin"
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      - name: Start Harja Fargate tasks
        uses: ./.github/actions/start-fargate-tasks
        timeout-minutes: 10
        # Pakota uudelleenkäynnistyminen
        if: always()
        with:
          cluster: ${{ vars.ECS_CLUSTER_NAME }}
          service: ${{ vars.ECS_SERVICE_NAME }}
